### ISSUE TITLE
[Feature Request] Version naming system should be sortable

### ISSUE THREAD

**Issue by costrouc** [lammps/lammps#941] opened 2018-06-06 13:38 UTC
## Summary

Many packaging systems require that version numbers be sortable to determine the latest release. I have built lammps for [anaconda](https://anaconda.org/costrouc/lammps/files) and other packaging systems. The current version naming system makes it such that package build systems do not grab the latest version. This could easily be fixed by adopting [semvar](https://semver.org/) or something similar such are changing the ordering of the naming.

Instead of `<type>-<day><month-name><year>` I suggest `<year><month><day>-<type>`. For example `stable_16Mar2018` -> `20180316_stable`.

## Type of Issue

Suggestion for enhancement

## Detailed Description (Enhancement Suggestion)

Want some version naming system that when using `sort` will order the releases from latest to oldest.

**Comment by rbberger** [comment] 2018-06-06 14:03
We had this discussion before, see #617

**Comment by akohlmey** [comment] 2018-06-06 14:16
In the discussion on issue #617 @sjplimp stated, that he doesn't want to change the scheme since it would require lots of changes to different places and it would break the tools he is using for managing releases. I also stated in that discussion, that it is easy to convert a date format like is used in the LAMMPS version string to a sortable number. We do this internally in LAMMPS to allow numerical comparisons on the LAMMPS script level. Nothing keeps you from using such a converted date string in versioning your packages. If your packaging tool or the scripts, you use to drive it, cannot handle this conversion, then it is a weakness of the packaging tool or the scripts, not a LAMMPS issue. Since this is a duplicate of a discussion that has been finished, I'm closing this now.

**Comment by costrouc** [comment] 2018-06-06 14:16
Apologies sorry about that.

**Closed by akohlmey** 2018-06-06 14:16 UTC
Labels: duplicate

**Comment by junghans** [comment] 2018-06-06 15:22
Duplicate of #617
