### ISSUE TITLE
Fix rigid restart is not exact

### ISSUE THREAD

**Issue by cleboo** [lammps/lammps#428] opened 2017-03-21 15:36 UTC
Hi all!

I am using fix/rigid/npt to integrate a system of molecules. Restarting a simulation from a restart file does not result in the same trajectory.

As of now, fix/rigid/nh only writes thermo-/barostat variables to the restart file, while the quaternions and the conjugated momenta are reconstructed from the particle coordinates and velocities. I would guess, that this leads to small errors that change the resulting trajectory.

- I tried to use the external restart file of fix/rigid. This improves the situation a little bit, but this file is a plain text file and also reconstructing the system state from this file seems to involve some computation which may introduce some small error.

- Is it feasible to add all dynamic variables to the restart file? I would expect, that one needs xcm, vcm, inertia, e*_space, angmom, quat and imagebody in addition to the bath-variables.

- I attached an example. the graph shows the potential energy as a function of time for 2 trajectories, where the second one has been started from a restart file of the first one.

![pot_energy_comparison](https://cloud.githubusercontent.com/assets/6784851/24155067/14be3562-0e53-11e7-98ec-f92c2d9638f4.png)

[rigid_tip4p_restart_test.zip](https://github.com/lammps/lammps/files/858648/rigid_tip4p_restart_test.zip)

**Comment by akohlmey** [comment] 2017-03-21 17:45
There is nothing unexpected here. The graph shows that the restarted run is close to the original run and starts diverging after a few 1000s of time steps. since LAMMPS is doing floating point math, restarts can never be 100% exact. a restart enforces a reneighboring which can change the order of atoms in the local arrays, which changes the order in which forces are summed up. for variable cell time integration, this divergence is emphasized because the pressure is very sensitive to such small differences and that influences the volume of the cell, which in turn affects all positions through the back-and-forth conversion to scaled and back to unscaled coordinates (a computation that adds more numerical noise as well).

you can induce similar divergences easily with other measures, e.g. changing the neighborlist rebuild frequency, but that doesn't make the resulting trajectories incorrect. they sample the same phase space and that matters.

**Comment by cleboo** [comment] 2017-03-21 20:05
Well "incorrect" is a strong word, I would not have used... It depends, when you look at a trajectory where something happens in a specific way, being able to restart it and get the exact same results, can be very useful. Also when using the LAMMPS engine as a basis for things like hybrid Monte-Carlo, being able to reset to the exact state is a big bonus.

Btw., it works beautifully for NVE with liquid Lennard-Jonesium. 180000 steps and counting without a discrepancy. I am just wondering, whether I can get the same thing for the rigid integrator if I dump the variables mentioned above into the restart file and read them from there again.

With regards to the NpT integrator, is there a way to force the reneighboring, similar to what is done while reading from the restart file? And do you think, there are any other obvious sources of such tiny inaccuracies apart from the neighbor lists?

**Comment by akohlmey** [comment] 2017-03-21 20:27
first off, LAMMPS has the "rerun" command, where one can exactly repeat a trajectory and then do computations based on the pre-recorded positions (and other supported properties).

if you want "exact" exact, then you have to write an MD code based on fixed point math. i still fail to see the point why something has to be exactly reproduced beyond the typical few thousand MD steps that you can achieve. since the intrinsic divergence is exponential, i would expect that there is little you can do to massively improve the situation for NPT.

i vaguely recall a graph in allen and tildesley (i think) comparing the accumulated error for different integrators versus the length of timestep. one of the points made in it was, that reducing the time step can give some short time improvement, but at some point it is overcompensated by having to do more floating point operations with their inherent errors, which will contribute to the divergence from the "ideal" trajectory.

you can force reneighboring in every step (and take a significant performance penalty) with `neigh_modify every 1 delay 0 check no`, but the step that i think emphasizes divergence is the scaling/unscaling in combination with the cell size update and the fact, that it is dependent on stress, which is quite noisy, especially when using long-range electrostatics.

i am not surprised that fix nve has a much better conservation as there is less "interference".

**Comment by cleboo** [comment] 2017-03-22 14:27
Hi,

and thanks for your answer!

There are two issues here, one is the chaotic behavior of the system your are speaking of, which leads to the exponential divergence of trajectories given small changes in the initial conditions or the integrator. I agree, that this is the reason why the trajectories depart from each other.

Nevertheless, the algorithm is in principle deterministic even if it is executed with finite precision, i.e. given the same initial conditions (particle positions, momenta, thermostat variables, neighbor list state....) and the same integrator (same binary code with the same libraries, on the same number of processors,...), will yield _exactly_ the same result. This is the case if I run a simulation from the same initial conditions twice and also for the NVE integrator if I restart it, as can be seen in this plot:
![pot_energy_comparison](https://cloud.githubusercontent.com/assets/6784851/24192650/f9e6ec00-0eef-11e7-9c12-79e3d870558b.png)

Here, the initial conditions are reproduced exactly. I know of other NpT simulation code that can do this as well, so it is in principle possible...

I tried using `neigh_modify every 1 delay 0 check no` in order to get the same thing with NpT, however, that does not change this behavior. 
Out of curiosity, does the number of bins in the neighbor list change as the volume changes during a simulation run? When I create the simulation initially the neighbor list info says 12 bins each, while in the restarted version it is 13.

As to an example for the usefulness, think of a long trajectory where you wait for something to happen. You may have a limited amount of hard disk available, so you simply can not save the whole trajectory in full detail. But you can still simulate the details of the event if you can exactly reproduce the state of the system and then do a second simulation where you include more detail.

**Comment by akohlmey** [comment] 2017-03-22 15:41
OK. i agree, that it is theoretically possible. It used to be near impossible with 32-bit x86 code, because the standard x86 floating-point unit would be in 80-bit mode by default and the mere process of restarting would cause differences unless the code was compiled with -ffloat-store (when using GNU) to force truncating/rounding to 64-bit or using proper instructions to force the FPU into 64-bit mode. on 64-bit x86 things are a bit better because the SSE unit is used by default and that one is 64-bit and IEEE 754 compatible.

as far as the binning is concerned, yes the bins are recomputed on every reneighboring. from neighbor.cpp:
```
/* ----------------------------------------------------------------------
   setup neighbor binning and neighbor stencils
   called before run and every reneighbor if box size/shape changes
   only operates on perpetual lists
   build_one() operates on occasional lists
------------------------------------------------------------------------- */

void Neighbor::setup_bins()
{
```

the application example you provide is quite extreme, so i don't think the effort required to figure out what additional data needs to be stored and how to reduce the divergence (i am not convinced that with the way cell size updates are done in LAMMPS it is possible to have perfect reproducibility with a nose-hoover barostat and thermostat, there are just too many options for introducing noise), is worth the benefit. if you are willing to dig into it, though, you are welcome. if the required changes are not too intrusive and collide with other issues, i am certain, that steve is willing to include them.

however, in my personal opinion, a better solution to your application example would be a TMD-like approach that adds forces (which will obviously be quite small) while following a coarsely prerecorded trajectory along to reproduce it with higher resolution. unlike in TMD, you can use velocities for improved guiding of the atoms and determining the corrective forces. an implementation of this could use code from the "rerun" command and would have the advantage of being a generic solution that is **not** dependent on having the same binary, compiler, hardware, number of processors, etc.

**Comment by akohlmey** [comment] 2017-03-22 15:43
One more thing on NPT the integrator. Check out where your reference point for scaling/unscaling of the cell is. When set to the center of the box, the noise from cell updates is much less than when it is on the corner.

**Comment by cleboo** [comment] 2017-03-23 11:46
Okay, cool, thanks! Everything that increases the amount of time the trajectories are close is a good thing.

I found another hack that works --- I just write out restart files and instead of simply continuing the simulation, I start a new one, from the checkpoint just written.

I think it would be interesting as a feature to force a similar behavior when writing restart files, so they are "exactly" restartable even though this disturbs the trajectory by a tiny amount and may cost a little bit of performance.

**Comment by akohlmey** [comment] 2017-04-04 18:03
since no other LAMMPS developer has chimed in and volunteered to try addressing this issue through adding more data to the restart, and since an acceptable workaround has been found, i am closing this now.

**Closed by akohlmey** 2017-04-04 18:03 UTC
