### ISSUE TITLE
[BUG] Type label containing "number-number" raises "invalid range string: -1" error

### ISSUE THREAD

**Issue by benjamindjensen** [lammps/lammps#4300] opened 2024-08-28 13:24 UTC
**Summary**

If a type label contains two numbers separated by a hyphen a "invalid range string: -1 error" is raised. For example:

```
Bond Type Labels

1 c2-2hc
```
or 
```
Dihedral Type Labels

1 [*:1]~[#7X3,#7X2-1:2]-!@[#6X3:3]~[*:4]mult:0
```

**LAMMPS Version and Platform**

LAMMPS (27 Jun 2024 - Development - patch_27Jun2024-956-g6e791034f9)

OS: Linux "Red Hat Enterprise Linux 8.10 (Ootpa)" 4.18.0-553.8.1.1toss.t4.x86_64 x86_64

Compiler: Intel Classic C++ 19.10.3 / Intel(R) C++ g++ 8.5 mode with OpenMP 5.0 preview 1
C++ standard: C++11
MPI v3.1: HPE MPT 2.28  04/25/23 14:36:47-mraymond

**Expected Behavior**

Expected type labels to be able to contain this sequence of numbers and hyphens

**Actual Behavior**

"invalid range string: -1 error" is raised

**Steps to Reproduce**

Modify an example, such as `lammps/examples/PACKAGES/reaction/tiny_epoxy/tiny_epoxy.dat` to contain a type label with number-number:

```
diff --git a/examples/PACKAGES/reaction/tiny_epoxy/tiny_epoxy.data b/examples/PACKAGES/reaction/tiny_epoxy/tiny_epoxy.data
index 90c074fde0..c4e74fe4fc 100644
--- a/examples/PACKAGES/reaction/tiny_epoxy/tiny_epoxy.data
+++ b/examples/PACKAGES/reaction/tiny_epoxy/tiny_epoxy.data
@@ -30,7 +30,7 @@ Atom Type Labels
 
 Bond Type Labels
 
-1 c2-hc
+1 c2-2hc
 2 c3m-c2
 3 c2-oc
 4 c3m-o3e

```

**Further Information, Files, and Links**

**Comment by akohlmey** [comment] 2024-08-28 14:32
@benjamindjensen I cannot reproduce this. If I make the suggested change, LAMMPS will throw an error because the reaction template files still contain 'c2-hc' which is now undefined.
And if I globally replace all instances of 'c2-hc' with 'c2-2hc' using `sed`, the input completes without a problem.

**Comment by akohlmey** [comment] 2024-08-28 14:55
> "invalid range string: -1 error" is raised

Please quote the *complete* error message. It contains useful information.

**Comment by benjamindjensen** [comment] 2024-08-28 14:55
The error I get occurs when `tiny_epoxy.data` is read, so it doesn't make it to reading the template files.

The results above are from a HPC. When I try the same inputs on my local laptop (OSX) it runs without error. Both LAMMPS versions are similar. Details of my OSX installation are below. Could the compiler or packages installed be impacting how the input is read? I can provide more details of the HPC installation if helpful.

OSX machine that does not produce the error with the same inputs:
```
27 Jun 2024
Git info (develop / patch_27Jun2024-524-g4b756e0b1c)

OS: Darwin 23.6.0 x86_64

Compiler: Clang C++ Apple LLVM 15.0.0 (clang-1500.3.9.4) with OpenMP not enabled
C++ standard: C++11
MPI v1.0: LAMMPS MPI STUBS for LAMMPS version 27 Jun 2024
```

**Comment by benjamindjensen** [comment] 2024-08-28 14:57
> > "invalid range string: -1 error" is raised
> 
> Please quote the _complete_ error message. It contains useful information.

```
LAMMPS (27 Jun 2024 - Development - patch_27Jun2024-956-g6e791034f9)
  using 1 OpenMP thread(s) per MPI task
Reading data file ...
  orthogonal box = (10 -10 -15) to (30 20 10)
  1 by 1 by 1 MPI processor grid
  reading atom labelmap ...
  reading bond labelmap ...
  reading angle labelmap ...
  reading dihedral labelmap ...
  reading improper labelmap ...
ERROR: Invalid range string: -1 (src/CLASS2/angle_class2.cpp:279)
Last command: read_data tiny_epoxy.data   extra/special/per/atom 25

```

**Comment by akohlmey** [comment] 2024-08-28 14:58
> Could the compiler or packages installed be impacting how the input is read?

You seem to be using Intel compilers where it is failing. Some versions of it are known to optimize too aggressively and thus miscompile code. Try compilation with GCC or Clang.

**Comment by benjamindjensen** [comment] 2024-08-28 15:44
That seems to be the issue. I compiled with gnu compilers and now it runs without problems.

GNU system that works:
```
27 Jun 2024 - Development
Git info (develop / patch_27Jun2024-956-g6e791034f9-modified)

OS: Linux "Red Hat Enterprise Linux 8.10 (Ootpa)" 4.18.0-553.16.1.1toss.t4.x86_64 x86_64

Compiler: GNU C++ 13.2.0 with OpenMP 4.5
C++ standard: C++11
MPI v3.1: HPE MPT 2.28  04/25/23 14:36:47-mraymond
```

**Comment by jrgissing** [comment] 2024-08-28 15:49
Ben, thanks for that report. @akohlmey so, this is not something we have to address?

**Comment by akohlmey** [comment] 2024-08-28 15:52
@jrgissing Yes, this is bogus and not the first case where Intel compilers are miscompiling LAMMPS. By coincidence, there is another case of problems due to the Intel compilers discussed on MatSci right now: https://matsci.org/t/segfault-using-rebo-potential/57302/6

We may need to add some warning to the manual.

**Comment by akohlmey** [comment] 2024-08-28 15:52
@benjamindjensen closing this for now. Please re-open if the issue reappears with other compilers than Intel.

**Closed as not planned by akohlmey** 2024-08-28 15:52 UTC
Labels: bug, unconfirmed

**Comment by stanmoore1** [comment] 2024-08-28 15:58
@benjamindjensen can you try compiling with `-fp-model precise` and see if that helps?

**Comment by benjamindjensen** [comment] 2024-08-28 17:20
@stanmoore1, compiling with intel and `-fp-model precise` also solves the issue for me. 

Thank you @stanmoore1  and @akohlmey.

**Comment by stanmoore1** [comment] 2024-08-28 17:22
> @stanmoore1, compiling with intel and `-fp-model precise` also solves the issue for me.

Interesting--we have to use that for another code too.
