### ISSUE TITLE
[BUG] _temper/npt restart index

### ISSUE THREAD

**Issue by matiasf86** [lammps/lammps#3854] opened 2023-07-14 23:38 UTC
**Summary**

The command temper/npt is not working as expected is not getting the restart flag "index"  as pointed in the doc page, 
Also it says that it can take a different pressure for each replica, but it seems this is not the case. 

**LAMMPS Version and Platform**

LAMMPS (28 Mar 2023)

**Expected Behavior**
As the manual says for temper/npt the same features as temper applies and also replicas of varying pressure 

**Actual Behavior**

If I put a number in the index flag it gives an error 

**Further Information, Files, and Links**

I have detect in the code that 

line 77   double press_set = utils::numeric(FLERR,arg[6],false,lmp);

line 92  if (narg == 8) my_set_temp = utils::inumeric(FLERR,arg[6],false,lmp);

In line 92 my_set_temp is being assigned to the pressure and not to the index flag, position 6, when it should take position 7, I believe 

I believe this should be changed 

Also I don't see a pressure swap in the code, i might be missing where it is . Anyway  if this was not intended this might be explicit in the manual 

Thanks for the help 
Matias

**Comment by akohlmey** [comment] 2023-07-15 00:15
Thanks for your report. I can confirm that the parsing of the index is indeed a bug (and it has been there since the code was merged into LAMMPS, which suggests that this is not a well tested feature). It has been changed in commit 78d3d4948f281c62e57e4f5ec200afcca5145ef2 and should be merged into the develop branch for the next release.

For your question about the pressure swap (and a possible clarification in the manual), you need to contact the developer @amilumas (email address is listed in the source).

**Closed as completed** 2023-07-17 23:00 UTC
Labels: bug
