### ISSUE TITLE
KOKKOS CUDA fails compiling with USER-REAXC and USER-OMP

### ISSUE THREAD

**Issue by andeplane** [lammps/lammps#535] opened 2017-06-19 16:57 UTC
Not a big problem in itself, but might indicate som other problem that may appear elsewhere. Anyway, I just cloned `master` and did

```
make yes-kokkos yes-user-reaxc yes-user-omp
make -j20 kokkos_cuda_openmpi
```
where compilation fails on
```
../reaxc_valence_angles_omp.cpp: In function 'void Valence_AnglesOMP(reax_system*, control_params*, simulation_data*, storage*, reax_list**, output_controls*)':
../reaxc_valence_angles_omp.cpp:259:1: error: expected primary-expression before '}' token
     {
 ^
../reaxc_valence_angles_omp.cpp:254:20: error: barrier region may not be closely nested inside of work-sharing, critical, ordered, master or explicit task region
../reaxc_valence_angles_omp.cpp:258:9: error: master region may not be closely nested inside of work-sharing or explicit task region
 #pragma omp master
         ^
Makefile:108: recipe for target 'reaxc_valence_angles_omp.o' failed
```

This does not happen if I compile with `make -j20 kokkos_omp`. I'm using Ubuntu 16.04 and CUDA 8.0.

**Comment by akohlmey** [comment] 2017-06-19 17:27
Aa far as i understand it, the following is happening. When compiling KOKKOS with CUDA, all files are compiled twice: once with g++/icpc, once with nvcc. for non-KOKKOS sources, the nvcc step should not produce any output of note, but it has to parse the entire code, including - when OpenMP is enabled - the OpenMP pragmas. This is where things go awry. nvcc does not seem to be well tested in correctly parsing correct OpenMP code. There was a long-standing issue with pair style comb/omp (see issue #43 ) which was only addressed in CUDA 8.0.
So it remains to be seen whether this is an issue of the source code or an issue with nvcc.
The code should still compile with -fopenmp removed, i.e. the OpenMP flag set to "no".

**Comment by stanmoore1** [comment] 2017-06-19 17:51
I can get rid of the "master region" error by using:

<pre>
diff --git a/src/USER-OMP/reaxc_valence_angles_omp.cpp b/src/USER-OMP/reaxc_vale
index 869a325..f4608a1 100644
--- a/src/USER-OMP/reaxc_valence_angles_omp.cpp
+++ b/src/USER-OMP/reaxc_valence_angles_omp.cpp
@@ -255,7 +255,7 @@ void Valence_AnglesOMP( reax_system *system, control_params

     // Master thread uses angle counts to compute offsets
     // This can be threaded
-#pragma omp master
+    if (tid == 0)
     {
       int current_count = 0;
       int m = _my_offset[0];
</pre>

I have no idea how to get rid of the barrier error though.

**Comment by stanmoore1** [comment] 2017-06-19 18:17
@crtrott @nmhamster any ideas? Do we need to submit a bug report for nvcc?

**Comment by stanmoore1** [comment] 2017-06-19 18:25
I confirmed that this code compiles without warning or error using `gcc` only (i.e. not using `nvcc`).

**Comment by stanmoore1** [comment] 2017-06-19 18:35
Also sent an email to @jefflarkin. Hopefully someone can figure this out.

**Comment by akohlmey** [comment] 2017-06-19 19:18
@stanmoore1 i have an idea for how to address this. i noticed that for some reason, the pragmas in the problematic files are not (yet) protected by `#if defined(_OPENMP)`. i need to add those, since all USER-OMP code is supposed to be compiled with OpenMP turned off. no idea, how this could slip through the cracks. as soon as i have those ifdefs in place, i can also convert the ones that offend nvcc to `#if defined(_OPENMP) && !defined(__NVCC__)` and they should compile fine. since those files do not contain GPU code, it should have no effect to skip those pragmas. this should work for the pragmas with atomic operactions that certain nvcc versions choke on as well.

**Comment by stanmoore1** [comment] 2017-06-19 19:20
@akohlmey great, thanks!

**Comment by jefflarkin** [comment] 2017-06-19 20:22
Did this error crop up after a CUDA upgrade? In other words, is it an nvcc regression or something totally new?

**Comment by akohlmey** [comment] 2017-06-19 20:22
This is now resolved in #536

**Comment by stanmoore1** [comment] 2017-06-19 20:23
@jefflarkin no, it isn't an nvcc regression. We added new OpenMP code that triggered the error.

**Comment by akohlmey** [comment] 2017-06-19 20:27
@jefflarkin we've had observed something similar before with pair comb/omp.
due to how KOKKOS compilation is set up, *all* files are compiled with the host compiler and nvcc, and nvcc chokes on a few valid OpenMP pragma constructs. I have implemented a workaround now. So technically, it might be called an nvcc regression, but i would call it a low priority issue, since the KOKKOS nvcc_wrapper script is forcing nvcc to compile files that have no CUDA code in them and thus no output is expected.

**Comment by stanmoore1** [comment] 2017-06-19 20:29
Right, this is low priority now for us since there is no GPU code in the files that offend nvcc.

**Comment by stanmoore1** [comment] 2017-06-19 20:30
But it does look like a bug in nvcc since the code compiles under gcc just fine.

**Closed** 2017-06-20 13:44 UTC
Labels: kokkos_package, user_omp_package, user_reaxc_package

**Comment by jefflarkin** [comment] 2017-06-20 15:57
@stanmoore1 OK, if you file an nvcc bug, please send me the details and I'll add myself to the tracking.
