### ISSUE TITLE
[BUG] CUDA illegal memory access with NVIDIA HPC SDK OpenMPI 4.0.5

### ISSUE THREAD

**Issue by Qiyu8** [lammps/lammps#3434] opened 2022-09-08 02:55 UTC
**Summary**

Hello!
I was trying to running lammps(kokkos mode) in my ARM-based machine, Two A100 NVidia card are installed. However, I couldn't manage to make cuda_ipc transport to work as long as the P2P is enabled. The mpirun command is as follows:
```
mpirun --allow-run-as-root -np 2 -x UCX_TLS=sm,cuda_copy,cuda_ipc lmp_kokkos_cuda_mpi -k on g 2 -sf kk -pk kokkos cuda/aware on neigh full comm device binsize 2.8  -in in.lj.txt
```
The failed log is:

```
cudaDeviceSynchronize() error( cudaErrorIllegalAddress): an illegal memory access was encountered ../../lib/kokkos/core/src/Cuda/Kokkos_Cuda_Instance.cpp:144
```

but if I removed cuda_ipc or turn cuda/aware off, The program can run successfully while the performance is bad.

**LAMMPS Version and Platform**
LAMMPS (29 Sep 2021)
Linux 4.19.90-24.4.v2101.ky10.aarch64 GNU/Linux

**Expected Behavior**
The program `lmp_kokkos_cuda_mpi` successfully running and get a good performance.

**Actual Behavior**
```
cudaDeviceSynchronize() error( cudaErrorIllegalAddress): an illegal memory access was encountered ../../lib/kokkos/core/src/Cuda/Kokkos_Cuda_Instance.cpp:144
```

**Steps to Reproduce**
Running the command as below:
```
mpirun --allow-run-as-root -np 2 -x UCX_TLS=sm,cuda_copy,cuda_ipc lmp_kokkos_cuda_mpi -k on g 2 -sf kk -pk kokkos cuda/aware on neigh full comm device binsize 2.8  -in in.lj.txt
```

**Comment by stanmoore1** [comment] 2022-09-08 03:06
Hi @Qiyu8 thanks for the report. I think this is more an issue with the system/libraries on your machine (i.e. `cuda_ipc`) and not a bug in LAMMPS. Maybe @weinbe2 has an idea, otherwise I think you will need to contact authors of the libraries or someone at NVIDIA, since I have no way to reproduce or debug this.

**Comment by Qiyu8** [comment] 2022-09-08 08:23
@stanmoore1 Thanks for your advice, I will going to NVIDIA forum for help. @weinbe2 Any suggestions?

**Comment by weinbe2** [comment] 2022-09-08 21:44
Definitely reach out on the NVIDIA forum, since that will cast a wider net, but a few questions that will help in either case:
 * Which ARM CPU do you have?
 * Are these GPUs connected by NVLink, or are all comms through the host?
 * How are you defining "good" performance? More specifically, is this relative to 2xA100 on x86, or another quantification? The reason I ask is I believe the default problem size is relatively small, so it may scale relatively poorly independent of the communications. (This doesn't mean it's okay that the application is crashing --- it's not okay --- but functionality vs expected performance are separate conversations.)

**Comment by Qiyu8** [comment] 2022-09-09 02:25
@weinbe2 The ARM CPU is ARM-V8.2-based kunpeng, all of the GPUs are connected through PCIE, no NVLink are used, in this workload, all gpus should comms through P2P，not through the host, when referring to the performance,  I tested on another ARM machine with same configuration, The performance can reach 240 timesteps/s,  but in this case, The performance is 205 timesteps/s, which is not good enough.

**Comment by weinbe2** [comment] 2022-09-09 15:46
Thank you for more information. For what it's worth, I'm using "P2P" as a blanket term referring to inter-GPU comms, which will go through the PCIe bus when NVLink isn't available (and may technically include host staging, depending on the PCIe topology). For this reason the exact PCIe topology can matter, as well as the exact driver/CPU, etc.

One test to try is the CUDA toolkit p2pBandwidthLatency test, available here: https://github.com/NVIDIA/cuda-samples/tree/v11.3/Samples/p2pBandwidthLatencyTest (newer/older versions of CUDA will likely work well as well).

This will directly use the P2P APIs, as opposed to going through LAMMPS or OpenMPI, which can better help isolate the issue --- namely, if this benchmark fails (or passes!) it gets us one step further to understanding the issue.

I see your e-mail is in your profile --- if it's alright with you, I can reach out to you via e-mail directly, and we can circle back to this issue once it's been resolved. Is that okay?

**Comment by stanmoore1** [comment] 2022-09-09 15:49
Thanks @weinbe2! @Qiyu8, hopefully Evan or others at NVIDIA can help you figure this out. Closing this issue here since it isn't a bug in LAMMPS/Kokkos per se.

**Closed as completed by stanmoore1** 2022-09-09 15:49 UTC
