### ISSUE TITLE
[BUG] New FIRE implementation is not as robust as the previous one

### ISSUE THREAD

**Issue by Liozou** [lammps/lammps#1907] opened 2020-02-27 11:31 UTC
**Summary**

The new FIRE implementation loses atoms when the initial positions of the atoms are too close to each others, while the previous version of the implementation worked with the same input.

Observed errors:
```
ERROR: Lost atoms: original 2 current 0 (src/thermo.cpp:438)
```
or
```
ERROR on proc 0: Bond atoms 1726 1774 missing on proc 0 at step 1 (src/ntopo_bond_all.cpp:63)
```

I understand that atoms blowing out of the simulation box are indicative of bad dynamics because their initial configuration is wrong, not of a LAMMPS issue, but since the same input used to work a few weeks ago I thought it was worth opening an issue.

**LAMMPS Version and Platform**

LAMMPS (18 Feb 2020) (the patch version) crashes on Linux (x86_64-linux-gnu) Ubuntu 18.04.4 with CPU Intel(R) Core(TM) i7-8550U CPU @ 1.80GHz and GPU GeForce MX150/PCIe/SSE2, while LAMMPS (24 Jan 2020) (the patch version) works.

`git-bisect` points to commit 197ba62cd93f6fc9630bcb75a9324b5cab61a751 as the one which introduced this behaviour.

LAMMPS was tested both from the pre-built executable and from a custom build with the command
```
cmake -C ../cmake/presets/all_off.cmake -C ../cmake/presets/minimal.cmake -D BUILD_EXE=yes ../cmake
```

**Expected Behavior**

The minimization procedure should not crash.

**Actual Behavior**

One of the two errors given above.

The exact error depends on the specific parameters used in the configuration file. Below is a reproducer for the first one, with a minimal example.

**Steps to Reproduce**

Download the archive from [https://github.com/lammps/lammps/files/4261264/MWE.zip](https://github.com/lammps/lammps/files/4261264/MWE.zip) and extract it into a folder. `cd` into that folder and execute
```
lmp_daily -in minimalexample.in
```

Note that the input set given was reduced as much as possible, but the original issue stems from a much bigger simulation with 13527 atoms in `full` style, using `pair_style hybrid lj/cut/coul/long 8.5`. I can attach the original files if you prefer.

**Further Information, Files, and Links**

[MWE.zip](https://github.com/lammps/lammps/files/4261264/MWE.zip)

**Comment by akohlmey** [comment] 2020-02-27 11:52
Thanks for reporting. Can you confirm, that using fire/old is still working with this input?

**Comment by Liozou** [comment] 2020-02-27 11:54
Yes! fire/old is working just fine.

**Comment by akohlmey** [comment] 2020-02-27 12:14
> Yes! fire/old is working just fine.

Thanks. That is good to know and the reason why the old implementation was kept available. Minimizers are always some kind of compromise between speed and stability, so I am not certain, if there are tweaks and settings that can improve the default behavior without negatively affecting the performance. I have to defer this to the experts in that field, but at the very least, we could add some comments to the documentation mentioning that for high-potential energy starting geometries it might be advisable to first do some "pre-minimization" with a different, simpler algorithm. I think that is good advice for many cases, actually.

**Comment by jguenole** [comment] 2020-03-04 10:44
Thanks for reporting this!
There is a criteria that prevents atoms moving too far within a single minimization step. That should be actually identical in both old and new fire, and prevent losing atoms...
I will check in detail why its not behaving as intended.

**Comment by jguenole** [comment] 2020-03-06 13:47
I identified the problem.

The "bug" affects fire, but not in combination with the eulerexplicit integrator. This integrator is actually the only one used by fire/old, that explain what fire/old is not affected by this issue.

The parameter dmax should limit the maximum displacement of particles and prevent this error. This limitation is enforced by evaluating the displacement based on the current timestep and current velocities. However, when the velocities are zeroed (at the beginning of the minimization, for example), the test fail to predict large particles displacements, as the velocities are obviously zeroed.

The eulerexplicit integrator is not affect by the bug, as it moves the particles *before* computing their velocities. In the case described in this issue, the 1st step of the eulerexplicit integrator actually does not move any particle as it compute a displacement by using a velocity equal to 0.

The solution I propose is to, whenever the velocites have been zeroed, trigger a force-velocity evaluation that will be used for the sol purpose of checking the "maximum displacement criteria". I will submit a bug-fix pull request with more details.

**Closed** 2020-03-10 19:08 UTC
Labels: bug
