### ISSUE TITLE
In latest download pair_style eam/alloy misreads pair_coeff line if OPT package loaded ...

### ISSUE THREAD

**Issue by jfnash** [lammps/lammps#789] opened 2018-01-26 23:56 UTC
## Summary

A pair_style eam/alloy input deck that works with the 8.11.17 stable release
and that includes these lines:

pair_style      eam/alloy
pair_coeff      * * AlCu.eam.alloy Al Cu

fails with the latest 1.17.18 download.  This occurs only when the OPT package
is added to the base packages.

## Type of Issue

Input deck reading issue.

## Detailed Description (Enhancement Suggestion)

The input file read phase fails out with the following message:

...
pair_style      eam/alloy
pair_coeff      * * AlCu.eam.alloy Al Cu
ERROR: Incorrect args for pair coefficients (../pair_eam.cpp:364)

This does not occur if the OPT package is not loaded.  Note that
the failure occurs in ../pair_eam.cpp NOT ../pair_eam_alloy.cpp 
where is should given the pair style.  ../pair_eam.cpp:364 reports
an argument count issue for the pair_coeff line above because
it is expecting only 3 arguments:

  if (narg != 3) error->all(FLERR,"Incorrect args for pair coefficients");

BUT this is an eam-alloy pair_coeff line which requires more than 3
arguments.  

Note that the same check is correctly made in pair_eam_alloy.cpp here
at line 51:

  if (narg != 3 + atom->ntypes)
    error->all(FLERR,"Incorrect args for pair coefficients")

where it expects more than 3 arguments.

This looks like a case of LAMMPs failing to take note that the input deck
is requesting the eam/alloy pair style in the initial line when the OPT 
package is load and then misinterpreting the pair_coeff line.

This is not a problem in the 8.11.17 stable release.

## LAMMPS Version (Bug Report)

1.17.18 download

## Expected Behavior (Bug Report)

Correctly interpret the pair_coeff line when the OPT package is loaded.

## Actual Behavior (Bug Report)

Interprets the line as if the pair_style is NOT eam/alloy.

## Steps to Reproduce (Bug Report)

Any deck using LAMMPS provided eam/alloy potential file below
should also fail:

pair_style eam/alloy
pair_coeff * * ./potentials/NiAlH_jea.eam.alloy Ni Al Ni Ni

when the 1.17.18 download LAMMPS is built with the OPT package.

## Further Information, Files, and Links

Please send note when fixed to:  rwalsh@cray.com

**Comment by mkanski** [comment] 2018-01-27 09:57
I cannot reproduce the bug (log below) with LAMMPS compiled with MANYBODY and OPT packages only. 
Which other packages are installed? Which makefile did you use? Please provide a complete input script which causes the bug.

Log:
> LAMMPS (17 Jan 2018)
> region          universe sphere 0 0 0 30
> create_box      4 universe
> Created orthogonal box = (-30 -30 -30) to (30 30 30)
>   1 by 1 by 1 MPI processor grid
> pair_style      eam/alloy
> pair_coeff      * * NiAlH_jea.eam.alloy Ni Al Ni Ni
> Reading potential file NiAlH_jea.eam.alloy with DATE: 2007-11-30
> Total wall time: 0:00:00

**Comment by Pakketeretet2** [comment] 2018-01-27 15:10
Maybe a package purge might help?

**Comment by stanmoore1** [comment] 2018-01-29 22:44
@jfnash I can't reproduce this either using MANYBODY and OPT. Can you post your input deck as a text file here so we can be sure we are using the same options?

**Comment by akohlmey** [comment] 2018-02-01 09:43
@jfnash please provide some additional information to support your claim so that others can reproduce the issue, or else we'll have to close this issue as unconfirmed.

**Comment by akohlmey** [comment] 2018-02-01 10:41
@jfnash one more observation. The code in eam/alloy/opt depends on multiple inheritance working correctly. So there is a good chance, that if something is broken, that it may be broken in the compiler and not in the LAMMPS code.

**Comment by jfnash** [comment] 2018-02-01 19:16
All

[lammps_bug.txt](https://github.com/lammps/lammps/files/1686834/lammps_bug.txt)

I am attaching a linux "script" screen capture of every step of a session
on a local Cray SKX system in which I build the latest LAMMPs download with the
latest Intel compiler 18.0.1.163, run my problem input case, and reproduce
the failure.

I attempt to reveal all the details of my build methodology along the way by 
cat-ing and less-ing files of interest, including my 'makefile' build options.  I
show the job running and its quick final failure and output in the log.lammps
file.

This >>should<< show you all that you need to reproduce, but I can provide
more upon request.  Let me know ... :-) ... 

Your help with this is appreciated.  We have a benchmark that needs to make
use of the OPT package and our preference is the make use of the latest download.

Sincerely,

rbw

**Comment by akohlmey** [comment] 2018-02-02 05:32
I've tried with multiple compilers and on multiple machines, and I *still*
cannot reproduce your issue. There have been *no* changes to any of the eam
pair styles (neither in MANYBODY nor in OPT) since the last stable release.
The code in the OPT package is known top be somewhat more aggressive in
expecting correct compiler behavior, so it is logical to assume, the issue
is cause by a bug or unexpected behavior of the particular compiler version
you are using.

We need better proof than your executable not functioning, to spend more
time on this.

Axel.



--
Dr. Axel Kohlmeyer  akohlmey@gmail.com  http://goo.gl/1wk0
College of Science & Technology, Temple University, Philadelphia PA, USA
International Centre for Theoretical Physics, Trieste. Italy.

**Comment by akohlmey** [comment] 2018-02-02 10:29
FYI, my colleague has just installed the intel 18.0.1.163 compiler on our local HPC cluster (running CentOS 7.4, x86-64 with Intel Xeon E5-2650 v4 CPUs).

i've compiled LAMMPS with the intel_cpu_openmpi makefile and the resulting executable was working as expected.

Then i've created a custom makefile based on intel_cpu_openmpi with your choice of compiler/linker flags. Due to the difference in CPU architecture, i've had to replace your -xCORE-AVX512 option with -xHOST. Again, I can use eam/alloy/opt without a problem.

we cannot fix a problem, that we cannot confirm.

**Closed by akohlmey** 2018-02-02 10:29 UTC
Labels: manybody_package, opt_package, unconfirmed
