### ISSUE TITLE
[BUG] KC type potentials - parallelization issues

### ISSUE THREAD

**Issue by nleconte** [lammps/lammps#1429] opened 2019-04-17 02:03 UTC
**Summary**

I've been looking at output based on calculations using the  Kolgomorov Cresti type potentials (full and ILP) on a bilayer system.

Both give the strange behavior in attached files at the end of this issue.

I am using 40 mpi processes, yielding a 5 by 4 by 2 MPI processor grid.

Incidentally, that's what we see in this grid, a 5 by 4 grid with mismatches at the interfaces of the grid.

I redid the calculation with a 10 by 2 by 2 grid and the grid of mismatches changes accordingly.

FYI, the calculation works well from a numerical point of view with the simplified KC potential (all normals along the z-axis), no such spurious grid is observed. From a physical point of view, the simplification might not be valid, but that's out of the scope of present query.

**LAMMPS Version and Platform**

LAMMPS (12 Dec 2018)

**Expected Behavior**

I would expect the same behavior as what one would get without parallelization.

**Actual Behavior**

A grid appears when plotting the colormap of interlayer distances, z components of the separate layers, etc.

**Steps to Reproduce**

A folder with necessary files can be downloaded here.
https://www.dropbox.com/s/n3gfkyyb0wn8v7o/lammpsIssue.tar?dl=0

The jupyter notebook reads in two files that are the positions of the first (visualizeInit.xyz) and last (visualize.xyz) of the last time step copy pasted from the dump.minimization file. One can also run the extractXYZ.py once these files have been created to get some of the other input files for the jupyter notebook. I have already provided them for convenience.

**Further Information, Files, and Links**

10x2x2 grid ILP potential
<img width="1314" alt="Screenshot 2019-04-17 10 55 15" src="https://user-images.githubusercontent.com/11783268/56255284-54f85a80-60ff-11e9-819c-ef3cae242d03.png">

5x4x2 grid ILP potential:
![ILP](https://user-images.githubusercontent.com/11783268/56255328-75c0b000-60ff-11e9-9fbe-148eb62c0903.jpg)

5x4x2 grid KC Full potential:
![KCFull](https://user-images.githubusercontent.com/11783268/56255331-78230a00-60ff-11e9-8065-f1534f72646f.jpg)

**Comment by nleconte** [comment] 2019-04-18 03:14
Actually, I'm wondering if the problem also exists using only one MPI process. In the following figure, it seems that the edges are affected too (hinting towards some problem in the periodic boundary conditions when calculating the normals)?

<img width="1303" alt="Screenshot 2019-04-18 12 05 04" src="https://user-images.githubusercontent.com/11783268/56334258-91e15180-61d2-11e9-892b-204879edef70.png">

Energetically, with and without MPI parallelization, the energies are pretty similar:

1x1x1 MPI:
Energy initial, next-to-last, final =
-112166.989186     -112193.194217      -112193.19443

5x4x2 MPI:
Energy initial, next-to-last, final =
-112166.989186     -112193.131607     -112193.131827

For my purposes which involve extracting the displacements of the atoms for further processing, I ideally need to preserve the symmetries, so it's critical to get accurate values I think. I can probably get by by tripling the simulation cell and focusing on the central one only, but it's not the most convenient thing to do, especially for the larger systems.

**Comment by mkanski** [comment] 2019-04-24 10:52
The Jupyter notebook is empty for me. However, I have few question after checking other attached files:
1. Does the problem appear with orthogonal simulation box?
1. Are the grid visible if only AIREBO is used?
1. Your system is anisotropic, but you want to relax the box isotropically. Why? Why is the z-dimension periodic anyway? 

Try running the minimization with `neigh_modify every 1 delay 0 check no`.

**Comment by sgsaenger** [comment] 2019-05-03 15:44
While i cannot comment on the versions of the KC potential shipped with lammps,
you could try the implementation available on our fork:
https://github.com/sgsaenger/lammps/tree/rdip

ATM, it is used like the `kolmogorov/crespi/z` by assigning a seperate atom-type to the different layers,
but it implements the full potential:
```
pair_style rdip 15.0
pair_coeff * * rdip C.rdip C C
```
We've used it extensively over the years, so far no parallelization issues arose and we couldn't reproduce the issue at hand.
In our quick and dirty benchmarks we've also been quite a bit faster, 1431 hours/ns (RDIP+AIREBO) vs 2292 hours/ns (KC/full+AIREBO) for 1728000 atoms on an E5-2620v4.

**Comment by akohlmey** [comment] 2019-05-08 00:07
@nleconte please try to validate your observations with the latest development patch version of LAMMPS. I don't think any of the LAMMPS core developers has currently the time to look into this, so your best chances are to look up the email addresses of the contributing authors in the source code (or README or manual) and contact them directly.

**Comment by nleconte** [comment] 2019-05-08 00:18
Hi Axel, Sebastian and Mkanski,

Thanks for responses. I have just returned from holidays so will be follow
up on your suggestions in the coming days/hours.
I am also in touch with Ouyang (the contributing author) who has been
rather responsive, so I'm confident I'll be able to resolve the issue soon.
I'll act accordingly on Github.

Regards,
Nicolas

**Comment by nleconte** [comment] 2019-05-10 02:17
> The Jupyter notebook is empty for me. However, I have few question after checking other attached files:
> 
> 1. Does the problem appear with orthogonal simulation box?
> 2. Are the grid visible if only AIREBO is used?
> 3. Your system is anisotropic, but you want to relax the box isotropically. Why? Why is the z-dimension periodic anyway?
> 
> Try running the minimization with `neigh_modify every 1 delay 0 check no`.

Sorry for late response, I was on holidays.

1. Can't comment on this as the bilayer graphene system I'm simulation requires a triclinic cell to build a commensurate supercell between the two layers.

2. Nothing is visible when only using AIREBO. Indeed, no interaction between layers keeps them perfectly flat.
3. Indeed, that was an error in my input file. For simplicity, I have redone them removing the cell relaxation. Yet, it still leads to the appearance of the spurious grid, even when using @oywg11's attached input file.

My result (ILP):

<img width="1300" alt="Screenshot 2019-05-10 11 11 34" src="https://user-images.githubusercontent.com/11783268/57497854-630f5480-7314-11e9-97a2-9719be9caee4.png">

His result:

<img width="484" alt="Screenshot 2019-05-10 11 07 45" src="https://user-images.githubusercontent.com/11783268/57497747-e54b4900-7313-11e9-9c75-7c562506f39e.png">

@oywg11 did not reproduce my erratic behavior (as illustrated in the figure above he provided me with, using two cores only), so the error must be on my side (and not in his code) and I will continue trying to locate the problem here.

Useful files: added .txt extension to be able to attach it here directly
[lammps.in.txt](https://github.com/lammps/lammps/files/3164622/lammps.in.txt)
[CH.rebo.txt](https://github.com/lammps/lammps/files/3164623/CH.rebo.txt)
[BNCH.ILP.txt](https://github.com/lammps/lammps/files/3164624/BNCH.ILP.txt)
[tBLG-2deg.data.txt](https://github.com/lammps/lammps/files/3164630/tBLG-2deg.data.txt)

**Comment by nleconte** [comment] 2019-05-10 02:23
> While i cannot comment on the versions of the KC potential shipped with lammps,
> you could try the implementation available on our fork:
> https://github.com/sgsaenger/lammps/tree/rdip
> 
> ATM, it is used like the `kolmogorov/crespi/z` by assigning a seperate atom-type to the different layers,
> but it implements the full potential:
> 
> ```
> pair_style rdip 15.0
> pair_coeff * * rdip C.rdip C C
> ```
> 
> We've used it extensively over the years, so far no parallelization issues arose and we couldn't reproduce the issue at hand.
> In our quick and dirty benchmarks we've also been quite a bit faster, 1431 hours/ns (RDIP+AIREBO) vs 2292 hours/ns (KC/full+AIREBO) for 1728000 atoms on an E5-2620v4.

When you say _full potential_, you mean calculating the normals (rather than aligning them with _z_)?

**Comment by nleconte** [comment] 2019-05-10 04:44
> > While i cannot comment on the versions of the KC potential shipped with lammps,
> > you could try the implementation available on our fork:
> > https://github.com/sgsaenger/lammps/tree/rdip
> > ATM, it is used like the `kolmogorov/crespi/z` by assigning a seperate atom-type to the different layers,
> > but it implements the full potential:
> > ```
> > pair_style rdip 15.0
> > pair_coeff * * rdip C.rdip C C
> > ```
> > 
> > 
> > We've used it extensively over the years, so far no parallelization issues arose and we couldn't reproduce the issue at hand.
> > In our quick and dirty benchmarks we've also been quite a bit faster, 1431 hours/ns (RDIP+AIREBO) vs 2292 hours/ns (KC/full+AIREBO) for 1728000 atoms on an E5-2620v4.
> 
> When you say _full potential_, you mean calculating the normals (rather than aligning them with _z_)?

For the record, I also just tried using your drip potential. I don't get any spurious grid, using the same input file (replacing the potential call of course), your personal branch and using the same post-processing visualization script. 

ASSUMING that no z-axis simplification for the normals is made in @sgsaenger's code, it would _seem_ that the difference lies in the way the normals are calculated (I looked at both source codes, @sgsaenger does not differentiate between atoms on the border with only two neighbors, while @oywg11 seems to do so). Yet, it is surprising that I'm the only one who gets the error using ilp and KC full. 

I'll try to continue figuring out where my error lies, but I'm feel free to comment.

**Comment by nleconte** [comment] 2019-05-10 04:51
> > While i cannot comment on the versions of the KC potential shipped with lammps,
> > you could try the implementation available on our fork:
> > https://github.com/sgsaenger/lammps/tree/rdip
> > ATM, it is used like the `kolmogorov/crespi/z` by assigning a seperate atom-type to the different layers,
> > but it implements the full potential:
> > ```
> > pair_style rdip 15.0
> > pair_coeff * * rdip C.rdip C C
> > ```
> > 
> > 
> > We've used it extensively over the years, so far no parallelization issues arose and we couldn't reproduce the issue at hand.
> > In our quick and dirty benchmarks we've also been quite a bit faster, 1431 hours/ns (RDIP+AIREBO) vs 2292 hours/ns (KC/full+AIREBO) for 1728000 atoms on an E5-2620v4.
> 
> When you say _full potential_, you mean calculating the normals (rather than aligning them with _z_)?

And side question: to what data did you fit your drip data? Is it similar to the Drip potential in recent PR #1453? Or was it fit to a different DFT/vdW scheme?

Until I figure out above issue (ILP and KC/full), I'll probably proceed with your potential. The KC/z works without spurious grid, but adds long-range corrugation (I'm not talking about the AA-AB corrugation) as it cannot differentiate between corrugation level. I presume your potential keeps the structures flat? It seems to be the case for my first test at 2 degree twist angle.

**Comment by sgsaenger** [comment] 2019-05-10 09:42
> When you say _full potential_, you mean calculating the normals (rather than aligning them with _z_)?

Yes, everything is calculated as defined in the original KC paper.

> And side question: to what data did you fit your drip data? Is it similar to the Drip potential in recent PR #1453? Or was it fit to a different DFT/vdW scheme?

As i said, our implementation is quite old, we just didn't get around submitting it in time before another implementation was merged to LAMMPS...
Therefore, the potential file included in our branch uses the original KC parameters, it has nothing to do with Tadmor et al.'s DRIP.

> (I looked at both source codes, @sgsaenger does not differentiate between atoms on the border with only two neighbors, while @oywg11 seems to do so)

Our assumptions for edges was for them to be "saturated", e.g. with hydrogen atoms declared as `EDGE` in the `pair_coeff` call. This way the normal calculation is stable and we don't get any implicit deviations from the initial formulation. But for a periodic bilayer system, this shouln't be a problem anyways, should it?

> I presume your potential keeps the structures flat?

I'm not quite sure what you mean?
We use it mainly to investigate deviations from flat structures, see here: https://www.nature.com/articles/nature12780
So if there's no buckling where you would expect it, it's at leas not intended ;)

**Comment by nleconte** [comment] 2019-05-14 06:45
> > When you say _full potential_, you mean calculating the normals (rather than aligning them with _z_)?
> 
> Yes, everything is calculated as defined in the original KC paper.
> 
> > And side question: to what data did you fit your drip data? Is it similar to the Drip potential in recent PR #1453? Or was it fit to a different DFT/vdW scheme?
> 
> As i said, our implementation is quite old, we just didn't get around submitting it in time before another implementation was merged to LAMMPS...
> Therefore, the potential file included in our branch uses the original KC parameters, it has nothing to do with Tadmor et al.'s DRIP.
> 
> > (I looked at both source codes, @sgsaenger does not differentiate between atoms on the border with only two neighbors, while @oywg11 seems to do so)
> 
> Our assumptions for edges was for them to be "saturated", e.g. with hydrogen atoms declared as `EDGE` in the `pair_coeff` call. This way the normal calculation is stable and we don't get any implicit deviations from the initial formulation. But for a periodic bilayer system, this shouln't be a problem anyways, should it?
> 
> > I presume your potential keeps the structures flat?
> 
> I'm not quite sure what you mean?
> We use it mainly to investigate deviations from flat structures, see here: https://www.nature.com/articles/nature12780
> So if there's no buckling where you would expect it, it's at least not intended ;)

Ok, got it about the _full_ terminology.

As for the edges, your potential properly seems to take into account the periodic images to calculate the normals. In the KC/full and ILP potential, it just considers the atoms at the boundaries as being actual edge atoms (with less number of neighbors) when calculating the normals. I think this explains why I get the spurious grid when using it for periodic systems.

(I should have used the _edge_ terminology before as all I want to refer to were the atoms at the boundaries of the periodic system)

**Comment by oywg11** [comment] 2019-05-14 07:08
> > > When you say _full potential_, you mean calculating the normals (rather than aligning them with _z_)?
> > 
> > 
> > Yes, everything is calculated as defined in the original KC paper.
> > > And side question: to what data did you fit your drip data? Is it similar to the Drip potential in recent PR #1453? Or was it fit to a different DFT/vdW scheme?
> > 
> > 
> > As i said, our implementation is quite old, we just didn't get around submitting it in time before another implementation was merged to LAMMPS...
> > Therefore, the potential file included in our branch uses the original KC parameters, it has nothing to do with Tadmor et al.'s DRIP.
> > > (I looked at both source codes, @sgsaenger does not differentiate between atoms on the border with only two neighbors, while @oywg11 seems to do so)
> > 
> > 
> > Our assumptions for edges was for them to be "saturated", e.g. with hydrogen atoms declared as `EDGE` in the `pair_coeff` call. This way the normal calculation is stable and we don't get any implicit deviations from the initial formulation. But for a periodic bilayer system, this shouln't be a problem anyways, should it?
> > > I presume your potential keeps the structures flat?
> > 
> > 
> > I'm not quite sure what you mean?
> > We use it mainly to investigate deviations from flat structures, see here: https://www.nature.com/articles/nature12780
> > So if there's no buckling where you would expect it, it's at least not intended ;)
> 
> Ok, got it about the _full_ terminology.
> 
> As for the edges, your potential properly seems to take into account the periodic images to calculate the normals. In the KC/full and ILP potential, it just considers the atoms at the boundaries as being actual edge atoms (with less number of neighbors) when calculating the normals. I think this explains why I get the spurious grid when using it for periodic systems.
> 
> (I should have used the _edge_ terminology before as all I want to refer to were the atoms at the boundaries of the periodic system)

@nleconte It seems that you misunderstand the "edge terminology". In the KC/full and ILP, the calculation of the normal is split into three cases according to the number of neighbours (cont=1, 2, and 3). The less number of neighbours (1,2) is designed for open boundary conditions, in which graphene or hBN have real edges. In your simulation, PBC condition is used, so the number of neighbours for each carbon atom should be always 3 (unless the PBC is not exact),  thus when you use KC/full and ILP, the third method is used (i.e., cont = 3) to calculate the normals. 
To be honest, I didn't observe the bug you reported here. We still need to think about the reason for it.

**Comment by nleconte** [comment] 2019-05-14 07:36
Thanks for clarifying how your code works and sorry for the confusing terminology I used.

Last time you gave me your output file (in the email exchange) from which I rebuilt the input file. It still gave the buggy looking behavior. Could you send me the input file _as is_, so I can run it with different number of processors and compare line by line with mine. I already have your position file. And could you share with me the post-processing script you used to create those maps. You use it with a pretty sparse colormap, so I want to see what happens if I run my output through it (I'm using a more continuous map definition).

The error is most probably on my side, but I still can't figure it out. Sorry for all this trouble.

The other implementation works well for me.

**Comment by oywg11** [comment] 2019-05-14 08:08
@nleconte Attached please find the input file. I didn't write a script for post-processing, I just typed several commands in MATLAB to plot the figures. The command I used is "contourf", you can find its syntax here: https://www.mathworks.com/help/matlab/ref/contourf.html.

[in.gr.txt](https://github.com/lammps/lammps/files/3176492/in.gr.txt)

**Comment by sgsaenger** [comment] 2019-05-14 09:38
@oywg11 
FIY, when we compared your implementation with ours, there were problems in creating the neighbor lists when we used a classical forcefield:
```ERROR: Could not build neighbor list to calculate normals, please check your configuration (../pair_kolmogorov_crespi_full.cpp:731)```
With AIREBO, both RDIP and KC/FULL copy the neighbor list:
```
  (1) pair rebo, perpetual
      attributes: full, newton on, ghost, omp
      pair build: full/bin/ghost/omp
      stencil: full/ghost/bin/3d
      bin: standard
  (2) pair kolmogorov/crespi/full, perpetual, copy from (1)
      attributes: full, newton on, ghost, omp
      pair build: copy
      stencil: none
      bin: none
```
```
  (1) pair rebo, perpetual
      attributes: full, newton on, ghost, omp
      pair build: full/bin/ghost/omp
      stencil: full/ghost/bin/3d    
      bin: standard
  (2) pair rdip, perpetual, copy from (1)
      attributes: full, newton on, omp
      pair build: copy
      stencil: none   
      bin: none    
```
If we use lj/charmm/coul/charmm, rdip works:
```
  (1) pair lj/charmm/coul/charmm, perpetual, half/full from (2)
      attributes: half, newton on, omp
      pair build: halffull/newton/omp
      stencil: none
      bin: none
  (2) pair rdip, perpetual
      attributes: full, newton on, omp
      pair build: full/bin/omp
      stencil: full/bin/3d
      bin: standard
```
but kc/full fails with the error noted above, in the only calculation that uses two discrete lists:
```
  (1) pair lj/charmm/coul/charmm, perpetual
      attributes: half, newton on, omp
      pair build: half/bin/newton/omp
      stencil: half/bin/3d/newton
      bin: standard
  (2) pair kolmogorov/crespi/full, perpetual
      attributes: full, newton on, ghost, omp
      pair build: full/bin/ghost/omp
      stencil: full/ghost/bin/3d
      bin: standard
```
Maybe there's something going wrong in how you request/utilize the neighbor lists?

**Comment by oywg11** [comment] 2019-05-14 10:05
> @oywg11
> FYI, when we compared your implementation with ours, there were problems in creating the neighbor lists when we used a classical forcefield:
> `ERROR: Could not build neighbor list to calculate normals, please check your configuration (../pair_kolmogorov_crespi_full.cpp:731)`
> With AIREBO, both RDIP and KC/FULL copy the neighbor list:
> 
> ```
>   (1) pair rebo, perpetual
>       attributes: full, newton on, ghost, omp
>       pair build: full/bin/ghost/omp
>       stencil: full/ghost/bin/3d
>       bin: standard
>   (2) pair kolmogorov/crespi/full, perpetual, copy from (1)
>       attributes: full, newton on, ghost, omp
>       pair build: copy
>       stencil: none
>       bin: none
> ```
> 
> ```
>   (1) pair rebo, perpetual
>       attributes: full, newton on, ghost, omp
>       pair build: full/bin/ghost/omp
>       stencil: full/ghost/bin/3d    
>       bin: standard
>   (2) pair rdip, perpetual, copy from (1)
>       attributes: full, newton on, omp
>       pair build: copy
>       stencil: none   
>       bin: none    
> ```
> 
> If we use lj/charmm/coul/charmm, rdip works:
> 
> ```
>   (1) pair lj/charmm/coul/charmm, perpetual, half/full from (2)
>       attributes: half, newton on, omp
>       pair build: halffull/newton/omp
>       stencil: none
>       bin: none
>   (2) pair rdip, perpetual
>       attributes: full, newton on, omp
>       pair build: full/bin/omp
>       stencil: full/bin/3d
>       bin: standard
> ```
> 
> but kc/full fails with the error noted above, in the only calculation that uses two discrete lists:
> 
> ```
>   (1) pair lj/charmm/coul/charmm, perpetual
>       attributes: half, newton on, omp
>       pair build: half/bin/newton/omp
>       stencil: half/bin/3d/newton
>       bin: standard
>   (2) pair kolmogorov/crespi/full, perpetual
>       attributes: full, newton on, ghost, omp
>       pair build: full/bin/ghost/omp
>       stencil: full/ghost/bin/3d
>       bin: standard
> ```
> 
> Maybe there's something going wrong in how you request/utilize the neighbor lists?

Which version of LAMMPS did you use? I updated the codes recently. 
Can you share with me your input file and data file so I can also check it?

**Comment by nleconte** [comment] 2019-05-28 01:47
Using @oywg11's input, 2 MPI processes (1x2 grid):

<img width="399" alt="Screenshot 2019-05-28 10 39 41" src="https://user-images.githubusercontent.com/11783268/58444863-05ad3d00-8135-11e9-98ff-32c10f0681bd.png">
<img width="454" alt="Screenshot 2019-05-28 10 39 56" src="https://user-images.githubusercontent.com/11783268/58444864-080f9700-8135-11e9-9345-78f1174f3bc2.png">


Same input, 20 MPI process (5x4 grid):

<img width="412" alt="Screenshot 2019-05-28 10 39 32" src="https://user-images.githubusercontent.com/11783268/58444859-fe862f00-8134-11e9-9723-c0fc6a2f1670.png">
<img width="446" alt="Screenshot 2019-05-28 10 40 04" src="https://user-images.githubusercontent.com/11783268/58444862-02b24c80-8135-11e9-907f-5c49a911543b.png">

When using contour, one hides the faulty behavior using only 2 MPI processes. In Python, when using imshow, one does not. The faulty behavior shows in any case for the 20 MPI processes.


```
name = "forHeight2.0.xyz"

data = np.genfromtxt(name)

layerIndex = data[:,0]
xdata = data[:,1]
ydata = data[:,2]
zdata = data[:,3]


xdataTop = xdata[layerIndex==1.0]
ydataTop = ydata[layerIndex==1.0]
zdataTop = zdata[layerIndex==1.0]

xdataBottom = xdata[layerIndex==2.0]
ydataBottom = ydata[layerIndex==2.0]
zdataBottom = zdata[layerIndex==2.0]

x=np.arange(min(xdataTop),max(xdataTop))
y=np.arange(min(ydataTop),max(ydataTop))

zdataTopInt=griddata((xdataTop,ydataTop),zdataTop,(x[None,:], y[:,None]), method='cubic')

im = plt.imshow(zdataTopInt,origin="lower",aspect="auto")

plt.figure()
X, Y = np.meshgrid(x, y)
zdataTopInt=griddata((xdataTop,ydataTop),zdataTop,(x[None,:], y[:,None]), method='cubic')
plt.contourf(X,Y,zdataTopInt)

plt.figure()
X, Y = np.meshgrid(xdataTop, ydataTop)
zdataTopInt=griddata((xdataTop,ydataTop),zdataTop,(xdataTop[None,:], ydataTop[:,None]), method='cubic')
plt.contourf(X,Y,zdataTopInt)

```

Not sure what is happening, so I can't use the ILP or KC/full potentials for now.

**Comment by oywg11** [comment] 2019-08-01 14:17
Hi all,
Thanks for discussing and debugging this bug. After a bunch of tests, I can finally find the reason of this bug and fixed it. Nicolas@nleconte did a quick test with the modified potential and it solved his problem. I did more tests on the new version of potential and I think now the bug is fixed. More details can be found in #1606. Please feel free to do some additional tests if you have time, any inputs will be grateful. Thanks!

**Closed** 2019-08-01 19:01 UTC
Labels: bug
