### ISSUE TITLE
running kokkos with gpu

### ISSUE THREAD

**Issue by busce004** [lammps/lammps#3751] opened 2023-04-25 01:45 UTC
I've been working on this for a couple of weeks. Trying to run lammps with gpu and kokkos
OS linux mint 21.1, AMD 7900, Lammps 8Feb 23, Kokkos-4, 
 NVIDIA-SMI 525.85.12    Driver Version: 525.85.12    CUDA Version: 12.0 
Build cuda_11.7.r11.7/compiler.31294372_0

Background:
I have installed Kokkos with cmake using
cmake  ../ -D Kokkos_ENABLE_CUDA=ON  -DKokkos_ARCH_AMPERE86=ON -D Kokkos_ENABLE_CUDA_LAMBDA=ON -D Kokkos_ENABLE_OPENMP=yes  ../cmake

=============================
with this installation I can compile lammps to run with kokkos with no gpu  using
 cmake -C ../cmake/presets/most.cmake -D Kokkos_ENABLE_OPENMP=yes  -D PKG_KOKKOS=yes  -D Kokkos_ENABLE_THREADS=ON ../cmake 

and for example 
mpirun -np 1 lmp-k -k on t 16 -sf kk -in in.rhodo

==============================
Similarly  without the invoking kokkos I can use cmake to run with a gpu
cmake -C ../cmake/presets/most.cmake  -D PKG_GPU=on -D GPU_API=cuda  -DCMAKE_CUDA_ARCHITECTURES=86    ../cmake 

with  for example  mpirun -np 1 lmp -sf gpu -pk gpu 1 -in in.lj   works as expected
==============================

ISSUE:
However If try to complile lammps and kokkos to use with a GPU RTX 3090 ( using presets = most or basic )
 cmake -C ../cmake/presets/most.cmake  -D PKG_GPU=on  -D Kokkos_ENABLE_CUDA=yes -D PKG_KOKKOS=yes ../cmake 

or with the cmake command 
cmake -C ../cmake/presets/most.cmake  -D PKG_GPU=on -D GPU_API=cuda -DCMAKE_CUDA_ARCHITECTURES=86  -D PKG_KOKKOS=yes -D Kokkos_ENABLE_CUDA=ON -D Kokkos_ENABLE_THREADS=ON ../cmake 

complilation proceeds ( with multiple warnings ) then after 100% is reached  and the following error appears:

.....
.....
tmp/ccDhsuWv.s:4323155: Error: symbol `fatbinData' is already defined  ( many lines ) 
/tmp/ccDhsuWv.s:4327364: Error: symbol `fatbinData' is already defined
lto-wrapper: fatal error: /usr/bin/c++ returned 1 exit status
compilation terminated.
[lammps build.txt](https://github.com/lammps/lammps/files/11315532/lammps.build.txt)

/usr/bin/ld: error: lto-wrapper failed
collect2: error: ld returned 1 exit status
make[2]: *** [CMakeFiles/lmp.dir/build.make:117: lmp] Error 1
make[1]: *** [CMakeFiles/Makefile2:391: CMakeFiles/lmp.dir/all] Error 2
make: *** [Makefile:136: all] Error 2

I can find little information on fatbin Data is already defined.   

Cuda was installed via the deb local from Nvidia  and I gather that the lto wrapper is critcial

The full output of cmake  for lammps is attached.

[lammps build.txt](https://github.com/lammps/lammps/files/11315596/lammps.build.txt)

In essence any combination of package inclusion ends in failure I I try to invoke a gpu and Kokkos

any tips would be appreciated.

**Comment by stanmoore1** [comment] 2023-04-25 15:49
Hi I have not encountered this error before but somehow link time optimization (LTO) is getting enabled. According to https://forums.developer.nvidia.com/t/link-time-optimization-with-cuda-on-linux-flto/55530/2, can you try using `-Xcompiler -fno-lto` and see if that fixes the issue?

**Comment by stanmoore1** [comment] 2023-04-25 15:59
Alternatively can you try adding the `-dlto` flag to enable LTO on device, see https://developer.nvidia.com/blog/improving-gpu-app-performance-with-cuda-11-2-device-lto/ and https://bugs.gentoo.org/811162.

**Comment by stanmoore1** [comment] 2023-04-25 17:54
Oh also a suggestion from @weinbe2: try using Kokkos `nvcc_wrapper` as the compiler, something like this:
`-D CMAKE_CXX_COMPILER=$(pwd)/../lib/kokkos/bin/nvcc_wrapper`

**Comment by stanmoore1** [comment] 2023-04-25 17:55
If you aren't using `nvcc_wrapper` then that is mostly likely the cause of the issue.

**Comment by stanmoore1** [comment] 2023-04-26 20:34
@busce004 I'm pretty sure that using `nvcc_wrapper` will fix your issue. In any case, since this is not a bug in LAMMPS but rather a build question I will close this issue on GitHub. Feel free to continue the discussion on MatSci: https://matsci.org/c/lammps/40 if you need more help. Thanks

**Closed as completed by stanmoore1** 2023-04-26 20:34 UTC
Labels: invalid, kokkos_package, cmake

**Comment by busce004** [comment] 2023-04-27 01:57
Thank you very much.. I'll follow up on your suggestions.
pb

**Comment by busce004** [comment] 2023-04-27 23:41
just an update:  using 

cmake  ../ -D Kokkos_ARCH_GPU=yes -D Kokkos_ARCH_AMPERE86=ON -D Kokkos_ENABLE_CUDA=yes -D Kokkos_ENABLE_OPENMP=yes -D CMAKE_CXX_COMPILER=/home/pb/Desktop/kokkos-4/bin/nvcc_wrapper  ../cmake

did not correct the error.  I'll post on MatSci.  thanks for the tips....pb

**Comment by stanmoore1** [comment] 2023-04-27 23:43
@busce004 thanks for the update, see you on MatSci.
