### ISSUE TITLE
Multiple restart writes same timstep using USER-INTEL sometimes creates invalid restart file

### ISSUE THREAD

**Issue by andeplane** [lammps/lammps#859] opened 2018-03-28 18:53 UTC
## Summary
This is an early bugreport since I haven't found a way to always reproduce the problem. I'll write what we have observed so that you might understand what's going on based on the symptoms.

Summary: **Running the attached script with 128 MPI processes using USER-INTEL sometimes creates one invalid restart files if two restart files are written the same timestep.**

One of my students ran the attached script that basically runs 10000 timesteps which ends up writing two restart files this way:

```
restart 10000 type1.restart
run 10000
write_restart type2.restart
```

Here both restart files are written the same timestep. We initially found a problem with the last restart file. LAMMPS ended up being in an infinite loop while reading the file in `read_restart.cpp`, but the first one works. 

## Type of Issue

Bug report.

## LAMMPS Version (Bug Report)

LAMMPS is compiled with following version of Intel compiler `icpc (ICC) 17.0.4 20170411`.
Both last stable (aug 17) and latest (march 18).

## Expected Behavior (Bug Report)

Both restart files should be identical (md5sum are identical if USER-INTEL is not used) and should work.

## Actual Behavior (Bug Report)

Only the first restart file is valid. The latter might make LAMMPS be in an infinite loop due to `buf[m]=0` in https://github.com/lammps/lammps/blob/master/src/read_restart.cpp#L271.

## Steps to Reproduce (Bug Report)
Haven't found a way that always reproduces the problem, but the attached script, if run on 128 processors is sometimes problematic on our cluster. We have observed that removing the `processors` command, the error goes away which makes me think a memory problem.

## Further Information, Files, and Links

I ran the attached input script multiple times with the following md5sum of the restart files:
```
MD5 (type1_1.restart.10000) = 870babf83114f14cfde82849606eb202
MD5 (type1_2.restart.10000) = 870babf83114f14cfde82849606eb202
MD5 (type1_3.restart.10000) = 870babf83114f14cfde82849606eb202
MD5 (type1_4.restart.10000) = 870babf83114f14cfde82849606eb202
MD5 (type1_5.restart.10000) = 870babf83114f14cfde82849606eb202
MD5 (type2_1.restart) = d1fc9562103a02fdb98aa0e8f9667858
MD5 (type2_2.restart) = 2d82e4f3d407eb920bc42669050c387d
MD5 (type2_3.restart) = 2b18c5cbdd9273a7dd90360139d49173
MD5 (type2_4.restart) = b4ed09086ec5faa501a65acd12f413d1
MD5 (type2_5.restart) = 7880a53211c089e63e75018a29962c99
```

This seems to definitely be a memory bug since it is not deterministic and random changes may "fix" the problem. 

[restart_bug.zip](https://github.com/lammps/lammps/files/1856610/restart_bug.zip)

**Comment by sjplimp** [comment] 2018-05-11 15:22
@andeplane Are you saying this issue never happens if not using USER-INTEL?
And is the only use of USER-INTEL for a pair style?

**Comment by andeplane** [comment] 2018-05-11 15:52
So far it happened only with USER-INTEL, using `lj/cut/coul/long/intel`, `pppm/intel` and `npt/intel` if all these have intel styles. Script is attached in initial post.

Could be issues with our compiler, but tested both 2017 and 2018. Could be our cluster, but that seems a bit weird too...

**Comment by wmbrownIntel** [comment] 2018-06-22 00:46
@andeplane Hi Anders. Thanks for the detailed report and attaching the run scripts. I have not yet been able to reproduce this. I tried on KNL, Xeon Skylake, and Haswell and the restart files are always identical. I did a run with valgrind to check for any memory issues and none were reported; however for this case I ran with 28 MPI tasks, the GNU compiler without vectorization, and changed 10000 to 2 since it is very slow.

What is the CPU where you observed this? Was the output to a parallel file system? If by some chance you still have the restarts were the sizes significantly different?

**Comment by andeplane** [comment] 2018-06-28 13:15
Hey!

These simulations were performed on E5-2683v4 CPU's on our cluster Fram. You can get some more info about the system here: https://www.sigma2.no/Fram
Not really sure how the file system is.

I'll see if I can reproduce and attach the restart files.

**Comment by akohlmey** [comment] 2018-10-26 02:48
@andeplane @wmbrownIntel any updates on this issue? has it been addressed by any of the updates to USER-INTEL that have happened since? is there a reliable way to reproduce it? if not, it is probably cleaner to close this issue for now and reopen it, in case this pops up again with a way to reproduce it.

**Comment by akohlmey** [comment] 2018-11-29 04:43
taking this down now due to inactivity. if anybody has any news or a more specific information to reproduce it or a pull request with changes, please re-submit or re-open.

**Closed by akohlmey** 2018-11-29 04:43 UTC
