### ISSUE TITLE
[BUG] _CMAKE build failure w/g++-9_

### ISSUE THREAD

**Issue by ellio167** [lammps/lammps#1482] opened 2019-05-31 01:15 UTC
**Summary**

Build fails in kspace.cpp with omp related issue.

**LAMMPS Version and Platform**

version: current git master: daac3f7102f4d12b05d9ec24d13bfdf675496623

machine: mac w/homebrew g++-9 (gcc version 9.1.0 (Homebrew GCC 9.1.0))

cmake version 3.14.4

**Expected Behavior**

build completes

**Actual Behavior**

```
[ 56%] Building CXX object CMakeFiles/lmp.dir/Users/relliott/unison-sync/KIM/git/lammps/src/kspace.cpp.o
/Users/relliott/unison-sync/KIM/git/lammps/src/kspace.cpp: In member function 'void LAMMPS_NS::KSpace::qsum_qsq()':
/Users/relliott/unison-sync/KIM/git/lammps/src/kspace.cpp:278:3: error: 'nlocal' not specified in enclosing 'parallel'
  278 |   for (int i = 0; i < nlocal; i++) {
      |   ^~~
/Users/relliott/unison-sync/KIM/git/lammps/src/kspace.cpp:276:9: error: enclosing 'parallel'
  276 | #pragma omp parallel for default(none) reduction(+:qsum_local,qsqsum_local)
      |         ^~~
/Users/relliott/unison-sync/KIM/git/lammps/src/kspace.cpp:279:19: error: 'q' not specified in enclosing 'parallel'
  279 |     qsum_local += q[i];
      |                   ^
/Users/relliott/unison-sync/KIM/git/lammps/src/kspace.cpp:276:9: error: enclosing 'parallel'
  276 | #pragma omp parallel for default(none) reduction(+:qsum_local,qsqsum_local)
      |         ^~~
make[2]: *** [CMakeFiles/lmp.dir/Users/relliott/unison-sync/KIM/git/lammps/src/kspace.cpp.o] Error 1
make[2]: *** Waiting for unfinished jobs....
make[1]: *** [CMakeFiles/lmp.dir/all] Error 2
make: *** [all] Error 2
```

**Steps to Reproduce**

CXX=g++-9 cmake ../cmake/
make

**Comment by akohlmey** [comment] 2019-05-31 01:38
this is a duplicate of #1326 

The GCC developers decided to suddenly switch the behavior for whether const variables need to be placed in a shared OpenMP directive or not without any indication in the OpenMP level or backward compatibility (like Intel compilers do). Pre gcc 9 const variables **must not** be declared in shared directives (the compiler would error out); since gcc 9, they **must** be part of the shared directive.
To make things even more irritating, this change was done already in the OpenMP 4.x specs, but most people implementing OpenMP thought it was a mistake and expected that it would be reverted with a future version of the OpenMP standard, but the OpenMP consortium decided differently. So now the gcc has changed its behavior in a way, that makes it messy to detect it transparently.

This becomes an issue with LAMMPS because we are using 'default(none)' to detect incorrect sharing and missing sharing of variables, while 'default(shared)' is normally implied. At the moment, I am not willing to invest the effort to hack around this with pre-processor macros. Personally, I have started to switch to using Clang instead of GCC (which is not yet affected by this issue) and have deliberately not yet updated to Fedora 30 (which ships with gcc-9) but am still using Fedora 29 (which ships with gcc-8) until Fedora 31 has been released (when support for Fedora 29 ends).

There is a script `src/USER-OMP/hack_openmp_for_pgi_gcc9.sh` that can be used to translate all default(none) directives into default(shared). This was originally written to work around issues with some version of the PGI compilers that didn't handle 'default(none)' but it can deal with gcc 9 as well.

At the moment, i don't have a good idea what to do about this. I don't want to plaster each OpenMP directive with ifdefs and write them twice, but i also don't want to give up using 'default(none)', which has helped identifying a lot of bad OpenMP code. i am angry at the OpenMP consortium by not reverting a bad decision and thus causing a lot of headaches and i am angry at the GCC folks by throwing the switch on this in a way that does not allow for any grace period (a reasonable approach would have been to accept both variants for 1-2 gcc releases and print a deprecation warning when code uses the old variant or having a compiler switch that would allow to select which semantics to use).

**Comment by ellio167** [comment] 2019-05-31 01:44
Yuk.  Thanks for the explanation.  Sorry I didn't look around more to find the existing gcc-9 issue.

(I'll leave this open since #1326 is closed; which might help others find it.  But, feel free to close as you like.)

**Comment by akohlmey** [comment] 2019-05-31 01:45
oh, and another workaround is, of course, to disable OpenMP when configuring with cmake.

**Comment by akohlmey** [comment] 2019-05-31 01:47
for cmake, it is probably the best workaround, that we change the defaults. i.e. if you have gcc 9, then OpenMP is  disabled by default until somebody implements a better way of dealing with it. that way people that run cmake in an unsuspecting way, won't be surprised in the same way that you got surprised.

**Comment by ellio167** [comment] 2019-05-31 01:57
Yeah, that seems reasonable.  I actually didn't realize that it was enabling OpenMP!  (Suppose I should read the cmake output more closely ;-) )

**Comment by akohlmey** [comment] 2019-05-31 02:39
PR request with the change is submitted. this should be helpful for the upcoming stable release.

**Closed** 2019-05-31 17:05 UTC
Labels: bug, duplicate

**Comment by jibril-b-coulibaly** [comment] 2019-06-03 22:52
Hi,
The patch in the CMakeLists.txt uses VERSION_GREATER_EQUAL which the minimum required version 2.8.12 does not support. That causes a crash with "Unknown arguments specified" in the corresponding if command line 325 when using CMake 2.8.12.

Could you please provide a fix to it ? Thanks

**Comment by akohlmey** [comment] 2019-06-04 00:00
> Hi,
> The patch in the CMakeLists.txt uses VERSION_GREATER_EQUAL which the minimum required version 2.8.12 does not support. That causes a crash with "Unknown arguments specified" in the corresponding if command line 325 when using CMake 2.8.12.
> 
> Could you please provide a fix to it ? Thanks

making it work with cmake 2.8.12 is a bit hackish, but since this is a temporary workaround, it doesn't matter as much. the change is in PR #1489
