### ISSUE TITLE
Bug with neighbor lists for compute rdf in certain cases

### ISSUE THREAD

**Issue by akohlmey** [lammps/lammps#462] opened 2017-04-26 21:00 UTC
There seems to be something wrong with the construction of neighbor lists for `compute rdf` the various inputs attached to this issue are simulating the exact same system (with the exception of the `long` input, which uses a longer cutoff for lj/cut to have a comparable rdf file with the `cutoff` option), yet for some there are pairs with zero distance. This can be caused by adding the cutoff option, or using a hybrid pair style. Also, in some cases the trajectories are identical across the entire run, in some divergence sets in quickly when compute rdf is added.

[in.gofr-single.txt](https://github.com/lammps/lammps/files/959685/in.gofr-single.txt)
[in.gofr-hybrid-sw.txt](https://github.com/lammps/lammps/files/959683/in.gofr-hybrid-sw.txt)
[in.gofr-hybrid-lj.txt](https://github.com/lammps/lammps/files/959682/in.gofr-hybrid-lj.txt)
[in.gofr-hybrid-cutoff.txt](https://github.com/lammps/lammps/files/959684/in.gofr-hybrid-cutoff.txt)
[in.gofr-cutoff.txt](https://github.com/lammps/lammps/files/959686/in.gofr-cutoff.txt)
[in.gofr-long.txt](https://github.com/lammps/lammps/files/959769/in.gofr-long.txt)
[in.gofr-hybrid-airebo.txt](https://github.com/lammps/lammps/files/959768/in.gofr-hybrid-airebo.txt)

**Comment by stanmoore1** [comment] 2017-04-27 22:51
The issue is that the neighbor binning isn't happening often enough for the compute rdf neighborlist, and the neighborlist build is using stale bins in which atoms have moved outside of the bins. This leads to the atom being included twice in the neighborlist. If you use 'neigh_modify check no' then it works as expected. I'm looking into a fix.

**Comment by stanmoore1** [comment] 2017-04-27 23:16
@sjplimp is going to take a look.

**Comment by stanmoore1** [comment] 2017-04-28 23:06
Here is the fix for the hybrid case, I checked this in to the SVN branch:

<pre>
$ git diff
diff --git a/src/neighbor.cpp b/src/neighbor.cpp
index 4cd99b4..5a7525e 100644
--- a/src/neighbor.cpp
+++ b/src/neighbor.cpp
@@ -1216,7 +1216,7 @@ void Neighbor::morph_copy()

     // check all other lists

-    for (j = 0; j < i; j++) {
+    for (j = 0; j < nrequest; j++) {
       if (i == j) continue;
       jrq = requests[j];

@sjplimp is still looking into the rdf cutoff issue
@@ -1279,7 +1279,7 @@ void Neighbor::morph_copy()
     // turn list I into a copy of list J
     // do not copy a list from another copy list, but from its parent list

-    if (j < i) {
+    if (j < nrequest) {
       irq->copy = 1;
       if (jrq->copy) irq->copylist = jrq->copylist;
       else irq->copylist = j;
</pre>

@sjplimp is still looking into the issue with the rdf `cutoff` option

**Comment by stanmoore1** [comment] 2017-04-28 23:08
For the hybrid case, the occasional list wasn't getting copied from the parent list.

**Comment by stanmoore1** [comment] 2017-05-04 22:52
Also need, this I checked it into the SVN branch:
<pre>
Index: neighbor.cpp
===================================================================
--- neighbor.cpp        (revision 16479)
+++ neighbor.cpp        (working copy)
@@ -1226,8 +1226,11 @@

       // parent list must be perpetual
       // copied list can be perpetual or occasional
+      // if both lists are perpetual, ensure j < i to
+      //   prevent circular dependence

       if (jrq->occasional) continue;
+      if (!irq->occasional && j > i) continue;

       // both lists must be half, or both full
</pre>

**Comment by akohlmey** [comment] 2017-05-11 21:52
ok. it looks like all the test cases seem to be working now, except for the `cutoff` variants.
@sjplimp any updates or ideas on what may be causing this?

**Comment by stanmoore1** [comment] 2017-05-11 21:59
The issue is that the parent perpetual neighborlist could be build several timesteps in advance of when the occasional list is built. The occasional list uses the bins from the parent perpetual list, and in that time an atom could have moved outside of its original bin. When this happens, the atom is included twice in the list, and there is a zero radius.

**Comment by stanmoore1** [comment] 2017-05-18 19:14
Fixed by #488. Closed #462.

**Closed by stanmoore1** 2017-05-18 19:14 UTC
Labels: bug, neighborlist_feature
