### ISSUE TITLE
[BUG] const issues initializing lammps with the C API

### ISSUE THREAD

**Issue by bernstei** [lammps/lammps#2967] opened 2021-09-29 13:30 UTC
**Summary**

C-API example in https://docs.lammps.org/Library_create.html is incompatible with modern (strict?) compilers with respect to const variables/arguments

**LAMMPS Version and Platform**

github master 8d8c7109

**Expected Behavior**

Example program compiling as is

**Actual Behavior**

With the example program as given, attempting to pass the `const char *argv[]` to `lammps_open_no_mpi` gives the error
```
atoms.h:215:61: error: invalid conversion from ‘const char**’ to ‘char**’ [-fpermissive]
  215 |                 calc = (void *) lammps_open_no_mpi(lmpargc, lmpargv, NULL);
      |                                                             ^~~~~~~
      |                                                             |
      |                                                             const char**
```

Removing the `const` breaks (or at least causes a warning) the initializer
```
atoms.h:212:37: warning: ISO C++ forbids converting a string constant to ‘char*’ [-Wwrite-strings]
  212 |                 char *lmpargv[] = { "liblammps", "-log", "none"};
      |                                     ^~~~~~~~~~~
```

It would be nice if the example could be updated to work cleanly with modern (and strict) standards

**Comment by akohlmey** [comment] 2021-09-29 13:45
Please note that this is an example for the C language but you seem to be compiling with a C++ compiler in C++ mode.

**Comment by akohlmey** [comment] 2021-09-29 14:10
Still needs an added cast for strict C compilers.

The proper way to address this, however, requires some rather deep internal changes where char pointers are passed as const char pointers or even better as const std::string references. This is an ongoing process which also helps to make code more readable.

**Comment by bernstei** [comment] 2021-09-29 14:19
Yes - the problem also shows up with pure C for things like gcc 10
```
> cat t.c 
#include <stdlib.h>
#include <lammps/library.h>

void t() {
    const char *lmpargv[] = {"liblammps", "-log", "none" };
    int lmpargc = sizeof(lmpargv)/sizeof(const char *);

    void *calc = lammps_open_no_mpi(lmpargc, lmpargv, NULL);
}

>  gcc -I${HOME}/include -c t.c 
t.c: In function ‘t’:
t.c:9:46: warning: passing argument 2 of ‘lammps_open_no_mpi’ from incompatible pointer type [-Wincompatible-pointer-types]
    9 |     void *calc = lammps_open_no_mpi(lmpargc, lmpargv, NULL);
      |                                              ^~~~~~~
      |                                              |
      |                                              const char **
In file included from t.c:2:
/home/cluster2/bernstei/include/lammps/library.h:91:43: note: expected ‘char **’ but argument is of type ‘const char **’
   91 | void *lammps_open_no_mpi(int argc, char **argv, void **ptr);
      |                                    ~~~~~~~^~~~

> gcc --version
gcc (GCC) 10.3.0
Copyright (C) 2020 Free Software Foundation, Inc.
This is free software; see the source for copying conditions.  There is NO
warranty; not even for MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.

```
I'd be perfectly happy with a change to the example that provides some sort of workaround that isn't too ugly, but I don't have enough experience with recent C/C++ versions to have a good suggestion.

**Comment by akohlmey** [comment] 2021-09-29 14:45
The "fix" is simple:
```
  index 3566cb3cc9..8043819891 100644
  --- a/doc/src/Library_create.rst
  +++ b/doc/src/Library_create.rst
  @@ -34,7 +34,7 @@ simple example demonstrating its use:
        int lmpargc = sizeof(lmpargv)/sizeof(const char *);
   
        /* create LAMMPS instance */
  -     handle = lammps_open_no_mpi(lmpargc, lmpargv, NULL);
  +     handle = lammps_open_no_mpi(lmpargc, (char **)lmpargv, NULL);
        if (handle == NULL) {
          printf("LAMMPS initialization failed");
          lammps_mpi_finalize();
```

This is not considered good programming practice, but it is currently done inside of LAMMPS in many places.
Because there are some functions that modify strings (even if only temporarily) pretty much all char pointers currently must be passed as writable strings, even if it is know that they won't be modified. A lot of the LAMMPS code goes back many years and what was considered good programming practice then was different from what is now.  Also, LAMMPS has grown quite substantially and thus the constraints on how to write code to be maintainable must be much stricter now than in the past so that we don't end up with complete chaos.  It is a difficult balance to find ways to write "clean" and "proper" code but at the same time have it written in such a way that non-expert programmers can adopt and modify it.  Modern C++ specifically has many convenient and attractive features, but not all of them result in "accessible" code.

**Comment by bernstei** [comment] 2021-09-29 15:01
This slightly ugly construct seems to work in C++, at least to the point of not causing any errors or warnings.  Not sure if it's considered better than your simpler solution above
```
                char *lmpargv[] = { const_cast<char*>(std::string("liblammps").c_str()),
                                    const_cast<char*>(std::string("-log").c_str()),
                                    const_cast<char*>(std::string("none").c_str()) };
```

**Comment by akohlmey** [comment] 2021-09-29 15:08
> This slightly ugly construct seems to work in C++, at least to the point of not causing any errors or warnings. Not sure if it's considered better than your simpler solution above
> 
> ```
>                 char *lmpargv[] = { const_cast<char*>(std::string("liblammps").c_str()),
>                                     const_cast<char*>(std::string("-log").c_str()),
>                                     const_cast<char*>(std::string("none").c_str()) };
> ```

This is needlessly convoluted and has some other problems. In C++ the semantics for string constant are different, so you need my suggested change and define lmpargv array members as const char pointers and not string constants like shown below:

```
const char *lmpargv[] = { (const char*)"liblammps", (const char*)"-log", (const char*)"none"};
```

**Comment by bernstei** [comment] 2021-09-29 15:13
If by "suggested changes" you just mean casting `(char **)lmpargv` in the call to `lammps_open_no_mpi`, that appears to be sufficient, without casting the individual strings to `const char*` one by one.

**Comment by akohlmey** [comment] 2021-09-29 15:20
you have to distinguish between C and C++ semantics. Those differ with string constants. Thus just adding the type cast for the `lammps_open_no_mpi()` call is the simplest approach in C because the declaration of the `lmpargv` array is correct C code. However, it is not correct C++ code. In C++ string constants are handled differently. So you either define the list lmpargv list with the extra type casts as shown, or you have to dynamically allocate and deallocate proper writable strings. Your code will implicitly create temporaries that will go out of scope in some cases. The "clean" C++ version of the example from the documentation would be:

```
#include "library.h"
#include <cstdio>
#include <cstring>

int main(int, char **)
{
  void *handle;
  int version;

  char **lmpargv;
  int lmpargc = 3;
  lmpargv = new char*[lmpargc];
  lmpargv[0] = new char[16];
  lmpargv[1] = new char[16];
  lmpargv[2] = new char[16];
  strcpy(lmpargv[0],"liblammps");
  strcpy(lmpargv[1],"-log");
  strcpy(lmpargv[2],"none");

  /* create LAMMPS instance */
  handle = lammps_open_no_mpi(lmpargc, lmpargv, NULL);
  if (handle == NULL) {
    printf("LAMMPS initialization failed");
    lammps_mpi_finalize();
    return 1;
  }

  /* get and print numerical version code */
  version = lammps_version(handle);
  printf("LAMMPS Version: %d\n",version);

  /* clean up */
  delete[] lmpargv[2];
  delete[] lmpargv[1];
  delete[] lmpargv[0];
  delete[] lmpargv;

  /* delete LAMMPS instance and shut down MPI */
  lammps_close(handle);
  lammps_mpi_finalize();
  return 0;
}

```

**Comment by bernstei** [comment] 2021-09-29 15:21
thanks

**Comment by bernstei** [comment] 2021-09-29 15:29
Your c++ example waits until the very end to free the memory associated with `lmpargv`.  Is this necessary, i.e. is it in fact unsafe to assume that I can free that memory immediately after calling `lammps_open_no_mpi` ?

**Comment by rbberger** [comment] 2021-09-29 15:34
>                 char *lmpargv[] = { const_cast<char*>(std::string("liblammps").c_str()),
>                                   const_cast<char*>(std::string("-log").c_str()),
>                                    const_cast<char*>(std::string("none").c_str()) };

@bernstei Creating a std::string() and calling c_str() right after is just asking for trouble. You're returning a pointer from a temporary object that no longer exists after that line is executed. It might work by accident, but you're playing with fire here since you're pointing to a memory location that is no longer owned by anyone.

Concerning your other question, the cleanup right after calling `lammps_open_no_mpi` is fine. If anything, LAMMPS will keep a copy of anything it will need later on.

**Comment by akohlmey** [comment] 2021-09-29 15:36
> Your c++ example waits until the very end to free the memory associated with `lmpargv`. Is this necessary, i.e. is it in fact unsafe to assume that I can free that memory immediately after calling `lammps_open_no_mpi` ?

The "clean" approach to coding is to assume that data you pass to a "consumer" must be present until after the "consumer" has gone away, i.e. until you call `lammps_close()` (so my example is incorrect in that `lammps_close()` has to come first). Unless you have carefully audited the code you cannot know whether LAMMPS makes a copy or keeps the pointers (and I myself don't know for certain either. I don't know if we every audited LAMMPS for that).
Please note, that with the static declaration as string constants, those will always remain in scope.

**Comment by bernstei** [comment] 2021-09-29 15:40
> Unless you have carefully audited the code you cannot know whether LAMMPS makes a copy or keeps the pointers (and I myself don't know for certain either. I don't know if we every audited LAMMPS for that)

Good to know, and probably worth documenting.  I definitely would have assumed that it was OK (not in terms of formal C grammar, just based on my assumptions of what it is probably be doing with those arguments), consistent with my understanding of what @rbberger said, if we hadn't gone down this particular rabbit hole.

**Comment by akohlmey** [comment] 2021-09-29 15:52
> Good to know, and probably worth documenting. I definitely would have assumed that it was OK (not in terms of formal C grammar, just based on my assumptions of what it is probably be doing with those arguments)

Well, from the perspective of programming LAMMPS, of course, it is equally bad practice to assume that that data passed as an argument stays around for longer than the immediate function call. So any data passed as an argument that has to be kept around **should** be copied. We are only checking things more thoroughly for a few years now and there are still "dark corners" and surprises with unexpected behavior and code that could be improved. At the rate at which new code is currently added it is sometimes quite challenging to audit and adapte both the new and existing code for consistent and "clean" behavior. In particular when you have to keep in mind that the definition of "clean" varies over time and with the background and perspective of the individual programmer.

**Closed** 2021-09-29 23:46 UTC
Labels: bug
