### ISSUE TITLE
Pair AIREBO bug reported by several independent groups

### ISSUE THREAD

**Issue by rbberger** [lammps/lammps#59] opened 2016-05-12 18:13 UTC
As reported in several emails there is a bug lurking in the AIREBO styles which causes large spikes. I've ran the reported minimal case and found that the following sin inverse term is the source of the large forces being computed. See https://github.com/akohlmey/lammps/blob/c465f77cb7453fd7e9773cf6fbf08b2092d79296/src/MANYBODY/pair_airebo.cpp#L2670. We have to figure out how we come into this (probably illegal) state.

**Comment by akohlmey** [comment] 2016-05-12 19:49
I've made the code safe against division by (near) zero, but that doesn't seem to be the whole story.
https://github.com/akohlmey/lammps/commit/c5b34d683dd8336669ac413dabdc45920dd1b509

**Comment by akohlmey** [comment] 2016-05-12 20:58
Compute pair support is added in this commit: https://github.com/akohlmey/lammps/commit/c75cc25d6c7b2be28a6a77e22bcedb8a3cead853

**Comment by v0i0** [comment] 2017-02-01 16:16
I might be able to add some pieces to the puzzle of what's wrong with AIREBO. I'll focus on the `bondorderLJ` method, since I believe the issues come from there. Arguably, it's also the most tricky thing one needs to figure out to implement AIREBO. It would be great if someone else could confirm my suspicions.
1. Etmp gets updated again in line 2753, after having been computed with the loops from line 2287. This means that the force updates in line 2959 and 2894 compute twice the expected force contribution.
2. The code between line 2666 and line 2928 seems to randomly pick whether to use `rij` or `r23` as a variable. (one is scaled/ficticious, the other is original). This leads to many issues, for example the cosine from line 2699 is incorrect. The correct code would use rij there, and not recompute. The "physical" distance is only required in one instance I describe in (4).
3. Consulting the Fortran code (from OpenKIM), it seems that `d/drij` derivatives should be assumed zero in many cases in `bondorderLJ`, but are not.
4. Again looking at the Fortran code (and doing a bit of math), some forces need a correction by `r_cutoff / |rij| * (I - rij . rij^T / |rij|^2)`. Now this is the one instance where `rij` is the "physical" distance, since it is the derivative to `rij/|rij|`. In total, this correcting should be performed in four places.
5. The spline functions have big discontinuities. Minute changes (`O(10^-12)`) can lead to huge variations in output (`O(10^-6)`).

I've tried to implement fixes to most of these issues (i.e. 1-4, since these only affect bondorderLJ), but I can only see little improvement in accuracy when compared against the OpenKIM Fortran code. It certainly pushes the forces into the right direction, but this likely means that there are additional issues lurking in the code.
I've attached the current state of my fixed code (needs a lot of cleanup right now, sorry). Also a trajectory that exercises bondorderLJ (50 atoms, section of CNT), as well as scripts to run with my code, unmodified LAMMPS and OpenKIM: [airebo-bondorderLJ-fixes.zip](https://github.com/lammps/lammps/files/745405/airebo-bondorderLJ-fixes.zip)

**Comment by CF17** [comment] 2017-05-10 06:31
I may have found a bug with the spline functions that could explain the big discontinuities in the spline functions. Let's take the example of the spline pCC

1. Looking at the current version of the code (31Mar17), the parameters pCCdom[i][0] and pCCdom[i][1] are fixed to 0 and 4, such that 0<= NijC <= 4 and 0<= NijH <= 4 (see code lines 3111 to 3114). However the spline coefficients assume that the values of NijC and NijH are lower than 4 (the dimension of the array pCC[x][y][i] is 4x4x16=256). Therefore in the case where for example NijH=0.1 and NijC = 4 then the code will get a value of pCC out of bounds.  For a specific geometry i actually got some NaN in the calculation of the energy.

2. The values of the spline at the knots are hard-coded in the subroutine spline_init. However the spline coefficients are read from the input file. I am wondering if there could be some discrepancies between these two. For example, recently a bug was fixed in the code: the value of the parameter PCCf should be different in REBO and AIREBO. However, I am not sure that the spline coefficients in the file CH.airebo were updated accordingly. 

I am not completely sure these are real issue or what is the best way to fix it. On way would be to recompute the spline coefficients and increase the size of the matrix pCC to 5x5x16. I am actually wondering if these coefficients should not be computed in the code such that any change in the value at the knots could be directly included in the spline coefficients.

**Comment by CF17** [comment] 2017-05-11 07:53
I figured the origin of the bug that I have observed in the AIREBO potential. 
In the calculation of the bicubic spline pCC and pCH at  lines: 3123, 3124, 3145, 3145
the variable x and y which set the splines coefficients are wrongly set:

x = (int) (floor(NijC)); 
y = (int) (floor(NijH));

For example if NijC=0.1 and Nij=4 then x=0 and y=4. While it should be x=0 and y=3.

This can lead to out of bounds array. Instead x and y should be set in a similar fashion as for the other splines (piCC for example) using this code for pCC

for (i=0; i<pCCdom[0][1]; i++)
  if (NijC>=(double) i && NijC<=(double) i+1) x=i;
for (i=0; i<pCCdom[1][1]; i++)
  if (NijH>=(double) i && NijH<=(double) i+1) y=i;

and this code for pCH:
      
for (i=0; i<pCHdom[0][1]; i++)
  if (NijC>=(double) i && NijC<=(double) i+1) x=i;
for (i=0; i<pCHdom[1][1]; i++)
  if (NijH>=(double) i && NijH<=(double) i+1) y=i;

**Comment by akohlmey** [comment] 2017-05-15 18:49
Thanks for digging into this and discovering this bug. As with a few other _unexpected features_, that we found before, this looks like a problem originating from translating a Fortran code into C++. After staring at the code for a bit, however, I think there is a simpler and more efficient way to achieve the same effect, e.g. like below, which will also allow for some additional cleanup and simplification of the associated code.
```c++
    if (NijC <  pCCdom[0][0]) NijC=pCCdom[0][0];
    if (NijC >= pCCdom[0][1]) NijC=pCCdom[0][1]-TOL;
    if (NijH <  pCCdom[1][0]) NijH=pCCdom[1][0];
    if (NijH >= pCCdom[1][1]) NijH=pCCdom[1][1]-TOL;
    x = (int) floor(NijC);
    y = (int) floor(NijH);
```
I'll put this into a pull request soon and then you and others can check it out.

**Comment by EfremBraun** [comment] 2017-05-16 02:03
I've run my old input file that was AIREBO was causing to crash with the updated code from #483 and it looks like the code is no longer crashing. Obviously that's no guarantee that the code is necessarily correct, but at least it's something.

Input files attached. Using the 17 Nov 2016 LAMMPS source code, the run crashes at 779,534 timesteps. With the code from #483, I've up to 800,000 timesteps and it hasn't yet crashed. I'll keep it running for awhile more to see if it ends up crashing at a later point.

[data.airebo.txt](https://github.com/lammps/lammps/files/1002982/data.airebo.txt)
[in.airebo.txt](https://github.com/lammps/lammps/files/1002981/in.airebo.txt)

**Comment by CF17** [comment] 2017-05-16 13:03
I have found another bug in the code. The calculation of the derivatives of the dihedral term in the bond order are wrong. In the subroutines bondorder and bondorderLJ the variable aaa2 is used to compute the derivatives originating from the cutoff functions (1.0-tspijl) and (1.0-tspkik). However these terms are included in the calculation of aaa2 while they should be remove (since we are computing the derivative). Therefore, in these subroutines the following line
`aaa2 = aaa1*w21*w34;`
should be replaced by 
`aaa2 = -prefactor*(1.0-square(om1234))*w21*w34;`

Now when I run an NVE simulation with 5000 K of kinetic energy and I disable the LJ term in AIREBO, I get a very good energy conservancy which is improved as I decrease the timestep. When I add the LJ term in AIREBO, the energy is again not conserved anymore. Therefore there is still some problem to be solved.

**Comment by EfremBraun** [comment] 2017-05-16 22:19
My run from yesterday crashed at 5,602,000 timesteps. I'll recompile with the latest commit and see if it fixes things. It takes a few hours of running to crash at this point, so I'll give another update tomorrow.

**Comment by EfremBraun** [comment] 2017-05-17 17:10
With Axel's latest commit, the run is up to 9,475,000 timesteps and still going. It's set to run up to 25,000,000 timesteps, so it'll be running for another 2 days before it finishes. I'll let you know if it crashes before then.

**Comment by EfremBraun** [comment] 2017-05-18 16:56
Crashed, this time at 14,600,000 timesteps. If the problem that @CF17 mentioned is found and fixed, I'll test again.

**Comment by v0i0** [comment] 2017-05-19 21:54
@EfremBraun Do you have a corresponding restart file that you could share?

**Comment by EfremBraun** [comment] 2017-05-20 00:41
Unfortunately I deleted the directory. I'll have it rerun over the weekend and get you a restart file on Monday.

**Comment by EfremBraun** [comment] 2017-05-22 17:37
My apologies, but I can't reproduce the crash. The re-run is up to 20,425,000 timesteps and it's still running fine. I made a very small change to the input file (split up the "run" command into two separate "run" commands of shorter length, and put the "restart" command after the first "run" command ended), though I don't think that should have changed anything.

I'll re-run with the original input now just to be sure, but I'm afraid it will take another 2 days to get back up to 14,600,000 timesteps. Sorry about the delay.

**Comment by Kammlma** [comment] 2017-05-29 12:45
Hi there, I'm working on an implementation of the REBO potential (not AIREBO, I'll only be talking about the REBO part) for my own MD code and thought it'd be a good idea to use LAMMPS (lammps-31Mar17) as a verification tool. There seems to be an issue with both the piRC and Tij forces. 

In lines 1618 (derivative w.r.t. _wik_) and 1640 (derivative w.r.t. _SpN_) (or more generally speaking, the lines where _dN3_[2] is being referenced), there needs to be an additional factor of kronecker(_ktype_,0). If atom _k_ is not a carbon atom, then it does not contribute to _Nijconj_ of atom _i_.

Same at lines 1681 and 1703, but this time there's a factor of kronecker(_ltype_,0) missing. The correction of the Tij forces should then be straightforward.

**Comment by EfremBraun** [comment] 2017-05-29 17:39
@v0i0 Sorry, but I can't reproduce the crash using the exact same input file. Not sure what could've happened. It now looks like I can get to the full 25,000,000 timesteps without crashing using the source code from Axel's commit.

**Comment by v0i0** [comment] 2017-05-30 12:57
@Kammlma Thanks! That indeed looks like another real bug. Is there anything else you've noticed that seems incorrect/suspicious?
@EfremBraun Alright. But do you still see the spiking energy behaviour that was originally reported?

**Comment by Kammlma** [comment] 2017-05-31 08:42
@v0i0 Everything else seems correct to me. I can now achieve energy conservation in all of my test cases with LAMMPS as well as with my code. That's a good indication that the forces are now correct.

**Comment by v0i0** [comment] 2017-05-31 10:38
@Kammlma Can you have a look at #513 and check whether that would fix the issue?
@CF17 Since #513 also touches AIREBO code, you might want to try it and see if there is an improvement in energy conservation (It will only have changed things if your simulation contains Hydrogen, though).

**Comment by Kammlma** [comment] 2017-05-31 11:25
@v0i0 #513 fixes all energy conservation issues that I came across.

**Comment by EfremBraun** [comment] 2017-06-02 03:37
@v0i0 Hard to say if the energy spikes are still there; before, I was just looking at the energies in the few timesteps before a crash occurred. If you'd like, I can re-run the simulation logging the energies every step, and then plot all energies vs time; this would tell me the answer to your question. Let me know if you'd like me to do that.

**Comment by CF17** [comment] 2017-06-02 13:58
I made additional tests with AIREBO and focused on understanding why we don't have energy conservation. I figured out that one of the issue is coming from the bondorderLJ subroutine. Analyzing the code, I don't understand why this is written in such complicate manner. The bij* term should be equivalent to the bij term except the distance between i and j is modified. the bij term mostly include angles and dihedral angles and these are independent of the rij distance. Therefore these forces should be the same. The only difference I can see between bij and bij* is found in the lambdaijk term which indeed include a term that depends on the distance rij. By coping the bondorder subroutine, I completely rewrote the bondorderLJ subroutine, I found with this version that the energies are exactly the same as before but the forces are much better and the energy conservation while not perfect is much better. I am attaching the version of the source code I have been using. I am wondering if someone can run additional tests with this code. One just have to compile lammps with these files and use the pair style airebo/new.

[pair_airebo_new.zip](https://github.com/lammps/lammps/files/1047862/pair_airebo_new.zip)

**Comment by v0i0** [comment] 2017-06-02 15:44
@CF17 Thanks a lot, I'll do some more detailed tests with your code later.
Btw. would you be willing to share a reduced bit/proxy of your simulation. It would help debugging a lot.

Anyway, here are my initial thoughts:

1. The `wij` calculation should still use the old distance `rij0mag` since it subtracts out the contribution fro `nC`/`nH` .
2. I'm not sure why the `lamdaijk` calcalation should use `rij0mag` though. Note that the derivatives w.r.t. `lamdajik` do not appear later, since `rijmag` is constant as far as `bondorderLJ` is concerned.
3. I just did the math, and angular terms still require a correction due to the fact that their vector is scaled. For cosines that works out as `rijmag / rij0mag`, for general dependencies on `rij` it works out as `rijmag/rij0mag * (Identity - rij0 rij0^T / rij0mag^2) * F` and the code is careful to apply that correction. For dependecies on `rijmag` the force contribution should be zero (since `rijmag` is a constant).

**Comment by CF17** [comment] 2017-06-02 19:35
In the code I wrote `rij0mag` is actually now the modified distance so its a constant (1.7 angstroms) and the `rijmag` is the real physical distance. I compute all angles and dihedral angles with the real physical positions such that there is no correction needed. The only correction necessary is in the `lambdajik` which here requires the constant distance (in my case `rij0mag`). The same is true for `wij`. I am attaching an input file which simulate a box of 128 carbon atoms at very high temperature.

[carbon128.zip](https://github.com/lammps/lammps/files/1048758/carbon128.zip)

**Comment by akohlmey** [comment] 2017-06-29 18:47
@v0i0 from the maintainer's perspective, and considering the complexity of the AIREBO code, the preference is for small, incremental changes unless there is a very compelling reasons to choose differently. if i understand correctly, the alternative implementation affects only a single subroutine, in that case, we could also make it a runtime choice, i.e. using instead of the choices 0 and 1 for FLJ, we would add a flag 2, which would select the new code path. if that cannot be done, we can also consider making it a compile time choice using pre-processor defines. last (and least desirable) option would be an airebo/mod style derived from airebo which overrides functions as needed.

The ultimate decision will have to be made by steve. i suggest you consider my point of view, but only as that (a single point of view), and make the decision that you are yourself most comfortable with, and submit that as a pull request. if you explain your reasons for your choices, then steve will consider them properly, give his feedback, and either accept your choice or suggest alterations. in my experience, it is easiest to have a focused discussion with steve, when you have a chunk of code in had that he can look at.

**Comment by CF17** [comment] 2017-06-30 15:39
@v0i0 @akohlmey I suggested this new code for AIREBO for the following reasons:

1. From a scientific point of view, having a simpler implementation is good since it allows more people to understand what is actually being computed. This is why I decided to actually rewrite completely the subroutine since I could not understand what was actually computed in the current version.

2. From a computational perspective, having almost the same code between the REBO bondorder subroutine and the AIREBO bondorderLJ subroutine is good since any improvement in one subroutine can be directly applied in the other one and I believe there is room for improvement in the bondorder subroutine to make it faster.  

Actually to improve the bondorderLJ subroutine I think the forces should be computed at the same time as the energy and saved in some kind of array to be used later. It could save some time since some parameter are computed twice. I am not sure how to do that since I don't know the overall LAMMPS structure.

In any case, this is just a suggestion and I am not a lammps developper. You guys can decide what to do. As an AIREBO user I am just happy to have a code that is working and provide the right forces. It does not really matter to me how it is computed. In principle both implementation should give the same results and in this case I do not see the point to have both implementations. 

@v0i0 this is great that you implemented this spline coefficients calculation. If I may make a suggestion, I think the value at the knots should be read from the airebo potential file (instead of the coefficients in the current implementation). With this it should be quite easy to introduced the different modification of the REBO and AIREBO potential you can find in the literature and to make new versions. 

On this topic I don't quite understand why when the parameter are close to the knots (within a certain tolerance) the value is directly set.  I know the tolerance parameter is quite small but it introduce an additional error. Is it to make the code faster ?

**Comment by v0i0** [comment] 2017-07-05 13:47
Alright, thanks for your feedback. I've created a pull-request incorporating the changes.
I've decided to use @CF17's code, since it seems a lot more consistent to do so, but I'm happy to discuss.

> Actually to improve the bondorderLJ subroutine I think the forces should be computed at the same time as the energy and saved in some kind of array to be used later. It could save some time since some parameter are computed twice. I am not sure how to do that since I don't know the overall LAMMPS structure.

I'm currently developing an optimized AIREBO code that will integrate with the USER-INTEL package.
What you're describing is one of the many optimizations that will be included.

> @v0i0 this is great that you implemented this spline coefficients calculation. If I may make a suggestion, I think the value at the knots should be read from the airebo potential file (instead of the coefficients in the current implementation). With this it should be quite easy to introduced the different modification of the REBO and AIREBO potential you can find in the literature and to make new versions.

Since backwards compatibility is a concern, I'd prefer not touching the `CH.airebo` file. Users tend to not keep it in a central place but to duplicate and copy it around, and changing it would break their simulations.

> On this topic I don't quite understand why when the parameter are close to the knots (within a certain tolerance) the value is directly set. I know the tolerance parameter is quite small but it introduce an additional error. Is it to make the code faster ?

I did not write this, but IMO it's a performance optimization, since the vast majority of atoms will have integer values in the majority of simulations.

**Comment by CF17** [comment] 2017-07-05 15:21
Thanks the pull request and thanks for the info

**Closed** 2017-07-13 19:10 UTC
Labels: bug, manybody_package
