### ISSUE TITLE
[BUG] Inconsistent unit conversion in QEQ part of Reaxff module

### ISSUE THREAD

**Issue by heindelj** [lammps/lammps#3457] opened 2022-09-23 21:26 UTC
**Summary**

In the reaxff module, there are three constants which are defined in `reaxff_defs.h`.

They look as follows:
```
#define C_ele 332.06371
#define EV_to_KCALpMOL 14.400000    // ElectronVolt --> KCAL per MOLe
#define KCALpMOL_to_EV 23.02        // 23.060549 //KCAL per MOLe --> ElectronVolt
```

The way these constants are defined, `C_ele / EV_to_KCALpMOL` should exactly equal `KCALpMOL_to_EV`. As the comment on this line indicates, the correct conversion is 23.060549. However, since even in EEM papers, the conversion of EV to kcal/mol is often set exacty equal to 14.4, the correct value of `KCALpMOL_to_EV` should be `23.059979861`. This is also much closer to the actual unit conversion.

The reason this is a problem is it means that the analytically calculated forces and the finite difference forces do not agree with one another. I have tested this with my own implementation using the constants in Lammps and the constants I suggest. Even for a diatomic like CO, the constants in Lammps will not give gradients that are consistent with the Coulomb energy. Therefore, this will contribute to a lack of energy conservation during long simulations. 

**LAMMPS Version and Platform**

master brach. Platform independent problem.

**Expected Behavior**

Energies and gradients should be consistent in the sense that finite difference gradients and analytic gradients are equal to within numerical precision.

**Actual Behavior**

Finite difference gradients and analytic gradients are not equal to within numerical precision.

**Steps to Reproduce**

Compute the finite difference gradients of the coulomb energy and compare it with the analytic gradient computed by Lammps for that same quantity.

The differences will be on the order of 0.5 to 1.5 kcal/mol/A. This is more than sufficient of an inconsistency to meaningfully contribute to a lack of energy conservation over long simulations.

**Comment by stanmoore1** [comment] 2022-09-26 16:46
I will take a look.

**Comment by athomps** [comment] 2022-09-26 16:47
@akohlmey I have assigned this to @stanmoore1.  I think he is better qualified than me to review ReaxFF PR's.  This seems like an important issue that I had not heard about before.  Requiring that forces and energy be consistent is a minimum requirement for any potential.

**Comment by athomps** [comment] 2022-09-29 22:24
After doing my own checking, I do not recommend adopting this proposed changes, for several reasons:

0. It is not a bug
1. The current value of KCALpMOL_to_EV matches that used in the original serial ReaxFF code of Adri van Duin
`reax: reax_poten.F:      c1=23.02           !conversion from kcal to eV`
3. The value is applied consistently to both energy and force calculations, so changing it has no effect on energy conservation or comparisons between numerical and analytical forces. For example, when I run both versions on examples/in.reaxff.rdx with `fix numdiff 1.0e-4`, on timestep zero, I get RMSE force errors 0.00035025011 kcal/mol/A and 0.00035025006 kcal/mol/A, with current and proposed values of KCALpMOL_to_EV, respectively.

**Comment by athomps** [comment] 2022-09-29 22:30
@heindelj I'd be curious to know how you observed force differences on the order of 0.5 to 1.5 kcal/mol/A. Your test must differ from mine in some way.

**Comment by heindelj** [comment] 2022-09-29 23:22
@athomps I have a different implementation of ReaxFF which agrees with the Lammps implementation basically bit for bit in outputs. I did not do the finite difference with the Lammps implementation, but in my implementation I get rather large differences in forces. I am testing on small molecules in the gas phase right now so maybe that is somehow related to seeing larger force differences? I'm not sure. For some systems the differences are on the order 0.01 kcal/mol/A.

I don't really understand why there is no difference in your tests, but if that's the case then I can see why you would not want to update the constant. When I use the Lammps values of the conversions I get the same exact energy so I don't know what to think. Perhaps the numerical error gets masked by the other energies. I am looking at only the finite difference of the coulomb term.

On the other hand, the constant `332.06371` is a conversion from hartree to kcal but scaled by the bohr radius. Similarly, the conversion factor `14.400000` converts from hartree to eV but scaled by the bohr radius (the name of the constant is wrong). So, the ratio of these two quantities should give you a conversion from kcal to eV. The conversion factor used is not equal to this ratio, so to me it makes sense to change the quantity to make the conversions exactly preserved.

I'll let you decide but thought I'd bring this up since I don't think the currently used values are internally consistent.

**Comment by athomps** [comment] 2022-12-12 22:25
@heindelj Sorry for the long delay. This fell off my radar for a bit. If I understand correctly, you have two codes LAMMPS and OTHER. When comparing energy, LAMMPS and OTHER agree, but when comparing forces, they do not.  That implies that at least one of the codes is calculating incorrect forces, meaning that they are not the derivatives of the energy.  My testing indicates LAMMPS forces are correct to within 0.00035 kcal/mol/A.  In your testing, have you confirmed that either LAMMPS forces or OTHER forces are( or are not) correct?

**Comment by athomps** [comment] 2023-10-06 20:40
In the absence of further evidence, I think we should conclude that this is not an error in need of correction.

**Closed as completed** 2023-10-09 16:05 UTC
Labels: bug
