### ISSUE TITLE
[BUG] Segmentational fault with ReaxFF on polymer + water at high Pand T

### ISSUE THREAD

**Issue by vincent-dufourdecieux** [lammps/lammps#2012] opened 2020-04-21 16:29 UTC
**Summary**

I run a simulation with 200 molecules of water and 1 25-monomer-long chain of PH3B. I use ReaxFF potential with parameters from Monti et al. (2013). I start at 300K and 1atm and then increase to 1000K and 100 atm. After stabilization, the simulation runs fine at the latter T and P for 450,000 steps and then breaks giving me a "Segmentational fault". There is no big change in energy, temperature or pressure before the error.

**LAMMPS Version and Platform**

LAMMPS (22 Aug 2018)

Operating System: CentOS Linux 7 (Core)
       CPE OS Name: cpe:/o:centos:centos:7
            Kernel: Linux 3.10.0-957.27.2.el7.x86_64
      Architecture: x86-64

**Expected Behavior**

I need to be able to run ReaxFF simulation of polymers and water at high T and P for a long time, in order to be able to see some reactivity.

**Actual Behavior**

The system evolves normally during the initialization process at 300K. Then I do a ramping from 300K and 1atm to 1000K and 100 atm. The ramp up happens correctly. Then the system stabilizes around 1000K and 100atm and the atoms move and react normally for 450,000 steps. Then the simulation breaks suddenly, and I can't find any particular sign in the output file, the lammps.log file or by visualizing it.
**Steps to Reproduce**
My input file is phase_water.txt that I attached here. I run it using lmp_intel_cpu_intelmpi, and the .sh file is analyzer.txt. The .dat files are PH3B_24mono_different.txt and water.txt and the ReaxFF parameters are protein.ffield.reax.txt. I also added the lmp_control and param.qeq files that I used.
It is possible that the simulation doesn't break before the 500,000 steps of the "50_ns phase" (see phase_water.txt) so you may need to run it a bit longer to see the problem. 

**Further Information, Files, and Links**

I converted everything to .txt file, and normally, I changed the names in the input file (phase_water.txt). I hope it doesn't affect the way it works.

[pha_water.txt](https://github.com/lammps/lammps/files/4511161/pha_water.txt)
[lmp_control.txt](https://github.com/lammps/lammps/files/4511166/lmp_control.txt)

[PH3B_24mono_different.txt](https://github.com/lammps/lammps/files/4511168/PH3B_24mono_different.txt)
[protein.ffield.reax.txt](https://github.com/lammps/lammps/files/4511169/protein.ffield.reax.txt)
[water.txt](https://github.com/lammps/lammps/files/4511170/water.txt)
[param.qeq.txt](https://github.com/lammps/lammps/files/4511172/param.qeq.txt)
[analyzer.txt](https://github.com/lammps/lammps/files/4511190/analyzer.txt)

**Comment by stanmoore1** [comment] 2020-04-21 16:36
You could try the Kokkos version. It is more robust in memory.

**Comment by akohlmey** [comment] 2020-04-21 16:41
Thanks for the report, but we have no resources and no time to debug simulations that require very many steps until they crash. You either need to find a way to trigger the crash reliably and quickly, or need to try some workarounds and hope they resolve the issue.

First thing to try out is always to use the very latest LAMMPS version (in this case either the latest stable release 3 March 2020 or the latest patch 15 April 2020) to make certain that this is not some issue that has already been addressed.

The second issue is that the ReaxFF is making some assumptions about how much of what kind of data is used on each MPI rank. If this changes too much, then the initial guesses will not be sufficient. You can use the "mincap" and "safezone" parameters to increase the extra buffer space.
Another option would be to check, if you can break down your simulation into chunks of, say 250,000 and run a loop, or in a more extreme case, write out a restart file, issue the clear command and do a complete restart.

Finally, there is also the KOKKOS version of the ReaxFF pair style, which uses a more reliable way of managing the memory and thus runs less often into the kind of memory issues that I mentioned.

**Comment by vincent-dufourdecieux** [comment] 2020-04-21 16:52
Hi,

Thanks for the quick answer ! I'll try new version of LAMMPS and try to use Kokkos or change the mince and safezone parameters and I will let you know.

**Comment by akohlmey** [comment] 2020-04-29 13:59
@vincent-dufourdecieux do you have any updates for us on this issue? or a way to more quickly and with few resources reproduce a failure?

**Comment by vincent-dufourdecieux** [comment] 2020-04-29 15:28
Hi,

I was about to give an update, thanks for the reminder !
So I tried:
- To use the last stable version of LAMMPS (3 March 2020) --> It didn't change anything
- To increase mincap (up to 4) and safe zone (up to 400) --> It worked a bit, but I am trying to reach very high pressure, so this solved it for pressure  100 atm, 200 atm, but when I tried 1000 atm, it didn't work. I don't know how high I can increase mincap and safe zone, what would you recommend ?
- I tried to work with Kokkos with the executable lmp_kokkos_mpi_only --> Kind of the same, it worked for 100 atm, and broke when I went up to 1000 atm. It gave me the error below, which seems to be the same as when I don't use Kokkos. 

[sh02-03n41:146747:0:146747] Caught signal 11 (Segmentation fault: address not mapped to object at address 0x637944b0)
==== backtrace ====
    1  /share/software/user/open/ucx/1.3.1/lib/libucs.so.0(+0x1916b) [0x7f78ea7a616b]
    2  /home/users/vdufourd/lammps-3Mar20/src/lmp_kokkos_mpi_only() [0x57eaf4]
    3  /home/users/vdufourd/lammps-3Mar20/src/lmp_kokkos_mpi_only() [0x57efc5]
    4  /home/users/vdufourd/lammps-3Mar20/src/lmp_kokkos_mpi_only() [0x57f8ae]
    5  /home/users/vdufourd/lammps-3Mar20/src/lmp_kokkos_mpi_only() [0x9c6b3f]
    6  /home/users/vdufourd/lammps-3Mar20/src/lmp_kokkos_mpi_only() [0x7a2462]
    7  /home/users/vdufourd/lammps-3Mar20/src/lmp_kokkos_mpi_only() [0x571405]
    8  /home/users/vdufourd/lammps-3Mar20/src/lmp_kokkos_mpi_only() [0x4f27c6]
    9  /home/users/vdufourd/lammps-3Mar20/src/lmp_kokkos_mpi_only() [0x4f0b61]
   10  /home/users/vdufourd/lammps-3Mar20/src/lmp_kokkos_mpi_only() [0x4f15bf]
   11  /home/users/vdufourd/lammps-3Mar20/src/lmp_kokkos_mpi_only() [0x407a76]
   12  /lib64/libc.so.6(__libc_start_main+0xf5) [0x7f78f6ca0495]
   13  /home/users/vdufourd/lammps-3Mar20/src/lmp_kokkos_mpi_only() [0x407e5f]
===================
srun: error: sh02-03n41: task 17: Segmentation fault
srun: Terminating job step 66286202.0
slurmstepd: error: *** STEP 66286202.0 ON sh02-03n40 CANCELLED AT 2020-04-28T15:08:40 ***
srun: error: sh02-03n41: tasks 10-16,18-19: Terminated
srun: error: sh02-03n40: tasks 0-9: Terminated
srun: Force Terminated job step 66286202.0

I don't know if you have any further idea here ? 
I will try to reduce the system to make it break faster with fewer resources. Do you have an idea on the order of magnitude of number of time steps and number of atoms that you can achieve in reasonable time ?

Thanks a lot for your help !

**Comment by akohlmey** [comment] 2020-04-29 15:39
This all looks like this is an intrinsic issue of a very high density. To address that would require expertise on the low-level implementation of the code. I am assigning this issue now to @hasanmetin in the hope that he may have some suggestion. Or as an alternative, you may look his contact info up from the source code or the LAMMPS webpage and send an e-mail directly.

A related question is: do you actually have ReaxFF parameters that are valid for such a system? Is this something that somebody else has done and published?  ReaxFF parameters tend to be much less transferable than other force field parameters. So if you have a set that has been used under similar conditions, you may want to look up publications using it and contacting the authors about how they made it work, in case they used LAMMPS.

**Comment by stanmoore1** [comment] 2020-04-29 21:34
How long does this run for and how many CPU cores? Can you try dumping out a data or restart file right before it crashes, then load it back in to see if you can get a short reproducer?

**Comment by mkanski** [comment] 2020-04-30 12:33
Try increasing MIN_HBONDS to something like 200 and recompile LAMMPS. It solved the segmentation fault problem for me in a similar case. 
https://github.com/lammps/lammps/blob/5c2f0ecc65b2187898940e746bd47b87641213a5/src/USER-REAXC/reaxc_defs.h#L94

You can increase `mincap` and `safezone` as far as you have enough RAM for it. Also, the value of `hbond_cutoff` in `lmp_control` is much larger than in standard ReaxFF parameterizations. Why would you use such a value?

**Comment by vincent-dufourdecieux** [comment] 2020-04-30 15:04
Thanks for all your suggestions !
@akohlmey : I will @hasanmetin ! And in terms of pressure I saw one article where they mention going to pressure around 1000 atm for these ReaxFF parameters, but they don't use LAMMPS. And those parameters have been used for similar systems with polymers in water.

@stanmoore1 : I will try @mkanski suggestions and if it doesn't work, I will do as you suggest. Right now it runs for few hours on 40 CPUs I think, so it would be way too long if you don't have the resources so I will make a restart file.

@mkanski : I will try that ! And for bond_cutoff, I think some pages on LAMMPS documentation were showing 10 or 7.5, so that's what I have been using.

**Comment by stanmoore1** [comment] 2020-04-30 15:06
>Try increasing MIN_HBONDS to something like 200 and recompile LAMMPS

Kokkos doesn't use this, so if it is still segfaulting with Kokkos the issue is probably somewhere else.

**Comment by stanmoore1** [comment] 2020-04-30 15:12
This is what I would do:

1. Make sure your Makefile has `-g` (debug symbols enabled)
2. Compile with clang or gcc and add `-fsanitize=address` to both compile and link flags.

This should give a detailed stack trace on segfault.

**Comment by mkanski** [comment] 2020-04-30 15:40
@vincent-dufourdecieux 
You use 10A as the hydrogen bond cutoff instead of standard 7.5. This will lead to much more Hbond interactions, especially in a compressed state.

Two other things you can try:
1. Use `fix dt/reset` instead of a static timestep.
2. Check if a neighbor list has to be rebuilt at every step, i.e `neigh_modify every 1 delay 0 check yes` It's computationally cheap, so the performance should not be affected.
You can also use `restart` command, so you won't have to repeat the whole simulation after making changes. 

@stanmoore1 I didn't know that. I agree that it may be something else then.

**Comment by vincent-dufourdecieux** [comment] 2020-05-01 16:09
Thanks to all your suggestions !
When I don't use Kokkos, and that I set the hbond_cutoff to 7.5 and the HMINBONDS to 200, it works ! I tried pressure up to 2000 atm and it works fine ! I am not sure yet how high I need to go for pressure, so I'll see when I keep on increasing it.
However, with Kokkos, I changed the hbond_cutoff to 7.5 (and no change to HMINBONDS since @stanmoore1 says it is useless), and it still doesn't work at pressure like 1,000 atm.

Thanks for your help !

**Comment by akohlmey** [comment] 2020-05-02 03:30
FYI. Just submitted a pull request that makes MIN_HBONDS a parameter that can be chose at runtime, same as MIN_CAP.

**Closed** 2020-05-04 14:28 UTC
Labels: bug, unconfirmed
