### ISSUE TITLE
Lammps Python Object

### ISSUE THREAD

**Issue by moradza** [lammps/lammps#1821] opened 2019-12-28 23:07 UTC
**Summary**
I am using lammps pair_python.cpp and pair_python.h to calculate forces from positon but my python code calculates the force vector instead norm of force vector, (py_compute_args includes delr and rsq). I want to modify few lines in the pair_pyathon.cpp for my own usage. Any suggestion on how to get back a vector instead of a double.

        py_value= PyObject_CallObject(py_compute_force,py_compute_args);
        if (!py_value) {
          PyErr_Print();
          PyErr_Clear();
          PyGILState_Release(gstate);
          error->all(FLERR,"Calling 'compute_force' function failed");
        }
        fpair = factor_lj*PyFloat_AsDouble(py_value); // py_value generated by python is 3dimensional
        Py_DECREF(py_value);

        f[i][0] += fpair[0];
        f[i][1] += fpair[1];
        f[i][2] += fpair[2];

Is it the right way to do this?

_Please provide a clear and concise description of what this issue report is about._

**LAMMPS Version and Platform**

_Please specify precisely which LAMMPS version this issue was detected with (the first line of the output) and what platform (operating system and its version, hardware) you are running on. If possible, test with the most recent LAMMPS patch version_

**Details**

_Please explain the issue in detail here_

**Comment by akohlmey** [comment] 2019-12-28 23:50
Short answer:

No

Long answer:

a) This is more a question about programming the Python/C interface and not LAMMPS, thus you 
should consult the corresponding Python C API documentation. I don't know the details of how to do this by heart and would also have to look it up myself.

b) your modified code segment:
```
fpair = factor_lj*PyFloat_AsDouble(py_value); // py_value generated by python is 3dimensional
    Py_DECREF(py_value);

    f[i][0] += fpair[0];
    f[i][1] += fpair[1];
    f[i][2] += fpair[2];
```
makes no sense and is showing several misconceptions about C/C++ programming:
 - your fpair variable is not 3-dimensional, but 1-dimensional (but of length 3). I assume you have changed its declaration, as in the python pair style it is declared as 0-dimensional, i.e. a scalar. If not, the code cannot compile and would exit with a syntax error. However, since you didn't change the way how the argument is returned from python, it **cannot** work.
 - C/C++ does not allow scalar operations on arrays like you are doing. arrays are effectively pointers and not variables with values.
 - Python has no direct equivalent data type to C/C++ arrays (there are custom compatible data types in the ctypes and numpy Python modules). In plain Python however you would have a tuple as data type (or a hash). So you would have to do some kind of conversion by iterating the tuple and copying the individual items to their corresponding data storage. Again, this should be explained in the documentation of the Python C API.

c) There are more open questions about code that is not shown but only referenced to (e.g. what is `delr`, what does it represent, and what data type is it and how is it encoded) and how you can compute a force vector from the potential and what appears to be two scalars.

d) This kind of question is not really a good match with an issue tracker (as it is not really a LAMMPS issue and not about LAMMPS documentation or specific LAMMPS features but rather about you wanting to modify something that was not designed to be modified without sufficient expertise in the corresponding non-LAMMPS APIs and the respective programming languages). You may be better off discussing this on the lammps-users mailing list, but your chances to get more information than what is included in this message are slim.

One final remark: pair style python is very, very slow due to the very inefficient way how python operates and the fact, that you have to enter the python interpreter for every pair of atoms. This pair style was designed to quickly prototyping pairwise additive potentials and then writing them to tables with the `pair_write` command, which will result in quite acceptable performance.

**Comment by moradza** [comment] 2019-12-29 00:25
Thanks Axel! 
I didn't put the whole code here, it is the part that I am struggling with it. I will look up to the Python C API for further information. Here is the part I didn't show above, ( I will open a new discussion on the lammps-user mailing list).

double delr[3];
int i, j ;// i and j are atom i and  j 
delr[0] = x[j][0] - x[i][0]
delr[1] = x[j][1] - x[j][1]
delr[2] = x[j][2] - x[j][2]

I read the lammps documentation for the pair python and I am aware of severe slow down due to python interoperator.  And in fact, I am prototyping couples of many-body potential in lammps.

The problem that I am working is actually extending pair python to support three-body potential in the form of python code. I am not sure about lammps supporting table form for the threebody potential.

**Comment by akohlmey** [comment] 2019-12-29 00:46
What you are describing now makes even less sense. The whole structure of the C++ part of pair style python is laid out for pairwise additive potentials. For most manybody potentials you need to request a different kind of neighbor list and - depending on the specific nature of the many-body component - processes this neighbor list into "short" neighbor lists for efficiently looping over 3-body and - in some cases - 4-body interactions. This cannot be easily generalized and would be very different. Pair style python was effectively designed to be similar to a pair style that would call the Pair::single() method in its innermost loop and then replace this call with calls to two python functions in a given derived class. For a many-body python pair style you would have to pretty much start from scratch and begin with a suitable pair style from the MANYBODY package as a template and then insert the call-outs to the Python interpreter accordingly.
Yes, there is no generic tabulation for manybody potentials as it has similar issues as I just outlined for implementing a python manybody prototype. There are, however, optimized versions of some manybody potentials that use tabulation internally and some have their parameters already tabulated as spline function parameters.

It seems to me, that they effort to implement a many-body pair style prototyping in python would be significantly more effort than doing the "prototyping" (i.e. development) in C++ directly and similarly not easily generalized as manybody interactions are not as general across different pair styles as pairwise additive potentials.

I am closing this issue now, as it has become now fully off-topic.

**Closed by akohlmey** 2019-12-29 00:46 UTC
