### ISSUE TITLE
Total energy changes when using the old version or the new version of LAMMPS

### ISSUE THREAD

**Issue by PrathapjharaplaUOS** [lammps/lammps#3940] opened 2023-10-16 02:36 UTC
**Summary**

The total energy changes when using the old version or the new version of LAMMPS under the same conditions and with the same input files.

Two example energies are given as:
Old version: -83995.3477715 
New version: -45411617.9792768

The energy from the new version seems meaningless to me, unlike the one from the old version, when comparing with typical per/atom energies.

The reason for this PR is to troubleshoot a subsequent surprising behavior related to this. Indeed, when using box/relax to include cell relaxation, I observe that when doing continuation runs from the final relaxed structure using the older version, the energy gradually keeps decreasing (as expected), while with the newer version, the energy jumps around, and the final energy after the first continuation run is different from the first energy for the second continuation, while it would be expected that they are the same. 

I can also upload the scripts related to this box/relax behavior if necessary, but I imagine that troubleshooting why energies between different version change beyond just numerical precision should already give sufficient indication of what is happening.

**LAMMPS Version and Platform**
LAMMPS (3 Mar 2020)

LAMMPS (2 Aug 2023 - Update 1)

what platform (operating system and its version, hardware) you are running on. If possible, test with the most recent LAMMPS patch version-->

**Expected Behavior**

When executing the provided input, it is expected that the total energies should remain consistent regardless of the version being used.

**Actual Behavior**

When running the given input, we observe variations in the total energies across different versions of LAMMPS.

**Steps to Reproduce**

lmp -in test.in to run the executable in 20version folder, on using the LAMMPS (3 Mar 2020)

lmp -in test.in to run the executable in 23version folder, on using the LAMMPS 2 Aug 2023 - Update 1

**Further Information, Files, and Links**

The log.lammps has been attached for reference . 

[Report.zip](https://github.com/lammps/lammps/files/12911509/Report.zip)

**Comment by akohlmey** [comment] 2023-10-16 03:41
@PrathapjharaplaUOS Thanks for your report. This is indeed a manifestation of a bug. It is due to a recently added feature to optimize neighbor lists with hybrid pair styles. This bug can be avoided by adding `pair_modify neigh/trim no` which disables this optimization.

**Comment by stanmoore1** [comment] 2023-10-16 15:28
I'm debugging now.

**Comment by stanmoore1** [comment] 2023-10-16 17:23
@PrathapjharaplaUOS this should be fixed by #3941, can you confirm?

**Comment by akohlmey** [comment] 2023-10-16 18:03
@stanmoore1 I can confirm that #3941 addresses the issue and all valgrind errors about invalid memory accesses are gone. I've reverted the workaround for REBO/AIREBO before testing, too.

**Comment by stanmoore1** [comment] 2023-10-16 18:04
Great, thanks @akohlmey!

**Closed as completed** 2023-10-16 19:49 UTC
Labels: bug

**Comment by PrathapjharaplaUOS** [comment] 2023-10-16 23:55
Thank you for your help and clarification; even the 'box/relax' method works.
