### ISSUE TITLE
[BUG] Possible memory leak with GPU package

### ISSUE THREAD

**Issue by Loki98** [lammps/lammps#2953] opened 2021-09-22 06:20 UTC
**Summary**

Continuous increase in system memory ( memory leak) with space calculations with GPU acceleration

**LAMMPS Version and Platform**

LAMMPS-29Oct20- build with MPI and GPU acceleration 
GPU - Nvidia Geforce RTX 3070

**Expected Behavior**

Expected a constant use of allocated system memory during a simulation run with GPU acceleration.
**Actual Behavior**

Getting a gradual increase in system memory usage, ultimately the system terminates the program, and freeze the system itself. 

**Steps to Reproduce**
Could be reproduced with lj pair potentials followed with kspace PPPM calculation, with GPU acceleration.
command used: mpirun -n 2 lmp -sf gpu -pk gpu 1 -in file.in

However if I use GPU acceleration with pair potential calculations only , omitting GPU acceleration for kspace calculation, the system memory consumption stays constant throughout the simulation.

**Further Information, Files, and Links**

**Comment by akohlmey** [comment] 2021-09-22 10:32
@Loki98 Thanks for your report. Unfortunately, the information your provide is too vague and unspecific in order to investigate further. Furthermore, if we will be making any changes, it will be to the development version of LAMMPS, and not to the stable version. Thus please do the following:
- Get the 20 September 2021 version of LAMMPS and repeat your tests. We have been fixing bugs and memory leaks (including a couple in the pppm/gpu kspace style) since the stable release, so your problem may already been solved
- In case you are still observing a memory leak with the latest development version of LAMMPS please report the following:
   - A detailed description of how you configured and compiler your LAMMPS binary including names and versions of compilers and libraries (most info can be copied from the output of `./lmp -h`).
   - Specific details and information about your operating system, version, drivers etc. When compiling the GPU package for CUDA the output of nvc_get_devices, when for OpenCL the output of ocl_get_devices
   - A detailed description of how to observe and reproduce the memory leakage based on an input example from the LAMMPS distribution, e.g. the in.rhodo example from the bench folder. If you need to modify the input, please attach the modified version here
- While testing, you may also consider running with the KOKKOS package compiled for CUDA instead.

**Comment by akohlmey** [comment] 2021-09-28 03:19
@Loki98 Do you have any updates on this issue?

**Comment by akohlmey** [comment] 2021-10-04 19:23
@Loki98 This has gone now for nearly two weeks without any response from you to the suggestions and questions. We cannot take any action without more information or being able to reproduce the issue that you are seeing. Thus I will close this now. Please reopen or resubmit when you have the required additional information.

**Closed by akohlmey** 2021-10-04 19:23 UTC
Labels: bug, unconfirmed
