### ISSUE TITLE
[BUG] ReaxFF + Kokkos + NPH/NPT problem

### ISSUE THREAD

**Issue by weichafan** [lammps/lammps#3535] opened 2022-11-23 22:33 UTC
**Summary**

Simulations of ReaxFF + Kokkos present problems when performing simulations with NPH or NPT. Even when using independent temperature control when there is an expansion of the box due to melting, the system temperature also jumps. The script works fine without kokkos.

**LAMMPS Version and Platform**

Lammps version 3Nov22, OS: Pop!_OS 22.04  
KOKKOS_ARCH = Volta70 
AMD Ryzen Threadripper 3970X 32-Core Processor

**Expected Behavior and Actual Behavior**

Using the same input file (except minor modifications between EAM and ReaxFF as units) I ran NPH + Langevin Thermostat simulations to model the iron melting point (In other simulations I used NPT with equivalent results).

In the simulation, I heat the system up to 1500 K in a few steps and then I heat it more slowly. When the system melts, an abrupt increase in the box volume is observed. At the same time, the temperature increases linearly. This happens with EAM+Kokkos without problems. However, for ReaxFF + Kokkos, once an abrupt rise in the case occurs, there is also an abrupt jump in temperature that should not occur. When running the same script for ReaxFF without kokkos (usual mpirun), no melting is observed in the tested window, only linear expansion of the volume. The temperature evolution is similar to what happened with EAM (black and blue lines overlapped in the plot)

The graph shows what happened.

![Volandtemp](https://user-images.githubusercontent.com/77077102/203656425-a9ab0c3d-3b57-47f3-9789-44cdeb1ef8ef.png)

**Steps to Reproduce**

Attached are 3 folders with the input scripts and the log.lammps files 

commands: 

EAM + Kokkos /ReaxFF +Kokkos

lmp  -k on g 1 -sf kk -pk kokkos newton on neigh half -in in.melting

ReaxFF (usual mpirun)

mpirun -np 32 lmp -in in.melting 

**Further Information, Files, and Links**
[Test-ReaxFF-EAM-Kokkos.zip](https://github.com/lammps/lammps/files/10079501/Test-ReaxFF-EAM-Kokkos.zip)

**Comment by stanmoore1** [comment] 2022-11-23 23:13
@weichafan thanks I will try to reproduce this issue.

**Comment by stanmoore1** [comment] 2022-11-23 23:34
@weichafan I can reproduce this issue. I see a jump from 2107 K to 4158 K and a similar jump in volume. Will debug.

**Comment by weichafan** [comment] 2022-11-23 23:38
Thanks a lot @stanmoore1 . Nice to hear that it was able to be reproduced. I always worry that I did something wrong.

**Comment by stanmoore1** [comment] 2022-11-23 23:47
Just FYI, you can reduce the overhead a little in the heating loop with `pre no post no`

```
run 2000 pre no post no
```

**Comment by stanmoore1** [comment] 2022-11-23 23:50
Actually I think that you need `pre yes`

**Comment by weichafan** [comment] 2022-11-23 23:53
Great! I didn't know these great keywords. Using lammps for 10 years or so and it is the first time I read about these keywords. Thanks a lot. 

In lammps manual for RUN command : 

By default (pre and post = yes), LAMMPS creates neighbor lists, computes forces, and imposes fix constraints before every run. And after every run it gathers and prints timings statistics. If a run is just a continuation of a previous run (i.e. no settings are changed), the initial computation is not necessary; the old neighbor list is still valid as are the forces. So if pre is specified as “no” then the initial setup is skipped, except for printing thermodynamic info. Note that if pre is set to “no” for the very first run LAMMPS performs, then it is overridden, since the initial setup computations must be done.

**Comment by stanmoore1** [comment] 2022-11-23 23:57
Yes, you can only set `post no` since you are changing the temperaure.

**Comment by stanmoore1** [comment] 2022-11-24 00:37
I wrote a restart file just before it crashes and then read it back in for debugging. No crash with UVM enabled or Kokkos Serial backed. Looks like a missing sync/modify for transferring between CPU and GPU memory, but it is a little tricky since it isn't 100% deterministic with fix langevin. For example if I change the number of MPI ranks it doesn't fail in 2000 steps either.

**Comment by weichafan** [comment] 2022-11-24 01:19
I obtained similar and weird results using the "fix NPT" directly. At that moment I supposed was a problem related to the integration of the movement equations (Probably mixing simulation box and coordinates). Using fix NPT I observed the same problem, that is, after a box expansion, there is a jump in temperature (600-700 K)  that then does not return to the fixed target temperature.

Then I tried to use NPH and a thermostat apart. I tried Berendsen and Langevin. To inform the problem I did the simulations using NPH + Langevin.

Finally, I did the test with EAM and realized it is related to ReaxFF somehow.

In my case, the simulations never crash.

**Comment by weichafan** [comment] 2022-11-24 01:27
Attached are 2 other simulations I did use ReaxFF + Kokkos

In one case I used  "fix NPT" and in another, I used "fix NPH"  + "fix temp/Berendesen"


[Test-ReaxFF-Kokkos-NPTandNPH.zip](https://github.com/lammps/lammps/files/10080133/Test-ReaxFF-Kokkos-NPTandNPH.zip)
I

**Comment by stanmoore1** [comment] 2022-11-29 16:25
@weichafan this should be fixed by #3541, can you confirm? Thanks for reporting the bug and providing an example input.

**Closed as completed** 2022-11-29 19:56 UTC
Labels: bug, user_reaxc_package, kokkos_package

**Comment by weichafan** [comment] 2022-12-01 18:56
Thanks a lot, @stanmoore1, yesterday I tried it, and it worked perfectly. Thanks.
