### ISSUE TITLE
erroneous molecule topology overflow error take 2

### ISSUE THREAD

**Issue by jrgissing** [lammps/lammps#608] opened 2017-08-09 05:11 UTC
## Summary

erroneous molecule topology overflow error

## Type of Issue

Bug Report

## Detailed Description (Enhancement Suggestion)

add this block to the end of Molecule::special_generate()

  maxspecial = 0;
  for (int i = 0; i < natoms; i++)
      maxspecial = MAX(maxspecial,nspecial[i][2]);

## LAMMPS Version (Bug Report)

latest

## Expected Behavior (Bug Report)

no erroneous molecule topology overflow

## Actual Behavior (Bug Report)

doesn't update maxspecial to molecule's actual maxspecial during second pass through read(), so erroneously remains at the temporarily assigned value. observed when reading in a data file and subsequently adding atoms

## Steps to Reproduce (Bug Report)

if still not convinced, can send example

## Further Information, Files, and Links

_Put any additional information here, attach relevant text or image files and URLs to external sites, e.g. relevant publications_

**Comment by akohlmey** [comment] 2017-08-09 10:52
@jrgissing thanks for the report, but it looks like we need a take 3.
1) version "latest" is useless, as it is a moving target and different people have different interpretation of "latest". since we introduced "stable" release versions, many people consider the latest stable version as "latest", others consider whatever is provided in their ubuntu, suse, red hat, fedora etc. repository as latest. so please always mention the version that LAMMPS prints.
2) a bug report without a (preferably small/short/fast) demonstration to reproduce the erroneous behavior is no bug report. please keep in mind, that this input could also be adapted to become part of the regressions test library, to make certain a verified bug does not return.
3) if you have a proposed change, please consider submitting this as a pull request instead (technically, a pull request is essentially an issue with a branch containing proposed changes attached).

**Comment by jrgissing** [comment] 2017-08-10 00:30
here is (slightly redundant but valid) example which should break it

[infromdata.lammps.txt](https://github.com/lammps/lammps/files/1213291/infromdata.lammps.txt)
[acid,6-6.molecule_template.txt](https://github.com/lammps/lammps/files/1213294/acid.6-6.molecule_template.txt)
[amine,6-6.molecule_template.txt](https://github.com/lammps/lammps/files/1213293/amine.6-6.molecule_template.txt)
[tiny_nylon.data.txt](https://github.com/lammps/lammps/files/1213295/tiny_nylon.data.txt)

**Comment by akohlmey** [comment] 2017-08-10 11:30
@jrgissing thanks. i can reproduce the problem, but i disagree with your approach to address this. The real problem lies in `Special::combine()` of special.cpp and it should be addressed in commit ce62c41252f61751a65a56b8ded8f0a93fd3441d

BTW: the `special_bonds extra 49` line in your input deck is contributing to the issue and the failure would be avoided by simply commenting that line out. it is redundant and conflicting with the 50 extra special neighbor entries in your read_data command.

**Closed** 2017-08-10 14:02 UTC

**Comment by jrgissing** [comment] 2017-08-10 15:40
thanks, i agree with that. technically i would still also support the change mentioned above for the sake of self-consistency in molecule.cpp, and the fact that it remains storing the wrong maxspecial for the molecule (even though erring on the safe side)

**Comment by akohlmey** [comment] 2017-08-10 18:40
it is not really the _wrong_ maxspecial. maxspecial is how much storage is allocated for special neighbors per atom. when auto-generating this list, this number cannot be known beforehand (you would have to add another pass at reading/processing the topology data), so that is why the global value is used instead.

**Comment by jrgissing** [comment] 2017-08-10 19:00
good point. or simply use a dummy array sized atom->maxspecial and allocate/assign the molecule's special lists at the end of special_generate

can take a crack at it if interested

**Comment by akohlmey** [comment] 2017-08-10 19:24
yes, this could be done, but i don't see a significant benefit from it. after all, this is just the molecule _template_ (so conserving memory is not a big concern) and the purpose is to ensure, that neither the data in the molecule file nor the molecule templates overflow the global setting. The global setting is what matters. This is achieved with the current code already. To avoid further inconsistencies, we'll remove the special_bonds extra option.

If you still like to propose additional changes and plan to work on it right away, please start from and submit them to this branch in my LAMMPS fork: https://github.com/akohlmey/lammps/tree/collected-small-changes

While reviewing your issue, i noticed that there were too few checks on the molecule file format and no parsing errors flagged, so i just implemented that today (and also implemented removing the extra keyword from special_bonds).  if you want to avoid merge conflicts with your additional changes, it is safer to start from these variants (or wait until this "meta branch" is merged to the first patch release after the pending stable version).

**Comment by jrgissing** [comment] 2017-08-10 19:39
sounds good, will push to new molecule.cpp when merged
