### ISSUE TITLE
[BUG] GPU package compiled with CUDA fails

### ISSUE THREAD

**Issue by charlessievers** [lammps/lammps#2740] opened 2021-04-27 23:10 UTC
**Summary**

Compiling and trying to run with the GPU package on NVIDIA drivers v440.100 either with CUDA 10.2 fails.

**LAMMPS Version and Platform**

current master, ubuntu 18.04, Intel(R) Core(TM) i9-9920X CPU @ 3.50GHz, GeForce 2080 Ti

**Expected Behavior**

```
 $ cd examples/melt 
 $ ../../build/lmp -in in.melt -sf gpu 
```

This should run and complete without error

**Actual Behavior**

```
$ ../../build/lmp -in in.melt -sf gpu 
LAMMPS (8 Apr 2021)
OMP_NUM_THREADS environment is not set. Defaulting to 1 thread. (src/comm.cpp:94)
  using 1 OpenMP thread(s) per MPI task
Lattice spacing in x,y,z = 1.6795962 1.6795962 1.6795962
Created orthogonal box = (0.0000000 0.0000000 0.0000000) to (16.795962 16.795962 16.795962)
  1 by 1 by 1 MPI processor grid
Created 4000 atoms
  create_atoms CPU = 0.000 seconds

CITE-CITE-CITE-CITE-CITE-CITE-CITE-CITE-CITE-CITE-CITE-CITE-CITE

Your simulation uses code contributions which should be cited:
- GPU package (short-range, long-range and three-body potentials):
The log file lists these citations in BibTeX format.

CITE-CITE-CITE-CITE-CITE-CITE-CITE-CITE-CITE-CITE-CITE-CITE-CITE


--------------------------------------------------------------------------
- Using acceleration for lj/cut:
-  with 1 proc(s) per device.
-  Horizontal vector operations: ENABLED
-  Shared memory system: No
--------------------------------------------------------------------------
Device 0: GeForce RTX 2080 Ti, 68 CUs, 11/11 GB, 1.5 GHZ (Mixed Precision)
--------------------------------------------------------------------------

Initializing Device and compiling on process 0...Done.
Initializing Device 0 on core 0...Done.

Setting up Verlet run ...
  Unit style    : lj
  Current step  : 0
  Time step     : 0.005
Cuda driver error 1 in call at file '/xxxx/xxxxxxxx/lammps/lib/gpu/geryon/nvd_kernel.h' in line 379.
--------------------------------------------------------------------------
MPI_ABORT was invoked on rank 0 in communicator MPI_COMM_WORLD
with errorcode -1.

NOTE: invoking MPI_ABORT causes Open MPI to kill all MPI processes.
You may or may not see output from other processes, depending on
exactly when Open MPI kills them.
--------------------------------------------------------------------------
```

**Steps to Reproduce**

```
mkdir build
cd build
cmake -C ../cmake/presets/minimal.cmake -D PKG_GPU=on -D GPU_API=cuda ../cmake
make
cd ../examples/melt
../../build/lmp -in in.melt -sf gpu
```

**Further Information, Files, and Links**

**Comment by weinbe2** [comment] 2021-04-27 23:54
Can you please see if this occurs with the `patch_10Feb2021` release?

**Comment by charlessievers** [comment] 2021-04-28 01:34
Hey @weinbe2, it sure does.

**Comment by rbberger** [comment] 2021-04-28 03:56
Confirmed on a Ubuntu 18.04 container with CUDA 10.2 on v465.19.01 (CUDA 11.3 driver) driver. And yet again, it works with
```bash
../../build/lmp -in in.melt -sf gpu -pk gpu 0 neigh no
```

**Comment by charlessievers** [comment] 2021-04-28 04:09
Why does it work with a neighbor list build on the cpus instead of the gpus?

**Comment by ndtrung81** [comment] 2021-04-28 16:46
@charlessievers can you also try build with -DCUDPP_OPT=ON, and run it again with "neigh yes" (i.e. without "neigh no")? Also for debugging purposes, does the run crash with GPU_API=opencl with either "neigh no" or "neigh yes"?

**Comment by charlessievers** [comment] 2021-04-28 19:06
@ndtrung81 Failed with ` -DCUDPP_OPT=ON, and run it again with "neigh yes"`
I was not able to build with `GPU_API=opencl `

**Comment by weinbe2** [comment] 2021-04-29 17:11
I figured out the issue---this one's sneaky.

In https://github.com/lammps/lammps/blob/master/lib/gpu/lal_neighbor_gpu.cu , there are two versions of the function `calc_neigh_list_cell` 
* Line 160, one with 23 arguments, compiled when `LAL_USE_OLD_NEIGHBOR` is _not_ defined
* Line 352, one with 16 arguments, compiled when it is defined.

When the `lal_neighbor_gpu.cu` `cubin` is compiled when you build libgpu, it uses this logic at the top of the file:
```
#ifdef NV_KERNEL
#if (__CUDACC_VER_MAJOR__ == 11) && (__CUDACC_VER_MINOR__ >= 2)
// Issue with incorrect results in CUDA >= 11.2
#define LAL_USE_OLD_NEIGHBOR
#endif
#endif
```

So, in @charlessievers case with CUDA 10.2, `LAL_USE_OLD_NEIGHBOR` is _not_ defined, so it's compiling the 23 argument version.

Now, at run time, `LAL_USE_OLD_NEIGHBOR` is defined based on what's in https://github.com/lammps/lammps/blob/master/lib/gpu/geryon/nvd_device.h , which is different: it's just always defining `LAL_USE_OLD_NEIGHBOR` when you're running on NVIDIA devices. This means it tries to launch the 16 argument version, which I've confirmed with some good old-fashioned printf debugging, inserting a print here: https://github.com/lammps/lammps/blob/master/lib/gpu/geryon/ucl_arg_kludge.h#L551

This means, at runtime, we're inferring we should use the 16 argument version of `calc_neigh_list_cell`, correctly build a list of 16 arguments, but then we pass that to the 23 argument version of `calc_neigh_list_cell` in the `cubin`. That's why you're getting driver error 1, for an invalid launch configuration.

There are a few different ways to fix this. One is to just reconcile the conditionals in `lal_neighbor_gpu.cu` and `geryon/nvd_device.h` --- I've verified this works, but it's arguably messy.

As a **cleaner, more robust solution,** I recommend giving the two versions of `calc_neigh_list_cell` in `lal_neighbor_gpu.cu` _two different names_ and always compile both of them. Then, at run time, you can figure out which kernel to launch. In my opinion this is the cleanest way forward---I think it's asking for trouble to have two kernels with the same name toggled by compiler defines.

Could someone more familiar with the kernel compile/launch plumbing of libgpu please give this a whirl?

**Comment by ndtrung81** [comment] 2021-04-29 18:35
@weinbe2 thanks for pointing out the cause of the issue. 

If I recall correctly, the change in geryon/nvd_device.h was made by @akohlmey as a workaround for a bug with neigh yes on CUDA builds at the time (dated 3/11/21), similar to HIP builds (geryon/hip_device.h) by @rbberger (dated 2/23/21). Later, @wmbrownIntel found and fixed an issue related to "neigh yes" (although originally tied with -DCUDPP used for neighbor list sorting) in lal_neighbor.cpp (dated 3/31/21). Now when I comment out #define LAL_USE_OLD_NEIGHBOR in geryon/nvd_device.h:29, the issue is resolved in my test run (with CUDA 9.2). I expect this simple fix would work for CUDA 10.x as well.

**Comment by rbberger** [comment] 2021-04-29 23:33
@ndtrung81 the issue seems to be that unlike OpenCL, the "workaround" didn't fully propagate to the kernels, because unlike OpenCL the compilation flags aren't passed at runtime, but at compile time. Reverting both a28d9a6e69d7f44414401412519259eebd04371e  and d405f2ec4b5faa4db404132be08e09df4a0b0422 puts everything back into place.

CUDA 10.2 - melt works
CUDA 11.2 - melt works
CUDA 11.3 - melt works

For HIP, I'm expecting the same problem. So my original workaround was likely flawed in the first place.

**Comment by rbberger** [comment] 2021-04-29 23:48
ugh... on my second system (driver 465.24.02, CUDA 11.3)
I get this with the two reverts:
```
ERROR: Lost atoms: original 4000 current 3918 (src/thermo.cpp:425)
Last command: run		250
Cuda driver error 4 in call at file '/home/richard/GitHub/lammps/lammps/lib/gpu/geryon/nvd_timer.h' in line 98.
Cuda driver error 4 in call at file '/home/richard/GitHub/lammps/lammps/lib/gpu/geryon/nvd_timer.h' in line 99.
Cuda driver error 4 in call at file '/home/richard/GitHub/lammps/lammps/lib/gpu/geryon/nvd_timer.h' in line 98.
Cuda driver error 4 in call at file '/home/richard/GitHub/lammps/lammps/lib/gpu/geryon/nvd_timer.h' in line 99.
Cuda driver error 4 in call at file '/home/richard/GitHub/lammps/lammps/lib/gpu/geryon/nvd_timer.h' in line 98.
Cuda driver error 4 in call at file '/home/richard/GitHub/lammps/lammps/lib/gpu/geryon/nvd_timer.h' in line 99.
Cuda driver error 4 in call at file '/home/richard/GitHub/lammps/lammps/lib/gpu/geryon/nvd_timer.h' in line 98.
Cuda driver error 4 in call at file '/home/richard/GitHub/lammps/lammps/lib/gpu/geryon/nvd_timer.h' in line 99.
Cuda driver error 4 in call at file '/home/richard/GitHub/lammps/lammps/lib/gpu/geryon/nvd_timer.h' in line 98.
Cuda driver error 4 in call at file '/home/richard/GitHub/lammps/lammps/lib/gpu/geryon/nvd_timer.h' in line 99.
Cuda driver error 4 in call at file '/home/richard/GitHub/lammps/lammps/lib/gpu/geryon/nvd_timer.h' in line 98.
Cuda driver error 4 in call at file '/home/richard/GitHub/lammps/lammps/lib/gpu/geryon/nvd_timer.h' in line 99.
Cuda driver error 4 in call at file '/home/richard/GitHub/lammps/lammps/lib/gpu/geryon/nvd_timer.h' in line 98.
Cuda driver error 4 in call at file '/home/richard/GitHub/lammps/lammps/lib/gpu/geryon/nvd_timer.h' in line 99.
```

**Comment by rbberger** [comment] 2021-04-30 00:18
@ndtrung81 Nope, was celebrating too soon. CUDA 11.3 fails on both drivers with both commits reverted. My initial CUDA 11.3 test was actually using 11.0.

**Comment by rbberger** [comment] 2021-04-30 00:42
To summarize: to resolve this issue only https://github.com/lammps/lammps/commit/a28d9a6e69d7f44414401412519259eebd04371e needs to be reverted. 

CUDA 10.2 - melt works (can use new neighbor)
CUDA 11.2 - melt works (old neighbor)
CUDA 11.3 - melt work (old neighbor)

The new neighbor code continues to fail on CUDA >= 11.2

**Closed** 2021-04-30 23:32 UTC
Labels: bug, gpu_package
