### ISSUE TITLE
Bond adapt bug

### ISSUE THREAD

**Issue by alessiodavidgit** [lammps/lammps#992] opened 2018-07-11 09:28 UTC
## Summary

Confusion between atom type and bond type

## Type of Issue

Bug Report

## Detailed Description (Enhancement Suggestion)

Lammps complains about index being out of bounds. The bounds it considers is max number of atom types instead of bond types.
I am quite sure the fix acts as expected, because it acts on the right bond type. The only problem is this error message.
At the moment I have solved the issue by adding spurious atom types to reach the index of the bond type to adapt.

**Comment by akohlmey** [comment] 2018-07-11 10:16
@alessiodavidgit why did you erase most of the issue report template and particularly not provide the important and required data for bug reports, like the exact LAMMPS version you are using, or how to exactly reproduce it? instead you are filling in data for a feature request. You are just causing needless effort and confusion. If I had not remembered integrating the fix for this issue, i might have spent a lot of time trying to fix an issue, that doesn't exist in the current LAMMPS code anymore, since it was already reported (and fixed) in #931. Please upgrade your LAMMPS version to the most recent patch.

**Closed by akohlmey** 2018-07-11 10:16 UTC
Labels: duplicate

**Comment by alessiodavidgit** [comment] 2018-07-11 12:05
it is 13 Mar 2018 version.
