### ISSUE TITLE
[BUG] _Python Package_

### ISSUE THREAD

**Issue by finkeljos** [lammps/lammps#2588] opened 2021-02-08 19:25 UTC
**Summary**

The LAMMPS Python package does not appear to update atoms positions or velocities when invoking the python/move fix when running the in.fix_python_move_nve_melt example provided in the ~/lammps/examples/python folder

**LAMMPS Version and Platform**

I am running in my local cluster environment which uses CentOS 7 and using the current master branch for LAMMPS.

**Expected Behavior**

I expect to see a typical MD simulation thermo output.

**Actual Behavior**

No reported errors from LAMMPS but the kinetic energy remains fixed for length of the example simulation and atoms do not appear to move.

**Steps to Reproduce**

I executed the following shell commands in this order

1. git clone
2. cd ~/lammps/src
3. make yes-python
4. make mode=shared serial -j
5. make install-python
6. export PYTHONPATH=${PYTHONPATH}:${HOME}/lammps/python
7. export LD_LIBRARY_PATH=${LD_LIBRARY_PATH}:${HOME}/lammps/src
8. cd ~/lammps/examples/python/
9. ~/lammps/src/lmp_serial < in.fix_python_move_nve_melt

**Comment by giacomofiorin** [comment] 2021-02-08 19:47
@rbberger To complete what Josh has reported so far, I built LAMMPS (both `master` and `stable_29Oct2020`) on a different machine also CentOS 7, with Python 3.6 detected from CMake and `-DPYTHON=on`.

I was able to build LAMMPS fine, but with the same example I got:
```
AttributeError: .../build/lammps/stable_29Oct2020/bin/lmp: undefined symbol: lammps_extract_setting
```

**Comment by rbberger** [comment] 2021-02-08 23:00
@finkeljos please attach a log output

**Comment by rbberger** [comment] 2021-02-08 23:00
@giacomofiorin you sure you're loading the correct .so file?

**Comment by finkeljos** [comment] 2021-02-08 23:11
@rbberger Here is the log output I get
[fix_py_move.log](https://github.com/lammps/lammps/files/5947372/fix_py_move.log)

**Comment by rbberger** [comment] 2021-02-08 23:22
@finkeljos Which version of python are you running? Also, doing both `make install-python` and setting `PYTHONPATH` and `LD_LIBRARY_PATH` at the same time is a bit weird. The first copies the python package in your user installation (`$HOME/.local/lib/pythonX.Y/site-packages/` by default), which should be automatically visible in your python installation and the latter points back to the compilation of the source folder.

**Comment by finkeljos** [comment] 2021-02-08 23:29
@rbberger I have the anaconda module loaded on my node, it's using Python 3.7.4.

Ok, perhaps I don't need make install-python then. I noticed that if I do not export LD_LIBRARY_PATH I would get an error in LAMMPS. Thanks for the tip!

**Comment by akohlmey** [comment] 2021-02-08 23:30
to add to @rbberger 's comments. It is probably a good idea to go through the various possible folders for copies of the LAMMPS python module and shared library and clean up. Since the file layout has changed not so long ago from a single .py file plus the shared library to a folder with multiple files and the shared library, there is a good chance that some old files may be picked up.

**Comment by giacomofiorin** [comment] 2021-02-08 23:47
@rbberger Sorry, you're right. I was juggling versions while also fighting off a physical assault against my chair.

What specifically tricked me was that between 29Oct2020 and `master` the location for the Python modules changed from `$PREFIX/lib64` to `$PREFIX/lib`. The latter makes more sense, but it broke the way I was loading/unloading the installation folders into the various PATH variables.

Redoing with a clean environment gives the correct result:
```
Step Temp E_pair E_mol TotEng Press 
       0            3   -6.7733681            0   -2.2744931   -3.7033504 
      50    1.6758903   -4.7955425            0   -2.2823355     5.670064 
...
```

@finkeljos One thing you also may want to consider is giving [the CMake build system](https://lammps.sandia.gov/doc/Build_cmake.html) a try. As you will read in the doc, this way of building LAMMPS is now quite mature thanks to the work of @rbberger and your now-colleague @junghans. Among other advantages, building with CMake would avoid altogether the issues just mentioned by @akohlmey.

**Comment by giacomofiorin** [comment] 2021-02-08 23:48
(Provided that you use `-DCMAKE_INSTALL_PREFIX` onto a brand new folder and not an existing one, which would be messy.)

**Comment by junghans** [comment] 2021-02-09 00:09
@finkeljos we have lammps with python enabled pre-installed on the darwin cluster, send me an email to my LANL email for details.

**Comment by junghans** [comment] 2021-02-09 00:16
@rbberger @akohlmey maybe should generate a LAMMPSRC.bash file that sets all important environment variables when installing LAMMPS outside of system locations similar to what [VOTCA](https://github.com/votca/tools/blob/28c46bbb98a832b3ae30ad82fa7edf685a5225d1/scripts/VOTCARC.bash.in), [GROMACS](https://github.com/gromacs/gromacs/blob/84b05f96f65c7f6408b6523e5d12e1ecfe3e6b9d/scripts/GMXRC.bash.cmakein) and [ESPRESSO++](https://github.com/espressopp/espressopp/blob/05ae583ddabb47e959f867fc0b7539c6af2bd599/src/ESPRC.cmakein) does.

**Comment by junghans** [comment] 2021-02-09 00:24
And maybe we should set `SOVERSION` to the date version instead of `0`.

**Comment by rbberger** [comment] 2021-02-09 19:48
@finkeljos my guess is that due some misconfiguration, the python parts just do nothing but don't exit with an error as they should.

**Comment by giacomofiorin** [comment] 2021-02-09 20:52
@finkeljos Anaconda has little incentive to support build systems that don't rely on their tool chain. In the past I even had trouble building parallel codes because they bundled their own MPI libraries and of course, those were not integrated with the cluster scheduling system. Usually creating a custom Conda environment containing *only what you need*, and having only that environment and nothing else loaded when you build a code against it, makes things easier.

As for CMake, being new to something obviously makes things harder for anybody. But in the long run you can see for yourself that making manual edits to Makefiles will eventually create conflicts with future updates in the LAMMPS distribution. Having a CMake-based script outside of the LAMMPS repository folder would minimize that problem (eliminate is obviously impossible).

For example, you could make that script aware of which Python you have loaded at that time, and use the argument `-DPYTHON_EXECUTABLE=xxx` to specify the correct one, rather than edit the CMake files in the LAMMPS folder (which basically would mean you keep the disadvantages of the make-based system while just changing syntax!).

**Comment by rbberger** [comment] 2021-02-09 23:33
@finkeljos looks like I can reproduce the "do nothing" Python runs on CentOS7 when using Python 2.7.

**Comment by akohlmey** [comment] 2021-02-10 02:15
@finkeljos this will be resolved with the next patch release of LAMMPS. For now using Python 3.x is required. It is a **very** good idea to use that, anyway.

**Closed** 2021-02-10 17:02 UTC
Labels: bug
