### ISSUE TITLE
[Feature Request] write_data functionality for aspherical particles

### ISSUE THREAD

**Issue by ohenrich** [lammps/lammps#1815] opened 2019-12-19 14:53 UTC
**Summary**

A write data functionality for aspherical particles

**Detailed Description**

With aspherical particles it is currently only possible to create binary checkpoints through the write_restart functionality. Due to their binary nature, these restart files cannot be edited manually, which means atom types, topologies, etc cannot be changed manually during a run. A corresponding write_data functionality for aspherical particles would allow to do this.

**Comment by akohlmey** [comment] 2019-12-19 14:59
This is a duplicate of #1327 
Unfortunately, implementing write data support for this cleanly and correctly is not quite as straightforward as one might expect. This is why this is still pending.

**Closed by akohlmey** 2019-12-19 14:59 UTC
Labels: duplicate, enhancement
