### ISSUE TITLE
[BUG] LAMMPS crashes when computing the average coordination parameter

### ISSUE THREAD

**Issue by evoyiatzis** [lammps/lammps#1336] opened 2019-02-14 14:37 UTC
**Summary**

For systems less than 27 million atoms, LAMMPS computes and prints smoothly the average coordination number (combination of coord/atom & reduce ave commands) to screen & log file (using the thermo command). For larger systems, it crashes when reaching the point to perform the actual calculations.

**LAMMPS Version and Platform**

LAMMPS stable version downloaded from GitHub at 14-02-2019.

**Expected Behavior**

Printing the average coordination parameter in the log file and continuing calculations.

**Actual Behavior**

LAMMPS crushes when trying to compute the average coordination parameter.

**Steps to Reproduce**

The bug can be reproduced by using the following two LAMMPS files.

**Further Information, Files, and Links**

LAMMPS input script
[in.simulate.txt](https://github.com/lammps/lammps/files/2865392/in.simulate.txt)

LAMMPS data file in gz format
https://drive.google.com/open?id=1rILlorZMnxoQmDaG3lOk7kpT0Gfz4uh_

**Comment by akohlmey** [comment] 2019-02-14 16:07
@evoyiatzis some additional questions:
- what is the error when LAMMPS crashes? can you get a screenshot or have something useful in the logfile?
- how did you compile the executable (-DLAMMPS_SMALLBIG or -DLAMMPS_BIGBIG), which compiler, which platform etc.
- are you running in serial or in parallel? if parallel, on how many processors? and is this across multiple nodes or on a single shared memory node?
- how much RAM do you have on the machine/nodes this is running on? this is not an input that will work on machines with little RAM.

**Comment by akohlmey** [comment] 2019-02-14 17:09
@evoyiatzis i've been able to run your input successfully on a machine with 48GB RAM and 25GB swap with mpirun -np 8 and LAMMPS compiled with -DLAMMPS_BIGBIG. So you are possibly running out of memory and/or have issues with too much data per MPI rank.

```
$ mpirun -np 8 ~/compile/lammps-icms/build/lmp -in in.simulate.txt -log log.bigbig
LAMMPS (8 Feb 2019)
  using 1 OpenMP thread(s) per MPI task
Reading data file ...
  triclinic box = (0 0 0) to (1209.78 1227.6 1309.94) with tilt (7.51688e-14 -218.739 9.47154e-14)
  2 by 2 by 2 MPI processor grid
  reading atoms ...
  38198590 atoms
  reading velocities ...
  38198590 velocities
Changing box ...
38198590 atoms in group inside_sphere
636 atoms in group excessive_shell_atoms
Deleted 636 atoms, new total = 38197954
19098977 atoms in group zn_atoms
19098977 atoms in group o_atoms
35708884 atoms in group core_atoms
2489070 atoms in group shell_atoms
17854478 atoms in group zn_core
1244499 atoms in group zn_shell
17854406 atoms in group o_core
1244571 atoms in group o_shell
WARNING: No fixes defined, atoms won't move (src/verlet.cpp:55)
Neighbor list info ...
  update every 1 steps, delay 10 steps, check yes
  max neighbors/atom: 2000, page size: 100000
  master list distance cutoff = 12
  ghost atom cutoff = 12
  binsize = 6, bins = 239 205 219
  3 neighbor lists, perpetual/occasional/extra = 2 1 0
  (1) pair buck, perpetual
      attributes: half, newton on
      pair build: half/bin/newton/tri
      stencil: half/bin/3d/newton/tri
      bin: standard
  (2) pair coul/wolf, perpetual, copy from (1)
      attributes: half, newton on
      pair build: copy
      stencil: none
      bin: none
  (3) compute coord/atom, occasional
      attributes: full, newton on
      pair build: full/bin/atomonly
      stencil: full/bin/3d
      bin: standard
Setting up Verlet run ...
  Unit style    : metal
  Current step  : 0
  Time step     : 0.001
Per MPI rank memory allocation (min/avg/max) = 473.7 | 2622 | 4758 Mbytes
c_6 c_7 c_8 
           0            0            0 
Loop time of 0.0138613 on 8 procs for 0 steps with 38197954 atoms

63.4% CPU use with 8 MPI tasks x 1 OpenMP threads

MPI task timing breakdown:
Section |  min time  |  avg time  |  max time  |%varavg| %total
---------------------------------------------------------------
Pair    | 0          | 0          | 0          |   0.0 |  0.00
Neigh   | 0          | 0          | 0          |   0.0 |  0.00
Comm    | 0          | 0          | 0          |   0.0 |  0.00
Output  | 0          | 0          | 0          |   0.0 |  0.00
Modify  | 0          | 0          | 0          |   0.0 |  0.00
Other   |            | 0.01386    |            |       |100.00

Nlocal:    4.77474e+06 ave 6.92364e+06 max 2.64602e+06 min
Histogram: 2 0 2 0 0 0 0 2 0 2
Nghost:    580257 ave 710485 max 421570 min
Histogram: 2 0 2 0 0 0 0 0 0 4
Neighs:    -4.40323e+08 ave 1.27897e+09 max -2.14171e+09 min
Histogram: 4 0 0 0 0 0 0 0 2 2
FullNghs:  0 ave 0 max 0 min
Histogram: 8 0 0 0 0 0 0 0 0 0

Total # of neighbors = 4.42857e+09
Ave neighs/atom = 115.937
Neighbor list builds = 0
Dangerous builds = 0
Total wall time: 0:47:38
```

**Comment by evoyiatzis** [comment] 2019-02-15 10:21
@akohlmey  Thanks for spending your time in this issue. A few more details:
I am running LAMMPS on a single-node with roughly 125 GM RAM and 16 cores using the command mpirun -np 16 and LAMMPS has been compiled with -DLAMMPS_SMALLBIG (i.e. the default flag). The number of particles in the system is roughly 38-39 millions so it should be ok. During execution, roughly 64 GB are needed (see the attached png file). 
![memory](https://user-images.githubusercontent.com/17886402/52848048-17cb1880-310e-11e9-8d5d-390b3c785eb0.png)
What makes me think that there is a bug with the coord/atom command is that, on the same machine with the same executable, I can run the same script but with the thermo command 
"thermo_style custom pe c_3 c_4 c_5 c_31 c_32 c_33 c_34  v_atoms_in_np v_atoms_in_core v_atoms_in_shell v_zn_atoms_in_core v_zn_atoms_in_shell v_o_atoms_in_core v_o_atoms_in_shell"
and get some meaningful values (please see the attached log file [log.lammps.run.txt](https://github.com/lammps/lammps/files/2868712/log.lammps.run.txt) ) while when I use the command 
"thermo_style custom c_6 c_7 c_8" the executable crashes ( [log.lammps.fail.txt](https://github.com/lammps/lammps/files/2868726/log.lammps.fail.txt) ).

I have tried the serial version as well and the two last lines printed in the screen are "c_6 c_7 c_8" & "killed".

The compiler is g++ (GCC) 4.8.5 20150623 (Red Hat 4.8.5-16) & MPI (Open MPI) 3.0.1

A short description of the general background: I am trying to create spherical particles with varying diameter. They are created by "replicating" a small unit cell of a well-defined crystal structure and after trimming some atoms, the structure parameters on the surface and the core of the particle are calculated (please have a look at the attached excel file columns from J to P [radius_data.xlsx](https://github.com/lammps/lammps/files/2868756/radius_data.xlsx) ). The value of zero which you obtain does not really makes any sense while the values obtained for my "successful run" with the thermo command "thermo_style custom pe c_3 c_4 c_5 c_31 c_32 c_33 c_34  v_atoms_in_np v_atoms_in_core v_atoms_in_shell v_zn_atoms_in_core v_zn_atoms_in_shell v_o_atoms_in_core v_o_atoms_in_shell" do fit in the general trends. If it was the case that the initial structure is so off and all atoms are really separated by more than 3.0 A (so that the structure parameter is 0), then the rest of the parameters would also deviate significantly (plus a naive visual inspection does not hint that there is a serious problem with the initial configuration).

Thanks for reading the long message !

**Comment by akohlmey** [comment] 2019-02-15 11:43
@evoyiatzis there is very little left, that i can do for you here. I need some screen output of an actual error message, not MPI telling me, that there was an error. or even better would be a stack trace from the debugger. since i cannot reproduce the error, i cannot get that info on my own.

**Comment by akohlmey** [comment] 2019-02-28 22:14
@evoyiatzis since there has not been any update for two weeks, and I (or somebody else) have not been able to confirm this, I am closing this now. Feel free to file a new bug report, if you are able to narrow this down some more and can (more) convincingly prove, that this is indeed a LAMMPS issue and not you running out or RAM or stack space or overflowing some 32-bit counters.

**Closed by akohlmey** 2019-02-28 22:14 UTC
Labels: unconfirmed
