### ISSUE TITLE
Mention crashes with profilers?

### ISSUE THREAD

**Issue by loveshack** [lammps/lammps#1481] opened 2019-05-30 13:46 UTC
I eventually realized the crash reported in #1463 was due to the environment, with the IPM profiler LD_PRELOADed.  (That's not at all obvious from core dumps to the extent I've poked at them, and I haven't debugged the cause.) The same happens for me with mpiP, but IPM and mpiP have both worked at some stage in the past, with published results, and I haven't seen such problems profiling anything else.
I was using the x86_64 openmpi 1.10 lammps-0:20181212-4 package from Fedora EPEL; builds against MPICH 3.0.4 and openmpi 3.0.2 acted the same.  The profilers are the current development versions.

I can't find any mention of such problems in a search. I wonder whether it's worth mentioning somewhere in case others fall over it and wastes time, though it's obviously not an FAQ. If not, at least it's recorded here.

I'll see if I can debug it in a reasonable time at some stage unless someone knows the cause.

**Comment by akohlmey** [comment] 2019-05-30 15:31
Why should this be recorded here? While running LAMMPS may trigger it, there is no indication at the moment, that this is due to bad behavior of LAMMPS. If you can find evidence of it, then it should be reported here.

**Comment by loveshack** [comment] 2019-05-31 09:48
> Why should this be recorded here?

Because it could be helpful to users like me.  It would be even more
useful to know which profiler(s) will work when simple low-overhead ones
using PMPI don't; I assume you profile somehow.

> While running LAMMPS may trigger it,
> there is no indication at the moment, that this is due to bad behavior
> of LAMMPS.

Indeed, but it's anomalous in my experience, used not to happen, and is
something of an impediment to people interested in performance.  If it
was my system, I'd be interested in that, but obviously you don't agree.

**Comment by akohlmey** [comment] 2019-05-31 10:28
> Why should this be recorded here?
> Because it could be helpful to users like me. It would be even more useful to know which profiler(s) will work when simple low-overhead ones using PMPI don't; I assume you profile somehow.

but i would expect that information to be added to the documentation of the profiler, if it can be confirmed to be an issue with the specific profiler. it is already challenging to keep information about issues that are indeed caused by LAMMPS up-to-date and available and confirm, that there are no conflict between features and parts of LAMMPS. 

> While running LAMMPS may trigger it, there is no indication at the moment, that this is due to bad behavior of LAMMPS.
> Indeed, but it's anomalous in my experience, used not to happen, and is something of an impediment to people interested in performance. If it was my system, I'd be interested in that, but obviously you don't agree.

i'd be interested to have this information present with LAMMPS, if this was a common thing that LAMMPS users do. Profiling is not such a thing. Many LAMMPS users these days struggle with much more basic issues.

To me the logical place to store information of bad interactions with a specific tool or library would be that specific tool or library.  For example, look at the the KOKKOS library (of which LAMMPS bundles a copy, but it is also developed and distributed independently). Since KOKKOS makes aggressive use of modern compiler features (while the baseline code of LAMMPS avoids them for increased compatibility to machines and compilers in active use), it makes sense for that library to document which compiler/toolkit versions on what platforms have been tested successfully and are thus compatible. But that information is only included in LAMMPS because it is with the KOKKOS library, even though it applies to LAMMPS as well, when using the KOKKOS package.

That said, i am not excluding that this is an issue with LAMMPS. it could well be, that there is something not done quite right, that just doesn't show otherwise. and **then** it would prompt to try resolving it and failing that, it should be documented with LAMMPS and be an open issue here for as long as is not resolved in a satisfactory way. but for that to be the case, evidence is needed.

**Closed** 2019-06-04 20:42 UTC
Labels: bug, unconfirmed
