### ISSUE TITLE
[BUG] Inconsistent special neighs/atom in different LAMMPS versions

### ISSUE THREAD

**Issue by yafshar** [lammps/lammps#2926] opened 2021-09-08 12:00 UTC
**Summary**

The LAMMPS master branch 19e6a9e0d87b6983142f3a30e2f22f4e6e030fc8 and older patch release [patch_10Feb2021](https://github.com/lammps/lammps/releases/tag/patch_10Feb2021) end in inconsistent results for the same simulation.  

The LAMMPS master branch,
````bash
LAMMPS (31 Aug 2021)
...
Step E_vdwl E_coul
       0    245.26002    401.29479
...
Total # of neighbors = 30912
Ave neighs/atom = 322.00000
Ave special neighs/atom = 7.8854167
````

The LAMMPS patch_10Feb2021
````bash
LAMMPS (10 Feb 2021)
...
Step E_vdwl E_coul
       0    -224.7538   -2091.5851
...
Total # of neighbors = 30912
Ave neighs/atom = 322.00000
Ave special neighs/atom = 14.666667
````

It seems that the new versions of LAMMPS compute an incorrect number of special bonds which leads to incorrect E_vdwl and E_coul and also lattice parameters. 

**LAMMPS Version and Platform**

The issue is reproducible with the latest LAMMPS master branch 19e6a9e0d87b6983142f3a30e2f22f4e6e030fc8 (we also tried [patch_31Aug2021](https://github.com/lammps/lammps/releases/tag/patch_31Aug2021), and [patch_30Jul2021](https://github.com/lammps/lammps/releases/tag/patch_30Jul2021))

We experienced the same behavior on Linux (CentOS 7) as well as on macOS (Big Sur)

**Expected Behavior**

The expected behavior is the one done by patch_10Feb2021.

**Actual Behavior**

It seems that the new versions of LAMMPS compute an incorrect number of special bonds which leads to incorrect E_vdwl and E_coul and also lattice parameters. 

**Steps to Reproduce**

I attached the input script and data file to run the simulation and reproduce the same behavior.

**Further Information, Files, and Links**

[in.test.zip](https://github.com/lammps/lammps/files/7128616/in.test.zip)
[input.data.zip](https://github.com/lammps/lammps/files/7128617/input.data.zip)

**Comment by akohlmey** [comment] 2021-09-08 13:45
Sorry, I cannot reproduce this. I get (with a current version on Linux):
```
LAMMPS (31 Aug 2021)
  using 1 OpenMP thread(s) per MPI task
Reading data file ...
  orthogonal box = (-6.3210000 -5.4740000 -6.1475000) to (6.3210000 5.4740000 6.1475000)
  1 by 1 by 1 MPI processor grid
  reading atoms ...
  96 atoms
  scanning bonds ...
  6 = max bonds/atom
  scanning angles ...
  15 = max angles/atom
  scanning dihedrals ...
  48 = max dihedrals/atom
  reading bonds ...
  192 bonds
  reading angles ...
  672 angles
  reading dihedrals ...
  1920 dihedrals
Finding 1-2 1-3 1-4 neighbors ...
  special bond factors lj:    0        0        1       
  special bond factors coul:  0        0        1       
     6 = max # of 1-2 neighbors
    15 = max # of 1-3 neighbors
    16 = max # of special neighbors
  special bonds CPU = 0.000 seconds
  read_data CPU = 0.004 seconds
WARNING: No fixes defined, atoms won't move (src/verlet.cpp:55)
PPPM initialization ...
  using polynomial approximation for long-range coulomb (src/kspace.cpp:342)
  G vector (1/distance) = 0.26924546
  grid = 12 10 12
  stencil order = 5
  estimated absolute RMS force accuracy = 0.00023429715
  estimated relative force accuracy = 7.0557891e-07
  using double precision FFTW3
  3d grid and FFT values/proc = 6137 1440
Neighbor list info ...
  update every 1 steps, delay 5 steps, check yes
  max neighbors/atom: 5000, page size: 100000
  master list distance cutoff = 14
  ghost atom cutoff = 14
  binsize = 7, bins = 2 2 2
  1 neighbor lists, perpetual/occasional/extra = 1 0 0
  (1) pair lj/cut/coul/long, perpetual
      attributes: half, newton on
      pair build: half/bin/newton
      stencil: half/bin/3d
      bin: standard
Setting up Verlet run ...
  Unit style    : real
  Current step  : 0
  Time step     : 1
WARNING: Inconsistent image flags (src/domain.cpp:814)
WARNING: Bond/angle/dihedral extent > half of periodic box length (src/domain.cpp:935)
Per MPI rank memory allocation (min/avg/max) = 43.73 | 43.73 | 43.73 Mbytes
Step E_vdwl E_coul 
       0    -224.7538   -2091.5851 
WARNING: Bond/angle/dihedral extent > half of periodic box length (src/domain.cpp:935)
Loop time of 9.53674e-07 on 1 procs for 0 steps with 96 atoms

104.9% CPU use with 1 MPI tasks x 1 OpenMP threads

[...]

Total # of neighbors = 30912
Ave neighs/atom = 322.00000
Ave special neighs/atom = 14.666667
Neighbor list builds = 0
Dangerous builds = 0
Total wall time: 0:00:00
```

**Comment by akohlmey** [comment] 2021-09-08 15:15
Same thing on macOS with the following OS/Compiler settings (from `lmp -h`):
```
OS: Darwin 20.6.0 on x86_64

Compiler: Clang C++ Apple LLVM 12.0.5 (clang-1205.0.22.11) with OpenMP not enabled
C++ standard: C++11
MPI v3.1: Open MPI v4.1.1, package: Open MPI brew@BigSur Distribution, ident: 4.1.1, repo rev: v4.1.1, Apr 24, 2021
```
So it seems we need to track down what is different besides the source code.

**Comment by yafshar** [comment] 2021-09-08 15:44
On Linux, I am using `icpc (ICC) 19.0.4.243 20190416` and compiling LAMMPS with,

```bash
cmake -C ${LAMMPS_SOURCE}/cmake/presets/all_on.cmake -C ${LAMMPS_SOURCE}/cmake/presets/nolib.cmake -DPKG_KIM=ON -DPKG_PYTHON=ON -DPKG_KSPACE=ON -DPKG_MEAM=ON  -DPKG_MISC=ON  -DPKG_MANYBODY=ON -DPKG_MOLECULE=ON -DPKG_CLASS2=ON -DPKG_REAXFF=ON -DBUILD_SHARED_LIBS=ON -DCMAKE_VERBOSE_MAKEFILE=ON -DLAMMPS_INSTALL_RPATH=ON -DCMAKE_BUILD_TYPE=Release -DCMAKE_CXX_COMPILER=mpic++ -DCMAKE_C_COMPILER=mpicc -DCMAKE_Fortran_COMPILER=mpifort  -DPKG_PLUGIN=OFF ${LAMMPS_SOURCE}/cmake -DCURL_LIBRARY="$PREFIX/curl/lib64/libcurl.so" -DCURL_INCLUDE_DIR="$PREFIX/curl/include"
```

getting the reported behavior. Due to a setup mistake, I did not set the MKL root and also got the warning from CMAKE

```bash
CMake Warning at Modules/Packages/INTEL.cmake:55 (message):
  INTEL with Intel compilers should use TBB malloc libraries
```

But if I set `-DPKG_INTEL=OFF` I am getting the correct behavior. This confuses me since I am not using any accelerator in my script.

**Comment by akohlmey** [comment] 2021-09-08 16:02
This could be due to a bug in the Intel compiler with high optimization level. The Intel compilers are known to be susceptible for that. If I remember correctly, turning on the INTEL package with Intel compilers will add compiler flags that enable additional and more aggressive optimizations.
Compare the "<<< Compilers and Flags: >>>" summary at the end of the CMake output for the two different settings.

**Comment by yafshar** [comment] 2021-09-08 16:25
thanks, @akohlmey . 

This is the summary 

```bash
-- <<< Compilers and Flags: >>>
-- C++ Compiler:     /stage/opt/OpenMPI/PILEDRIVER/4.0.3/Intel/2019_U4/bin/mpic++
      Type:          Intel
      Version:       19.0.4.20190416
      C++ Flags:     -restrict -O3 -DNDEBUG
      Defines:       LAMMPS_SMALLBIG;LAMMPS_MEMALIGN=64;LAMMPS_OMP_COMPAT=4;LAMMPS_GZIP;FFT_KISS;LMP_PYTHON;LMP_KIM_CURL;LMP_OPENMP;LMP_INTEL;LMP_INTEL_USELRT;LMP_INTEL_NO_TBB
      Options:       -xHost;-O2;-fp-model;fast=2;-no-prec-div;-qoverride-limits;-qopt-zmm-usage=high;-qno-offload;-fno-alias;-ansi-alias;-restrict
-- <<< Linker flags: >>>
```

where I am getting the wrong answer 

```bash
Step E_vdwl E_coul 
       0    245.26002    401.29479
[...]
Ave special neighs/atom = 7.8854167
```

By turning intel off `-DPKG_INTEL=OFF`

```bash
-- <<< Compilers and Flags: >>>
-- C++ Compiler:     /stage/opt/OpenMPI/PILEDRIVER/4.0.3/Intel/2019_U4/bin/mpic++
      Type:          Intel
      Version:       19.0.4.20190416
      C++ Flags:     -restrict -O3 -DNDEBUG
      Defines:       LAMMPS_SMALLBIG;LAMMPS_MEMALIGN=64;LAMMPS_OMP_COMPAT=4;LAMMPS_GZIP;FFT_KISS;LMP_PYTHON;LMP_KIM_CURL;LMP_OPENMP
      Options:       -xHost
-- <<< Linker flags: >>>
```

and am getting the correct answer

```bash
Step E_vdwl E_coul 
       0    -224.7538   -2091.5851 
[...]
Ave special neighs/atom = 14.666667

```

**Comment by akohlmey** [comment] 2021-09-08 18:44
There is a big difference under `Options:` I would suspect one of those flags triggers an optimization that will lead to miscompiled code and the different neighbor lists. This is not really something that can be fixed on the LAMMPS side and the compiler flags are the ones recommended by collaborators at Intel. Perhaps a different version of the Intel compiler (new versions are now available free of cost) will have that corrected. Or you need to avoid the problematic flag.

**Comment by yafshar** [comment] 2021-09-08 18:54
Thanks, @akohlmey. I will update the compiler and check the flags. I will close the issue.

**Closed** 2021-09-08 18:55 UTC
Labels: bug, unconfirmed
