### ISSUE TITLE
Pair style hybrid skip lists depend on order of the hybrid styles

### ISSUE THREAD

**Issue by akohlmey** [lammps/lammps#333] opened 2017-01-10 19:36 UTC
This seems to be a bug that was introduced with the neighbor list refactoring. Here is the report from Steven Strong from LAMMPS users:

Hi-

I have encountered an issue using a hybrid pair_style with sw.
The result depends on the order in which the pair_styles are listed.
I have attached a simple example script that demonstrates this.
It consists of two particles that interact via an LJ potential.
When the two components of the hybrid potential are listed in the order given in the attached script:
  `pair_style hybrid sw lj/cut 9.0`
then there is no force between the two particles (see the output file 'f'). When the order is reversed:
  `pair_style hybrid lj/cut 9.0 sw`
then I get the correct LJ force between the two particles.

Thanks, Steven

[in.test.txt](https://github.com/lammps/lammps/files/697147/in.test.txt)

**Comment by stanmoore1** [comment] 2017-01-12 21:27
I can't reproduce this. I get the same force either way:

ITEM: ATOMS id x y z fx fy fz 
1 0 0 0 0 0 -390144 
2 0 0 0.5 0 0 390144 

@akohlmey can you try?

**Comment by stanmoore1** [comment] 2017-01-12 21:36
Nevermind, I see now...

**Comment by stanmoore1** [comment] 2017-01-12 23:25
The issue was that the neighbor class was trying to build the skip list before creating the corresponding half-from-full list.

**Comment by stanmoore1** [comment] 2017-01-17 18:35
Fixed by 630783c8e852436e1f477e5062d65232fe57afa5. Closed #333.

**Closed by stanmoore1** 2017-01-17 18:35 UTC
Labels: bug
