### ISSUE TITLE
fix_gcmc segfault

### ISSUE THREAD

**Issue by 994PhiJ** [lammps/lammps#751] opened 2017-12-18 11:33 UTC
## Summary

fix gcmc segfaults with mol keyword

## Type of Issue

Bug Report

## LAMMPS Version (Bug Report)

I have two installs of lammps.  Gentoo default install (9Jan2017) and my own manual install for patching (also 09Jan2017).  My (unpatched) install of lammps segfaults when using fix_gcmc but the gentoo default doesn't.  They both segfault on a much larger and more cumbersome input.  My manual install contains packages MC and RIGID.

## Expected Behavior (Bug Report)

LAMMPS runs normally.

## Actual Behavior (Bug Report)

Segmentation fault.

## Steps to Reproduce (Bug Report)

Run lammps with the three attached files.  It should segfault.

If it doesn't segfault, run lammps in gdb with debugging symbols.  Set a breakpoint at fix_gcmc.cpp:1730.

Note that 'print natoms_per_molecule' gives 2, so atom_coord has length 2.

Note that molecule_group_bit is set in mask[2], mask[3] and mask[4].  So in the loop about to be executed, three coordinates get set in atom_coord, but it only has capacity for 2.

I tried to look further, but I'm trying to use this as the basis of a patch that does something different, so I don't really understand what fix gcmc is meant to do here, and the more I look the more confused I get.

## Further Information, Files, and Links

[O2_mol.data.txt](https://github.com/lammps/lammps/files/1567624/O2_mol.data.txt)
[twogas.data.txt](https://github.com/lammps/lammps/files/1567625/twogas.data.txt)
[twogas.in.txt](https://github.com/lammps/lammps/files/1567626/twogas.in.txt)

**Comment by Pakketeretet2** [comment] 2017-12-18 12:30
I can reproduce this with the 23 Oct 2017 version.
It looks like it's maybe an off-by-one error, but I do not know for sure. Was this recently fixed? If not, the GDB output might be useful:

"Thread 1 "lmp" received signal SIGSEGV, Segmentation fault.
0x000055555635d145 in LAMMPS_NS::FixGCMC::attempt_molecule_rotation_full (this=0x555558d89d90) at ../fix_gcmc.cpp:1810
1810	      atom_coord[n][0] = x[i][0];
(gdb) print x
$1 = (double **) 0x555558e44430
(gdb) print atom_coord
$2 = (double **) 0x555558d8a250
(gdb) print atom_coord[0]
$3 = (double *) 0x555558d89870
(gdb) print n
$4 = 2
(gdb) print atom_coord[1]
$5 = (double *) 0x555558d89888
(gdb) print atom_coord[2]
$6 = (double *) 0x0"

**Comment by stanmoore1** [comment] 2018-01-16 17:08
Yeah, there seems to be an issue with the molecule mask. The variable `natoms_per_molecule` is equal to 2, which is the size of `atom_coord`'s first dimension, but the loop over all atoms is finding more than 2 atoms that belong to the molecule, so there is an out of bounds memory access.

**Comment by athomps** [comment] 2018-01-16 18:49
Thanks for the simple example. valgrind detects the problem and it seems to be generic. Not sure why it never showed up before.  I will check in to it.

**Comment by athomps** [comment] 2018-01-17 18:34
The key ingredient in the bug demo is applying fix gcmc to the group all, instead of a dedicated group (see examples/gcmc). This allows rotation of pre-existing molecules, which may have more atoms than the template molecule.  I have added a fix for this and also enabled molecule MC moves without exchanging molecules.   I will submit PR shortly.

**Comment by stanmoore1** [comment] 2018-01-17 21:37
Fixed by #778.

**Closed** 2018-02-02 22:29 UTC
Labels: bug, mc_package
