### ISSUE TITLE
[BUG] 7Aug19 version bond/break issue in parallel

### ISSUE THREAD

**Issue by seukjames** [lammps/lammps#1805] opened 2019-12-10 20:10 UTC
**Summary**

The latest "fix bond/break" (7Aug19) does not work properly in parallel. Several lammps versions were tested to do breaking several stretched bonds. The following tests were summarized. 

For 7Aug19 Lammps version, it seems to work breaking bonds with a serial executable but not in parallel of a cluster.

For 30Sep13 Lammps version, it works both in serial and parallel. Angles and dihedrals, however, won't be altered.  

For 12Dec18 Lammps version, it does not work in parallel.

**Expected Behavior**

Stretched bonds won't be broken with the latest lammps version in parallel. In the data file attached, four unusual bond lengths exist, which were checked by "compute bond/local dist command". After testing with different lammps versions, only 30Sep13 Lammps version worked in both serial and parallel. This version, however, does not update other bonded topologies. 

I assume that the latest version lammps (7Aug19) has a bug of "fix bond/break" in the parallel calculation. 

Attached are the files containing data and input file for the bug testing. 

Thanks. 
James
 

[bondbreaking.zip](https://github.com/lammps/lammps/files/3946910/bondbreaking.zip)

**Comment by akohlmey** [comment] 2020-01-03 16:31
@sjplimp any idea how to address this?

**Comment by sjplimp** [comment] 2020-01-03 22:10
@akohlmey @seukjames I ran this problem.  A few observations and Qs.

1) With the current GitHub master version, I'm not seeing the problem.
Whether I run on 1,8,32 cores (MPI tasks) I see the bond count in
the data file reduce from 38603 to 38599 after 10 steps.  Is that the
expected behavior?  I did not go back and try 7Aug19.

2) I see a couple of warnings that could be problematic:

WARNING: Inconsistent image flags (../domain.cpp:785)
WARNING: Bond/angle/dihedral extent > half of periodic box length (../domain.cpp:906)

B/c they indicate image flags are not correct in the initial data
file, so possibly bonds will not be found correctly by fix bond/break,
Probably a red herring for this bond/break issue.

3) This input script has 7 fix bond/break commands.  Axel, I seem
to recall some issue with using multiple bond/break and/or bond/create
commands.  I.e. that they didn't know about the effects of each other.
Might have just been relevant to fix bond/create.  Do you recall
any details on that?  I don't see a warning on the 2 doc pages, which
I thought we might have added.

Steve

**Comment by akohlmey** [comment] 2020-01-03 22:40
> 1. This input script has 7 fix bond/break commands.  Axel, I seem
>    to recall some issue with using multiple bond/break and/or bond/create

my recollection of that is very vague, so it must be a long time ago. the issue might be with bonds across subdomains. i don't see any changes in the commit messages for the sources related to that (which go back about 5 years before they become just svn commit ids).

>    commands.  I.e. that they didn't know about the effects of each other.
>    Might have just been relevant to fix bond/create.  Do you recall
>    any details on that?  I don't see a warning on the 2 doc pages, which
>    I thought we might have added.

what has transpired recently, is that for more complex bond breaking or bond forming operations, fix bond/react seems more capable and flexible. it certainly has seen many functional improvements since it was added and also a lot of bugs have been fixed. in addition, the author is usually replying to inquiries on the mailing list quickly and very supportive in general. 

> 
> Steve

**Comment by akohlmey** [comment] 2020-01-08 20:59
@seukjames i just ran your input with the latest master sources from github and i get the same number of bonds/angles/dihedrals in serial and parallel with 4 bonds, 20 angles and 49 dihedrals removed. So it is more likely an issue on your side, or you have to provide us  with more specific instructions to reproduce the issue as the generic serial vs. parallel cannot be confirmed.

**Comment by akohlmey** [comment] 2020-01-08 21:00
I am not closing this issue for the time being, but it will be closed in a while unless you provide additional confirmation of a bug that we can actually reproduce ourselves.

**Comment by seukjames** [comment] 2020-01-10 04:03
I checked that the latest master source worked well in parallel. I am going to switch from 7Aug19 to master. 

Thanks.

**Comment by akohlmey** [comment] 2020-01-10 11:28
This inconsistent behavior then must be due to something on the local machine and not LAMMPS. Fix bond/break has not been changed at all since July 2019 and had no functional changes for over 5 years.

**Closed by akohlmey** 2020-01-10 11:28 UTC
Labels: bug, unconfirmed
