### ISSUE TITLE
[Feature Request] Add -std=c++11 to Makefiles

### ISSUE THREAD

**Issue by stanmoore1** [lammps/lammps#1961] opened 2020-03-24 16:16 UTC
**Summary**

Can we add `-std=c++11` to the Makefiles, e.g. `Makefile.mpi` and others, now that LAMMPS requires it?

**Comment by akohlmey** [comment] 2020-03-24 23:19
@stanmoore1 I would recommend against adding it to Makefile.mpi since this makefile is supposed to work on the largest variety of machines without modifications and `-std=c++11` is specific to GNU gcc and compilers that try to be command line compatible with it. Most compilers on most systems are C++11 compatible by default. It is mostly RHEL/CentOS 7.x that is not.

Beyond that, for people that have trouble handling this situation, we should recommend building with CMake, as this will attempt to automatically discover most settings, will automatically enable C++11 compatibility with the compiler specific flag, and - as of recent - also will try to set some additional compiler dependent optimization flags (where known). With the latest changes, people on most machines should be able to get a well working LAMMPS executable with many commonly used features included through:
```
cd path/to/lammps
mkdir build
cd build
cmake3 -C ../cmake/presets/most.preset ../cmake
cmake3 --build .
```
Or if they want a more minimal but still widely applicable configuration (MANYBODY, MOLECULE, KSPACE, RIGID) use the `minimal.cmake` preset (which is similar to the packages installed by default in older LAMMPS tarballs).

**Comment by akohlmey** [comment] 2020-04-03 14:30
@stanmoore1 since nobody else commented on this, can we close this issue and continue the discussion in private, if needed?
I am open to make changes, if there is a compelling use case, but we have to balance it against the goals named in my previous comment.

Outside of compiling with KOKKOS enabled, I am not aware of any scenario where the conventional build has significant advantages over using CMake, and there is - of course - no problem to have -std=c++11 added to any of the makefiles in src/MAKE/MACHINES or src/MAKE/OPTIONS, but src/MAKE/Makefile.mpi should be as compatible to as many machines as possible. 

The changes from PR #1956 improve the MinGW cross compilation so that it works better with CMake than with the conventional build. After that is merged, we need to update the docs for compiling KOKKOS with CMake anyway, at that time I am planning to prepare a few preset files that would mirror the available makefiles for the KOKKOS configurations to - hopefully - make the CMake route as convenient for compiling with KOKKOS as the conventional make build.

**Comment by stanmoore1** [comment] 2021-08-10 22:23
I think we should revisit this.

**Comment by akohlmey** [comment] 2021-09-27 18:25
@stanmoore1 I don't like adding a non-portable flag to Makefile.mpi. We've tried to make this as generic as possible. Would it be a satisfactory solution to add a Makefile.centos7?

**Comment by stanmoore1** [comment] 2021-09-27 18:28
Not portable for which compilers? The Intel compiler requires adding the "-std=c++11" flag, even for Intel 20.0. So I don't think this statement is valid:

`Most compilers on most systems are C++11 compatible by default. It is mostly RHEL/CentOS 7.x that is not.`

**Comment by stanmoore1** [comment] 2021-09-27 18:36
Looking at https://github.com/kokkos/kokkos/blob/master/Makefile.kokkos all compilers tested by Kokkos, (GNU, Intel, Clang) support this flag except PGI and Cray. So I think *not* adding this flag is hurting more users, i.e. Intel users.

**Comment by akohlmey** [comment] 2021-09-27 18:38
> Not portable for which compilers?

PGI/Nvidia for example, not sure about the IBM ones either, except for the LLVM based versions.

We do have specific makefiles for intel compilers, but I noticed the "icc" ones are without -std=c++11, so that should be added there.

Since it doesn't look we're going to converge between us two, I suggest we put this item to a vote.
@sjplimp, @athomps, @rbberger what is your preference? 5 people should result in a majority unless somebody abstains.

**Comment by stanmoore1** [comment] 2021-09-27 18:40
Multiple people trying to build LAMMPS have asked me about this, so I'm not the only user who this would benefit...

**Comment by akohlmey** [comment] 2021-09-27 19:24
Hmmm... just checking with PGI/Nvidia compilers and it looks that with version 21.3 they have switched to an LLVM based backend and thus also used the "gnu" conventions for signaling the C++ standard. The pgCC executable is gone, too. pgc++ is now required.

**Comment by akohlmey** [comment] 2021-09-27 19:36
Version 2021.2 of both the old Intel compiler and the new LLVM based default to C++14

**Comment by rbberger** [comment] 2021-09-27 19:54
@akohlmey not sure that statement holds:
```
$ module load intel-compiler/2021.3.0
$ icpc cpptest.cpp 
$ ./a.out
199711
$ icpc -std=c++11 cpptest.cpp 
$ ./a.out
201103
```
Might be dependent on the default GCC toolchain on the system (in this case CentOS7)

**Comment by stanmoore1** [comment] 2021-09-27 19:58
Yeah I took another look at the Intel issue I saw. The problem is not that the Intel compiler isn't c++11/14 compatible, but rather the underlying GCC version is 4.8.5 by default on our cluster, so it still chokes if we don't add the "-std=c++11" flag or load a newer GCC. I suppose this is RHEL7 related.

**Comment by akohlmey** [comment] 2021-09-27 19:59
> Might be dependent on the default GCC toolchain on the system (in this case CentOS7)

Must be. I am checking on Fedora 33/34 here.

**Comment by akohlmey** [comment] 2021-09-27 20:05
OK. After some more input and checking things. The points in favor of a change are more than those against as I see it. I will prepare a pull request.

**Comment by rbberger** [comment] 2021-09-27 20:09
Confirmed.
```
$ module load intel-compiler/2021.3.0
$ module load gcc/11.1.0 
$ icpc cpptest.cpp 
$ ./a.out 
201402
```

**Comment by rbberger** [comment] 2021-09-27 20:11
There is a tiny side note on this page: https://software.intel.com/content/www/us/en/develop/articles/c0x-features-supported-by-intel-c-compiler.html

> 3. On Linux or macOS: the C++11 features supported by **gcc on the path** are enabled by default. Use "-std=c++11" to turn on the support for all other cases.

**Comment by akohlmey** [comment] 2021-09-27 20:15
... and none of this is as crazy as what the microsoft folks did with their visual c++ compiler. They are C++14 compatible by default, but the `__cplusplus` macro indicates C++98. :facepalm: You need to set a special flag to have it report the correct version. :facepalm: But if we ever get LAMMPS to compile with VC++ it will be with CMake only, and there the issue is a non-issue as CMake will add the suitable flag for the compiler at hand automatically according to the required standard.

**Comment by akohlmey** [comment] 2021-09-27 20:16
Oh, and we should add AppleClang to the list of compilers that default to C++98 regardless of the behavior of the Clang version they are based on.

**Closed** 2021-09-27 23:42 UTC
Labels: enhancement
