### ISSUE TITLE
[BUG] Regression for the module quip (and maybe other)

### ISSUE THREAD

**Issue by Axel-SH4** [lammps/lammps#2780] opened 2021-05-25 09:14 UTC
**Summary**

[This commit](https://github.com/lammps/lammps/commit/1e3f1c584c569601efef6111babd3b3302dde656) removed some lines in the file `src/USER-QUIP/pair_quip.cpp` from:
```
  n_quip_file = strlen(arg[2]);
  quip_file = new char[n_quip_file+1];
 strcpy(quip_file,arg[2]);

  n_quip_string = strlen(arg[3]);
  quip_string = new char[n_quip_string+1];
  strcpy(quip_string,arg[3]);
```
to
```
  quip_file = utils::strdup(arg[2]);
  quip_string = utils::strdup(arg[3]);
```

Leaving `n_quip_file` and `n_quip_string` initialized to 0 (due to how the object they belong to is created), but those two variables are used a bit below in a function:
`quip_lammps_potential_initialise(quip_potential,&n_quip_potential,&cutoff,quip_file,&n_quip_file,quip_string,&n_quip_string);`

This function is actually calling FORTRAN code via the C ABI, which specify that the length of a string should be passed as an argument along the original string for FORTRAN code, as FORTRAN doesn't use a NULL byte to recognize the end of a string.

Thus those two variables should be initialized correctly, and someone that know if the project is calling FORTRAN elsewhere could check if the same problem could have happened in another part of the code.

**Comment by akohlmey** [comment] 2021-05-25 18:44
@Axel-SH4 thanks for reporting. The issue should be resolved in the next patch release.
This is not likely to show elsewhere, since we run extensive automated regression tests. Unfortunately, these do not include the USER-QUIP package due to the complications of obtaining the up-to-date source code and building it in an automated fashion.

**Closed** 2021-05-26 15:29 UTC
Labels: bug
