### ISSUE TITLE
[BUG] Build fails due to the use of deprecated and removed features

### ISSUE THREAD

**Issue by yurivict** [lammps/lammps#3876] opened 2023-08-03 22:42 UTC
**Summary**

You use C++17 and the ```binary_function``` that was removed in C++17.

**LAMMPS Version and Platform**

* lammps-2023.06.15
* lammps-2023.08.02
* FreeBSD 13.2

**Expected Behavior**
n/a

**Actual Behavior**
```
In file included from /wrkdirs/usr/ports/science/lammps/work/lammps-patch_15Jun2023/src/AWPMD/pair_awpmd_cut.cpp:34:
In file included from /wrkdirs/usr/ports/science/lammps/work/lammps-patch_15Jun2023/lib/awpmd/systems/interact/TCP/wpmd.h:151:
/wrkdirs/usr/ports/science/lammps/work/lammps-patch_15Jun2023/lib/awpmd/ivutils/include/wavepacket.h:26:27: error: no template named 'binary_function'; did you mean '__binary_function'?
struct eq_second : public binary_function <Type, Type, Type> {
                          ^~~~~~~~~~~~~~~
                          __binary_function
/usr/include/c++/v1/__functional/binary_function.h:49:1: note: '__binary_function' declared here
using __binary_function = __binary_function_keep_layout_base<_Arg1, _Arg2, _Result>;
^
In file included from /wrkdirs/usr/ports/science/lammps/work/lammps-patch_15Jun2023/src/AWPMD/pair_awpmd_cut.cpp:34:
In file included from /wrkdirs/usr/ports/science/lammps/work/lammps-patch_15Jun2023/lib/awpmd/systems/interact/TCP/wpmd.h:151:
/wrkdirs/usr/ports/science/lammps/work/lammps-patch_15Jun2023/lib/awpmd/ivutils/include/wavepacket.h:34:33: error: no template named 'binary_function'; did you mean '__binary_function'?
struct eq_minus_second : public binary_function <Type, Type, Type> {
                                ^~~~~~~~~~~~~~~
                                __binary_function
/usr/include/c++/v1/__functional/binary_function.h:49:1: note: '__binary_function' declared here
using __binary_function = __binary_function_keep_layout_base<_Arg1, _Arg2, _Result>;
^
2 errors generated.
```

**Steps to Reproduce**

regular build

**Comment by akohlmey** [comment] 2023-08-03 23:13
> You use C++17

That is not correct. LAMMPS *requires* C++11 and sets the C++ standard to C++11 unless you use an external cmake define to use a different standard. The only package straying from that is the KOKKOS package that requires C++14.
So when KOKKOS is enabled the minimum required C++ standard is set to C++14 instead. Of course you can always set something different, but there you are on your own.

The only way I can imagine where C++17 is set automatically would be when you are using an *external* version of Kokkos 4.x. While this is technically possible, LAMMPS 2 August 2023 is only validated with Kokkos 3.7 which requires only C++14. If you use a more recent version of Kokkos and things break, you are on your own. If this conflicts with an older package written without support for C++17, you must disable that package then. This is your choice and that is why stuff is organized in packages. It is most certainly not a bug in LAMMPS

That said, even with enabling C++17, I get the AWPMD package compiled. 
```
$ git describe --all
tags/patch_2Aug2023

$ cmake -S cmake -B build-awpmd -DPKG_AWPMD=on -DCMAKE_CXX_STANDARD=17
$ cmake --build build-awpmd
$ ./build-awpmd/lmp -h
Large-scale Atomic/Molecular Massively Parallel Simulator - 2 Aug 2023
Git info (develop / patch_2Aug2023)

[...]

OS: FreeBSD "FreeBSD 13.2-RELEASE" 13.2-RELEASE amd64

Compiler: Clang C++ FreeBSD Clang 14.0.5 (https://github.com/llvm/llvm-project.git llvmorg-14.0.5-0-gc12386ae247c) with OpenMP 5.0
C++ standard: C++17
MPI v3.1: MPICH Version:        3.4.3
MPICH Release date:     Thu Dec 16 11:20:57 CST 2021

MPICH ABI:      13:12:1

Accelerator configuration:


Active compile time flags:

-DLAMMPS_GZIP
-DLAMMPS_PNG
-DLAMMPS_JPEG
-DLAMMPS_FFMPEG
-DLAMMPS_SMALLBIG
sizeof(smallint): 32-bit
sizeof(imageint): 32-bit
sizeof(tagint):   32-bit
sizeof(bigint):   64-bit

Available compression formats:

Extension: .gz     Command: gzip
Extension: .bz2    Command: bzip2
Extension: .zst    Command: zstd
Extension: .xz     Command: xz
Extension: .lzma   Command: xz
Extension: .lz4    Command: lz4


Installed packages:

AWPMD 
```

> Steps to Reproduce

> regular build

This is insufficient information. There is no such thing as a "regular build". In order to be reproducible, exact details need to be provided. There are many ways how one can break things.

**Comment by yurivict** [comment] 2023-08-04 04:00
> That is not correct. LAMMPS *requires* C++11 and sets the C++ standard to C++11 unless you use an external cmake define to use a different standard. The only package straying from that is the KOKKOS package that requires C++14.

The failing commands have c++17 requirements for some reason:
```
[ 43%] Building CXX object CMakeFiles/lammps.dir/wrkdirs/usr/ports/science/lammps/work/lammps-patch_15Jun2023/src/AWPMD/fix_nve_awpmd.cpp.o
/usr/bin/c++ -DASMJIT_BUILD_RELEASE=1 -DASMJIT_BUILD_X86=1 -DASMJIT_STATIC=1 -DEIGEN_NO_CUDA -DFFT_FFTW3 -DFFT_FFTW_THREADS -DKOKKOS_DEPENDENCE -DLAMMPS_EXCEPTIONS -DLAMMPS_FFMPEG -DLAMMPS_GZIP -DLAMMPS_JPEG -DLAMMPS_MEMALIGN=64 -DLAMMPS_OMP_COMPAT=4 -DLAMMPS_PNG -DLAMMPS_SMALLBIG -DLAMMPS_ZSTD -DLEPTON_BUILDING_STATIC_LIBRARY=1 -DLEPTON_USE_JIT=1 -DLMP_HAS_NETCDF -DLMP_KIM_CURL -DLMP_KOKKOS -DLMP_MPIIO -DLMP_PLUGIN -DLMP_PYTHON -DMPICH_SKIP_MPICXX -DNC_64BIT_DATA=0x0020 -DOMPI_SKIP_MPICXX -D_MPICC_H -Dlammps_EXPORTS -I/wrkdirs/usr/ports/science/lammps/work/lammps-patch_15Jun2023/src -I/wrkdirs/usr/ports/science/lammps/work/lammps-patch_15Jun2023/src/ASPHERE -I/wrkdirs/usr/ports/science/lammps/work/lammps-patch_15Jun2023/src/ATC -I/wrkdirs/usr/ports/science/lammps/work/lammps-patch_15Jun2023/src/AWPMD -I/wrkdirs/usr/ports/science/lammps/work/lammps-patch_15Jun2023/src/BOCS -I/wrkdirs/usr/ports/science/lammps/work/lammps-patch_15Jun2023/src/BODY -I/wrkdirs/usr/ports/science/l
ammps/work/lammps-patch_15Jun2023/src/BROWNIAN -I/wrkdirs/usr/ports/science/lammps/work/lammps-patch_15Jun2023/src/CG-DNA -I/wrkdirs/usr/ports/science/lammps/work/lammps-patch_15Jun2023/src/CLASS2 -I/wrkdirs/usr/ports/science/lammps/work/lammps-patch_15Jun2023/src/COLLOID -I/wrkdirs/usr/ports/science/lammps/work/lammps-patch_15Jun2023/src/COLVARS -I/wrkdirs/usr/ports/science/lammps/work/lammps-patch_15Jun2023/src/COMPRESS -I/wrkdirs/usr/ports/science/lammps/work/lammps-patch_15Jun2023/src/DIELECTRIC -I/wrkdirs/usr/ports/science/lammps/work/lammps-patch_15Jun2023/src/DIFFRACTION -I/wrkdirs/usr/ports/science/lammps/work/lammps-patch_15Jun2023/src/DIPOLE -I/wrkdirs/usr/ports/science/lammps/work/lammps-patch_15Jun2023/src/DPD-BASIC -I/wrkdirs/usr/ports/science/lammps/work/lammps-patch_15Jun2023/src/DPD-MESO -I/wrkdirs/usr/ports/science/lammps/work/lammps-patch_15Jun2023/src/DPD-REACT -I/wrkdirs/usr/ports/science/lammps/work/lammps-patch_15Jun2023/src/DPD-SMOOTH -I/wrkdirs/usr/po
rts/science/lammps/work/lammps-patch_15Jun2023/src/DRUDE -I/wrkdirs/usr/ports/science/lammps/work/lammps-patch_15Jun2023/src/EFF -I/wrkdirs/usr/ports/science/lammps/work/lammps-patch_15Jun2023/src/EXTRA-COMPUTE -I/wrkdirs/usr/ports/science/lammps/work/lammps-patch_15Jun2023/src/EXTRA-DUMP -I/wrkdirs/usr/ports/science/lammps/work/lammps-patch_15Jun2023/src/EXTRA-FIX -I/wrkdirs/usr/ports/science/lammps/work/lammps-patch_15Jun2023/src/EXTRA-MOLECULE -I/wrkdirs/usr/ports/science/lammps/work/lammps-patch_15Jun2023/src/EXTRA-PAIR -I/wrkdirs/usr/ports/science/lammps/work/lammps-patch_15Jun2023/src/FEP -I/wrkdirs/usr/ports/science/lammps/work/lammps-patch_15Jun2023/src/GRANULAR -I/wrkdirs/usr/ports/science/lammps/work/lammps-patch_15Jun2023/src/H5MD -I/wrkdirs/usr/ports/science/lammps/work/lammps-patch_15Jun2023/src/INTERLAYER -I/wrkdirs/usr/ports/science/lammps/work/lammps-patch_15Jun2023/src/KIM -I/wrkdirs/usr/ports/science/lammps/work/lammps-patch_15Jun2023/src/KSPACE -I/wrkdirs/
usr/ports/science/lammps/work/lammps-patch_15Jun2023/src/LATBOLTZ -I/wrkdirs/usr/ports/science/lammps/work/lammps-patch_15Jun2023/src/MACHDYN -I/wrkdirs/usr/ports/science/lammps/work/lammps-patch_15Jun2023/src/MANIFOLD -I/wrkdirs/usr/ports/science/lammps/work/lammps-patch_15Jun2023/src/MANYBODY -I/wrkdirs/usr/ports/science/lammps/work/lammps-patch_15Jun2023/src/MC -I/wrkdirs/usr/ports/science/lammps/work/lammps-patch_15Jun2023/src/MEAM -I/wrkdirs/usr/ports/science/lammps/work/lammps-patch_15Jun2023/src/MGPT -I/wrkdirs/usr/ports/science/lammps/work/lammps-patch_15Jun2023/src/MISC -I/wrkdirs/usr/ports/science/lammps/work/lammps-patch_15Jun2023/src/ML-IAP -I/wrkdirs/usr/ports/science/lammps/work/lammps-patch_15Jun2023/src/ML-RANN -I/wrkdirs/usr/ports/science/lammps/work/lammps-patch_15Jun2023/src/ML-SNAP -I/wrkdirs/usr/ports/science/lammps/work/lammps-patch_15Jun2023/src/MOFFF -I/wrkdirs/usr/ports/science/lammps/work/lammps-patch_15Jun2023/src/MOLECULE -I/wrkdirs/usr/ports/scie
nce/lammps/work/lammps-patch_15Jun2023/src/MOLFILE -I/wrkdirs/usr/ports/science/lammps/work/lammps-patch_15Jun2023/src/MPIIO -I/wrkdirs/usr/ports/science/lammps/work/lammps-patch_15Jun2023/src/NETCDF -I/wrkdirs/usr/ports/science/lammps/work/lammps-patch_15Jun2023/src/ORIENT -I/wrkdirs/usr/ports/science/lammps/work/lammps-patch_15Jun2023/src/PERI -I/wrkdirs/usr/ports/science/lammps/work/lammps-patch_15Jun2023/src/PHONON -I/wrkdirs/usr/ports/science/lammps/work/lammps-patch_15Jun2023/src/PLUGIN -I/wrkdirs/usr/ports/science/lammps/work/lammps-patch_15Jun2023/src/PLUMED -I/wrkdirs/usr/ports/science/lammps/work/lammps-patch_15Jun2023/src/POEMS -I/wrkdirs/usr/ports/science/lammps/work/lammps-patch_15Jun2023/src/PTM -I/wrkdirs/usr/ports/science/lammps/work/lammps-patch_15Jun2023/src/PYTHON -I/wrkdirs/usr/ports/science/lammps/work/lammps-patch_15Jun2023/src/QEQ -I/wrkdirs/usr/ports/science/lammps/work/lammps-patch_15Jun2023/src/QMMM -I/wrkdirs/usr/ports/science/lammps/work/lammps-pa
tch_15Jun2023/src/QTB -I/wrkdirs/usr/ports/science/lammps/work/lammps-patch_15Jun2023/src/REACTION -I/wrkdirs/usr/ports/science/lammps/work/lammps-patch_15Jun2023/src/REAXFF -I/wrkdirs/usr/ports/science/lammps/work/lammps-patch_15Jun2023/src/REPLICA -I/wrkdirs/usr/ports/science/lammps/work/lammps-patch_15Jun2023/src/RIGID -I/wrkdirs/usr/ports/science/lammps/work/lammps-patch_15Jun2023/src/SHOCK -I/wrkdirs/usr/ports/science/lammps/work/lammps-patch_15Jun2023/src/SMTBQ -I/wrkdirs/usr/ports/science/lammps/work/lammps-patch_15Jun2023/src/SPH -I/wrkdirs/usr/ports/science/lammps/work/lammps-patch_15Jun2023/src/SPIN -I/wrkdirs/usr/ports/science/lammps/work/lammps-patch_15Jun2023/src/SRD -I/wrkdirs/usr/ports/science/lammps/work/lammps-patch_15Jun2023/src/TALLY -I/wrkdirs/usr/ports/science/lammps/work/lammps-patch_15Jun2023/src/UEF -I/wrkdirs/usr/ports/science/lammps/work/lammps-patch_15Jun2023/src/VORONOI -I/wrkdirs/usr/ports/science/lammps/work/lammps-patch_15Jun2023/src/YAFF -I/wr
kdirs/usr/ports/science/lammps/work/lammps-patch_15Jun2023/src/KOKKOS -I/wrkdirs/usr/ports/science/lammps/work/.build/styles -I/wrkdirs/usr/ports/science/lammps/work/lammps-patch_15Jun2023/lib/lepton/include -I/wrkdirs/usr/ports/science/lammps/work/lammps-patch_15Jun2023/lib/lepton -I/wrkdirs/usr/ports/science/lammps/work/lammps-patch_15Jun2023/lib/colvars -I/wrkdirs/usr/ports/science/lammps/work/lammps-patch_15Jun2023/lib/molfile -I/wrkdirs/usr/ports/science/lammps/work/lammps-patch_15Jun2023/lib/qmmm -I/wrkdirs/usr/ports/science/lammps/work/lammps-patch_15Jun2023/lib/poems -I/wrkdirs/usr/ports/science/lammps/work/lammps-patch_15Jun2023/lib/atc -I/wrkdirs/usr/ports/science/lammps/work/lammps-patch_15Jun2023/lib/awpmd/systems/interact -I/wrkdirs/usr/ports/science/lammps/work/lammps-patch_15Jun2023/lib/awpmd/ivutils/include -I/wrkdirs/usr/ports/science/lammps/work/lammps-patch_15Jun2023/lib/h5md/include -isystem /usr/local/mpi/openmpi/include -isystem /usr/local/include/pytho
n3.9 -isystem /usr/local/include/voro++ -isystem /usr/local/include/eigen3 -isystem /usr/local/lib/kim-api/mod -isystem /usr/local/include/kim-api -O2 -pipe -fstack-protector-strong -isystem /usr/local/include -fno-strict-aliasing  -isystem /usr/local/include -O2 -pipe -fstack-protector-strong -isystem /usr/local/include -fno-strict-aliasing  -isystem /usr/local/include  -DNDEBUG -std=c++17 -fPIC -fexceptions -pthread -fopenmp=libomp -MD -MT CMakeFiles/lammps.dir/wrkdirs/usr/ports/science/lammps/work/lammps-patch_15Jun2023/src/AWPMD/fix_nve_awpmd.cpp.o -MF CMakeFiles/lammps.dir/wrkdirs/usr/ports/science/lammps/work/lammps-patch_15Jun2023/src/AWPMD/fix_nve_awpmd.cpp.o.d -o CMakeFiles/lammps.dir/wrkdirs/usr/ports/science/lammps/work/lammps-patch_15Jun2023/src/AWPMD/fix_nve_awpmd.cpp.o -c /wrkdirs/usr/ports/science/lammps/work/lammps-patch_15Jun2023/src/AWPMD/fix_nve_awpmd.cpp
In file included from /wrkdirs/usr/ports/science/lammps/work/lammps-patch_15Jun2023/src/AWPMD/fix_nve_awpmd.cpp:28:
In file included from /wrkdirs/usr/ports/science/lammps/work/lammps-patch_15Jun2023/lib/awpmd/systems/interact/TCP/wpmd_split.h:65:
In file included from /wrkdirs/usr/ports/science/lammps/work/lammps-patch_15Jun2023/lib/awpmd/systems/interact/TCP/wpmd.h:151:
/wrkdirs/usr/ports/science/lammps/work/lammps-patch_15Jun2023/lib/awpmd/ivutils/include/wavepacket.h:26:27: error: no template named 'binary_function'; did you mean '__binary_function'?
struct eq_second : public binary_function <Type, Type, Type> {
                          ^~~~~~~~~~~~~~~
                          __binary_function
/usr/include/c++/v1/__functional/binary_function.h:49:1: note: '__binary_function' declared here
using __binary_function = __binary_function_keep_layout_base<_Arg1, _Arg2, _Result>;
^
In file included from /wrkdirs/usr/ports/science/lammps/work/lammps-patch_15Jun2023/src/AWPMD/fix_nve_awpmd.cpp:28:
In file included from /wrkdirs/usr/ports/science/lammps/work/lammps-patch_15Jun2023/lib/awpmd/systems/interact/TCP/wpmd_split.h:65:
In file included from /wrkdirs/usr/ports/science/lammps/work/lammps-patch_15Jun2023/lib/awpmd/systems/interact/TCP/wpmd.h:151:
/wrkdirs/usr/ports/science/lammps/work/lammps-patch_15Jun2023/lib/awpmd/ivutils/include/wavepacket.h:34:33: error: no template named 'binary_function'; did you mean '__binary_function'?
struct eq_minus_second : public binary_function <Type, Type, Type> {
                                ^~~~~~~~~~~~~~~
                                __binary_function
/usr/include/c++/v1/__functional/binary_function.h:49:1: note: '__binary_function' declared here
using __binary_function = __binary_function_keep_layout_base<_Arg1, _Arg2, _Result>;
^
--- CMakeFiles/lammps.dir/wrkdirs/usr/ports/science/lammps/work/lammps-patch_15Jun2023/src/AWPMD/pair_awpmd_cut.cpp.o ---
[ 43%] Building CXX object CMakeFiles/lammps.dir/wrkdirs/usr/ports/science/lammps/work/lammps-patch_15Jun2023/src/AWPMD/pair_awpmd_cut.cpp.o
/usr/bin/c++ -DASMJIT_BUILD_RELEASE=1 -DASMJIT_BUILD_X86=1 -DASMJIT_STATIC=1 -DEIGEN_NO_CUDA -DFFT_FFTW3 -DFFT_FFTW_THREADS -DKOKKOS_DEPENDENCE -DLAMMPS_EXCEPTIONS -DLAMMPS_FFMPEG -DLAMMPS_GZIP -DLAMMPS_JPEG -DLAMMPS_MEMALIGN=64 -DLAMMPS_OMP_COMPAT=4 -DLAMMPS_PNG -DLAMMPS_SMALLBIG -DLAMMPS_ZSTD -DLEPTON_BUILDING_STATIC_LIBRARY=1 -DLEPTON_USE_JIT=1 -DLMP_HAS_NETCDF -DLMP_KIM_CURL -DLMP_KOKKOS -DLMP_MPIIO -DLMP_PLUGIN -DLMP_PYTHON -DMPICH_SKIP_MPICXX -DNC_64BIT_DATA=0x0020 -DOMPI_SKIP_MPICXX -D_MPICC_H -Dlammps_EXPORTS -I/wrkdirs/usr/ports/science/lammps/work/lammps-patch_15Jun2023/src -I/wrkdirs/usr/ports/science/lammps/work/lammps-patch_15Jun2023/src/ASPHERE -I/wrkdirs/usr/ports/science/lammps/work/lammps-patch_15Jun2023/src/ATC -I/wrkdirs/usr/ports/science/lammps/work/lammps-patch_15Jun2023/src/AWPMD -I/wrkdirs/usr/ports/science/lammps/work/lammps-patch_15Jun2023/src/BOCS -I/wrkdirs/usr/ports/science/lammps/work/lammps-patch_15Jun2023/src/BODY -I/wrkdirs/usr/ports/science/l
ammps/work/lammps-patch_15Jun2023/src/BROWNIAN -I/wrkdirs/usr/ports/science/lammps/work/lammps-patch_15Jun2023/src/CG-DNA -I/wrkdirs/usr/ports/science/lammps/work/lammps-patch_15Jun2023/src/CLASS2 -I/wrkdirs/usr/ports/science/lammps/work/lammps-patch_15Jun2023/src/COLLOID -I/wrkdirs/usr/ports/science/lammps/work/lammps-patch_15Jun2023/src/COLVARS -I/wrkdirs/usr/ports/science/lammps/work/lammps-patch_15Jun2023/src/COMPRESS -I/wrkdirs/usr/ports/science/lammps/work/lammps-patch_15Jun2023/src/DIELECTRIC -I/wrkdirs/usr/ports/science/lammps/work/lammps-patch_15Jun2023/src/DIFFRACTION -I/wrkdirs/usr/ports/science/lammps/work/lammps-patch_15Jun2023/src/DIPOLE -I/wrkdirs/usr/ports/science/lammps/work/lammps-patch_15Jun2023/src/DPD-BASIC -I/wrkdirs/usr/ports/science/lammps/work/lammps-patch_15Jun2023/src/DPD-MESO -I/wrkdirs/usr/ports/science/lammps/work/lammps-patch_15Jun2023/src/DPD-REACT -I/wrkdirs/usr/ports/science/lammps/work/lammps-patch_15Jun2023/src/DPD-SMOOTH -I/wrkdirs/usr/po
rts/science/lammps/work/lammps-patch_15Jun2023/src/DRUDE -I/wrkdirs/usr/ports/science/lammps/work/lammps-patch_15Jun2023/src/EFF -I/wrkdirs/usr/ports/science/lammps/work/lammps-patch_15Jun2023/src/EXTRA-COMPUTE -I/wrkdirs/usr/ports/science/lammps/work/lammps-patch_15Jun2023/src/EXTRA-DUMP -I/wrkdirs/usr/ports/science/lammps/work/lammps-patch_15Jun2023/src/EXTRA-FIX -I/wrkdirs/usr/ports/science/lammps/work/lammps-patch_15Jun2023/src/EXTRA-MOLECULE -I/wrkdirs/usr/ports/science/lammps/work/lammps-patch_15Jun2023/src/EXTRA-PAIR -I/wrkdirs/usr/ports/science/lammps/work/lammps-patch_15Jun2023/src/FEP -I/wrkdirs/usr/ports/science/lammps/work/lammps-patch_15Jun2023/src/GRANULAR -I/wrkdirs/usr/ports/science/lammps/work/lammps-patch_15Jun2023/src/H5MD -I/wrkdirs/usr/ports/science/lammps/work/lammps-patch_15Jun2023/src/INTERLAYER -I/wrkdirs/usr/ports/science/lammps/work/lammps-patch_15Jun2023/src/KIM -I/wrkdirs/usr/ports/science/lammps/work/lammps-patch_15Jun2023/src/KSPACE -I/wrkdirs/
usr/ports/science/lammps/work/lammps-patch_15Jun2023/src/LATBOLTZ -I/wrkdirs/usr/ports/science/lammps/work/lammps-patch_15Jun2023/src/MACHDYN -I/wrkdirs/usr/ports/science/lammps/work/lammps-patch_15Jun2023/src/MANIFOLD -I/wrkdirs/usr/ports/science/lammps/work/lammps-patch_15Jun2023/src/MANYBODY -I/wrkdirs/usr/ports/science/lammps/work/lammps-patch_15Jun2023/src/MC -I/wrkdirs/usr/ports/science/lammps/work/lammps-patch_15Jun2023/src/MEAM -I/wrkdirs/usr/ports/science/lammps/work/lammps-patch_15Jun2023/src/MGPT -I/wrkdirs/usr/ports/science/lammps/work/lammps-patch_15Jun2023/src/MISC -I/wrkdirs/usr/ports/science/lammps/work/lammps-patch_15Jun2023/src/ML-IAP -I/wrkdirs/usr/ports/science/lammps/work/lammps-patch_15Jun2023/src/ML-RANN -I/wrkdirs/usr/ports/science/lammps/work/lammps-patch_15Jun2023/src/ML-SNAP -I/wrkdirs/usr/ports/science/lammps/work/lammps-patch_15Jun2023/src/MOFFF -I/wrkdirs/usr/ports/science/lammps/work/lammps-patch_15Jun2023/src/MOLECULE -I/wrkdirs/usr/ports/scie
nce/lammps/work/lammps-patch_15Jun2023/src/MOLFILE -I/wrkdirs/usr/ports/science/lammps/work/lammps-patch_15Jun2023/src/MPIIO -I/wrkdirs/usr/ports/science/lammps/work/lammps-patch_15Jun2023/src/NETCDF -I/wrkdirs/usr/ports/science/lammps/work/lammps-patch_15Jun2023/src/ORIENT -I/wrkdirs/usr/ports/science/lammps/work/lammps-patch_15Jun2023/src/PERI -I/wrkdirs/usr/ports/science/lammps/work/lammps-patch_15Jun2023/src/PHONON -I/wrkdirs/usr/ports/science/lammps/work/lammps-patch_15Jun2023/src/PLUGIN -I/wrkdirs/usr/ports/science/lammps/work/lammps-patch_15Jun2023/src/PLUMED -I/wrkdirs/usr/ports/science/lammps/work/lammps-patch_15Jun2023/src/POEMS -I/wrkdirs/usr/ports/science/lammps/work/lammps-patch_15Jun2023/src/PTM -I/wrkdirs/usr/ports/science/lammps/work/lammps-patch_15Jun2023/src/PYTHON -I/wrkdirs/usr/ports/science/lammps/work/lammps-patch_15Jun2023/src/QEQ -I/wrkdirs/usr/ports/science/lammps/work/lammps-patch_15Jun2023/src/QMMM -I/wrkdirs/usr/ports/science/lammps/work/lammps-pa
tch_15Jun2023/src/QTB -I/wrkdirs/usr/ports/science/lammps/work/lammps-patch_15Jun2023/src/REACTION -I/wrkdirs/usr/ports/science/lammps/work/lammps-patch_15Jun2023/src/REAXFF -I/wrkdirs/usr/ports/science/lammps/work/lammps-patch_15Jun2023/src/REPLICA -I/wrkdirs/usr/ports/science/lammps/work/lammps-patch_15Jun2023/src/RIGID -I/wrkdirs/usr/ports/science/lammps/work/lammps-patch_15Jun2023/src/SHOCK -I/wrkdirs/usr/ports/science/lammps/work/lammps-patch_15Jun2023/src/SMTBQ -I/wrkdirs/usr/ports/science/lammps/work/lammps-patch_15Jun2023/src/SPH -I/wrkdirs/usr/ports/science/lammps/work/lammps-patch_15Jun2023/src/SPIN -I/wrkdirs/usr/ports/science/lammps/work/lammps-patch_15Jun2023/src/SRD -I/wrkdirs/usr/ports/science/lammps/work/lammps-patch_15Jun2023/src/TALLY -I/wrkdirs/usr/ports/science/lammps/work/lammps-patch_15Jun2023/src/UEF -I/wrkdirs/usr/ports/science/lammps/work/lammps-patch_15Jun2023/src/VORONOI -I/wrkdirs/usr/ports/science/lammps/work/lammps-patch_15Jun2023/src/YAFF -I/wr
kdirs/usr/ports/science/lammps/work/lammps-patch_15Jun2023/src/KOKKOS -I/wrkdirs/usr/ports/science/lammps/work/.build/styles -I/wrkdirs/usr/ports/science/lammps/work/lammps-patch_15Jun2023/lib/lepton/include -I/wrkdirs/usr/ports/science/lammps/work/lammps-patch_15Jun2023/lib/lepton -I/wrkdirs/usr/ports/science/lammps/work/lammps-patch_15Jun2023/lib/colvars -I/wrkdirs/usr/ports/science/lammps/work/lammps-patch_15Jun2023/lib/molfile -I/wrkdirs/usr/ports/science/lammps/work/lammps-patch_15Jun2023/lib/qmmm -I/wrkdirs/usr/ports/science/lammps/work/lammps-patch_15Jun2023/lib/poems -I/wrkdirs/usr/ports/science/lammps/work/lammps-patch_15Jun2023/lib/atc -I/wrkdirs/usr/ports/science/lammps/work/lammps-patch_15Jun2023/lib/awpmd/systems/interact -I/wrkdirs/usr/ports/science/lammps/work/lammps-patch_15Jun2023/lib/awpmd/ivutils/include -I/wrkdirs/usr/ports/science/lammps/work/lammps-patch_15Jun2023/lib/h5md/include -isystem /usr/local/mpi/openmpi/include -isystem /usr/local/include/pytho
n3.9 -isystem /usr/local/include/voro++ -isystem /usr/local/include/eigen3 -isystem /usr/local/lib/kim-api/mod -isystem /usr/local/include/kim-api -O2 -pipe -fstack-protector-strong -isystem /usr/local/include -fno-strict-aliasing  -isystem /usr/local/include -O2 -pipe -fstack-protector-strong -isystem /usr/local/include -fno-strict-aliasing  -isystem /usr/local/include  -DNDEBUG -std=c++17 -fPIC -fexceptions -pthread -fopenmp=libomp -MD -MT CMakeFiles/lammps.dir/wrkdirs/usr/ports/science/lammps/work/lammps-patch_15Jun2023/src/AWPMD/pair_awpmd_cut.cpp.o -MF CMakeFiles/lammps.dir/wrkdirs/usr/ports/science/lammps/work/lammps-patch_15Jun2023/src/AWPMD/pair_awpmd_cut.cpp.o.d -o CMakeFiles/lammps.dir/wrkdirs/usr/ports/science/lammps/work/lammps-patch_15Jun2023/src/AWPMD/pair_awpmd_cut.cpp.o -c /wrkdirs/usr/ports/science/lammps/work/lammps-patch_15Jun2023/src/AWPMD/pair_awpmd_cut.cpp
--- CMakeFiles/lammps.dir/wrkdirs/usr/ports/science/lammps/work/lammps-patch_15Jun2023/src/AWPMD/fix_nve_awpmd.cpp.o ---
2 errors generated.
*** [CMakeFiles/lammps.dir/wrkdirs/usr/ports/science/lammps/work/lammps-patch_15Jun2023/src/AWPMD/fix_nve_awpmd.cpp.o] Error code 1

make[3]: stopped in /wrkdirs/usr/ports/science/lammps/work/.build
--- CMakeFiles/lammps.dir/wrkdirs/usr/ports/science/lammps/work/lammps-patch_15Jun2023/src/AWPMD/pair_awpmd_cut.cpp.o ---
In file included from /wrkdirs/usr/ports/science/lammps/work/lammps-patch_15Jun2023/src/AWPMD/pair_awpmd_cut.cpp:34:
In file included from /wrkdirs/usr/ports/science/lammps/work/lammps-patch_15Jun2023/lib/awpmd/systems/interact/TCP/wpmd.h:151:
/wrkdirs/usr/ports/science/lammps/work/lammps-patch_15Jun2023/lib/awpmd/ivutils/include/wavepacket.h:26:27: error: no template named 'binary_function'; did you mean '__binary_function'?
struct eq_second : public binary_function <Type, Type, Type> {
                          ^~~~~~~~~~~~~~~
                          __binary_function
/usr/include/c++/v1/__functional/binary_function.h:49:1: note: '__binary_function' declared here
using __binary_function = __binary_function_keep_layout_base<_Arg1, _Arg2, _Result>;
^
In file included from /wrkdirs/usr/ports/science/lammps/work/lammps-patch_15Jun2023/src/AWPMD/pair_awpmd_cut.cpp:34:
In file included from /wrkdirs/usr/ports/science/lammps/work/lammps-patch_15Jun2023/lib/awpmd/systems/interact/TCP/wpmd.h:151:
/wrkdirs/usr/ports/science/lammps/work/lammps-patch_15Jun2023/lib/awpmd/ivutils/include/wavepacket.h:34:33: error: no template named 'binary_function'; did you mean '__binary_function'?
struct eq_minus_second : public binary_function <Type, Type, Type> {
                                ^~~~~~~~~~~~~~~
                                __binary_function
/usr/include/c++/v1/__functional/binary_function.h:49:1: note: '__binary_function' declared here
using __binary_function = __binary_function_keep_layout_base<_Arg1, _Arg2, _Result>;
^
2 errors generated.
*** [CMakeFiles/lammps.dir/wrkdirs/usr/ports/science/lammps/work/lammps-patch_15Jun2023/src/AWPMD/pair_awpmd_cut.cpp.o] Error code 1

make[3]: stopped in /wrkdirs/usr/ports/science/lammps/work/.build
2 errors

make[3]: stopped in /wrkdirs/usr/ports/science/lammps/work/.build
*** [CMakeFiles/lammps.dir/all] Error code 2

make[2]: stopped in /wrkdirs/usr/ports/science/lammps/work/.build
1 error

make[2]: stopped in /wrkdirs/usr/ports/science/lammps/work/.build
*** [all] Error code 2

make[1]: stopped in /wrkdirs/usr/ports/science/lammps/work/.build
1 error
```

This c++17 requirement causes compilation to fail with clang-16, because it now has removed features actually removed.

There are no port patches for lammps, so c++17 comes either from lammps itself, or from some cmake files that it imports.
The external ```kokkos-4.1.00``` is used.

**Comment by akohlmey** [comment] 2023-08-04 04:22
> The external `kokkos-4.1.00` is used.

This is the "killer", because that enforces C++17. It is not really LAMMPS doing that, but Kokkos. I already mentioned that. You are on your own with this one.

While the option to compile with an external Kokkos exists in LAMMPS, it is not at all guaranteed to work and not the way that the LAMMPS developers endorse. LAMMPS is only validated with the bundled Kokkos library and often we need to make changes and apply workarounds to the bundled Kokkos, so that LAMMPS can work correctly (of course those are always submitted to the upstream version). When compiling with the embedded Kokkos version, there will be no problem with this particular old code in LAMMPS.

We will be integrating full support for Kokkos 4.x into LAMMPS with the *next* feature release. The corresponding pull request was merged today and testing is ongoing. As it turns out, the offending lines of code are easily fixed.

Your choices are clear:  either do not install the AWPMD package (it is very obscure, anyway and there is a good chance it may be removed from the distribution) or use the bundled Kokkos library.

**Closed as completed** 2023-08-04 17:04 UTC
Labels: bug, invalid
