### ISSUE TITLE
[BUG] After kim-api update to 2.2.0 lammps now fails: Imported target "PkgConfig::KIM-API" includes non-existent path

### ISSUE THREAD

**Issue by yurivict** [lammps/lammps#2489] opened 2020-11-21 21:48 UTC
```
CMake Error in CMakeLists.txt:
  Imported target "PkgConfig::KIM-API" includes non-existent path

    "/usr/local/libdata/pkgconfig/../kim-api/mod"

  in its INTERFACE_INCLUDE_DIRECTORIES.  Possible reasons include:

  * The path was deleted, renamed, or moved to another location.

  * An install or uninstall procedure did not complete successfully.

  * The installation package was faulty and references files it does not
  provide.
```

Log: http://beefy6.nyi.freebsd.org/data/121amd64-default/555803/logs/lammps-2020.10.29.log

Version: patch_29Oct2020
OS: FreeBSD 12.2
compiler: clang-10
cmake-3.18.3

**Comment by ellio167** [comment] 2020-11-22 00:02
@yurivict I believe this is an issue in the pkg-config file for the new kim-api-2.2.0 release.  Can you please create an issue there https://github.com/openkim/kim-api

**Comment by junghans** [comment] 2020-11-22 00:18
@yurivict you might what do try the patch from #2488.

**Comment by yurivict** [comment] 2020-11-22 06:40
This patch worked, thanks!

**Comment by yurivict** [comment] 2020-12-01 01:14
30Nov2020 is again broken with, and the above patch doesn't apply any more.

**Comment by akohlmey** [comment] 2020-12-01 02:25
@yurivict the pull in question request has been merged after some additional corrections to maintain backward compatibility. So no need to apply it.
Besides, I cannot reproduce your problem on either Fedora Linux or a FreeBSD 12.1 virtual machine, it also passes our compilation tests which use Ubuntu Linux and CentOS in addition.
To install the latest KIM API I did:
```
curl -o kim-api.txz https://s3.openkim.org/kim-api/kim-api-2.2.0.txz
tar -xJvvf kim-api.txz
cd kim-api-2.2.0/
mkdir build
cd build
cmake .. -DCMAKE_BUILD_TYPE=Release -DCMAKE_INSTALL_PREFIX=$HOME/.local
make 
make install
```
and then in the LAMMPS build folder (which had a working LAMMPS configuration but without KIM)
source $HOME/.local/bin/kim-api-activate
cmake . -DPKG_KIM=yes
make
```
and this worked just fine as documented.

**Comment by ellio167** [comment] 2020-12-01 02:27
The issue has to do with the debian packaging and the format of the libkim-api.pc file.  

https://github.com/openkim/kim-api/issues/57

It should be resolved with the release of kim-api-2.2.1 although this will likely still be a week or so.

**Comment by yurivict** [comment] 2020-12-01 02:31
Yes, maybe I have to just wait until ```kim-api``` will fixes it.
Before the compilation problem was gone with the patch.

**Comment by akohlmey** [comment] 2020-12-01 02:33
we won't put incorrect "fixes" into the LAMMPS distribution and the whole issue is not a LAMMPS issue in the first place, so this is now closed permanently.

**Closed by akohlmey** 2020-12-01 02:33 UTC
Labels: bug, unconfirmed
