### ISSUE TITLE
[BUG] Breaks when BUILD_MPI=OFF: undefined reference to symbol 'ompi_mpi_comm_world'

### ISSUE THREAD

**Issue by yurivict** [lammps/lammps#2065] opened 2020-05-03 23:01 UTC
OS: FreeBSD 12.1
Version: patch_15Apr2020 (with some patches from https://github.com/lammps/lammps/pull/2051)
Compiler: clang-9

```
/usr/bin/c++  -O2 -pipe -fno-omit-frame-pointer -fstack-protector-strong -isystem /usr/local/include -fno-strict-aliasing -fno-omit-frame-pointer  -isystem /usr/local/include  -O2 -pipe -fno-omit-frame-pointer -fstack-protector-strong -isystem /usr/local/include -fno-strict-aliasing -fno-omit-frame-pointer  -isystem /usr/local/include   -L/usr/local/lib -Wl,-rpath=/usr/local/lib/gcc9  -L/usr/local/lib/gcc9 -B/usr/local/bin -fstack-protector-strong -L/usr/local/lib  CMakeFiles/lmp.dir/usr/ports/science/lammps/work/lammps-patch_15Apr2020/src/main.cpp.o  -o lmp  -Wl,-rpath,/usr/ports/science/lammps/work/.build:/usr/local/lib/vtk-8.2:/usr/local/lib/qt5: liblammps.so.0 /usr/local/lib/libfftw3.so -Wl,-rpath-link,/usr/local/lib/vtk-8.2:/usr/local/lib/qt5 
/usr/local/bin/ld: CMakeFiles/lmp.dir/usr/ports/science/lammps/work/lammps-patch_15Apr2020/src/main.cpp.o: undefined reference to symbol 'ompi_mpi_comm_world'
```

All cmake arguments:
```
-DBLA_VENDOR:STRING="OpenBLAS"  -DWITH_FFMPEG:BOOL=true -DWITH_GZIP:BOOL=true -DPKG_USER-H5MD:BOOL=true -DWITH_JPEG:BOOL=true -DPKG_KIM:BOOL=true -DDOWNLOAD_KIM:BOOL=OFF -DPKG_KOKKOS:BOOL=true -DEXTERNAL_KOKKOS:BOOL=true -DPKG_LATTE:BOOL=true -DBUILD_MPI:BOOL=false -DPKG_MPIIO:BOOL=false -DPKG_USER-LB:BOOL=false -DWITH_PNG:BOOL=true -DPKG_VORONOI:BOOL=true -DPKG_USER-VTK:BOOL=true -DVTK_DIR:PATH=/usr/local/lib/vtk-8.2/cmake/vtk-8.2 -DBUILD_OMP:BOOL=true -DCMAKE_C_COMPILER:STRING="cc"  -DCMAKE_CXX_COMPILER:STRING="c++"  -DCMAKE_C_FLAGS:STRING="-O2 -pipe -fno-omit-frame-pointer  -fstack-protector-strong -isystem /usr/local/include -fno-strict-aliasing "  -DCMAKE_C_FLAGS_DEBUG:STRING="-O2 -pipe -fno-omit-frame-pointer  -fstack-protector-strong -isystem /usr/local/include -fno-strict-aliasing "  -DCMAKE_C_FLAGS_RELEASE:STRING="-O2 -pipe -fno-omit-frame-pointer  -fstack-protector-strong -isystem /usr/local/include -fno-strict-aliasing "  -DCMAKE_CXX_FLAGS:STRING="-O2 -pipe -fno-omit-frame-pointer -fstack-protector-strong -isystem /usr/local/include -fno-strict-aliasing -fno-omit-frame-pointer  -isystem /usr/local/include "  -DCMAKE_CXX_FLAGS_DEBUG:STRING="-O2 -pipe -fno-omit-frame-pointer -fstack-protector-strong -isystem /usr/local/include -fno-strict-aliasing -fno-omit-frame-pointer  -isystem /usr/local/include "  -DCMAKE_CXX_FLAGS_RELEASE:STRING="-O2 -pipe -fno-omit-frame-pointer -fstack-protector-strong -isystem /usr/local/include -fno-strict-aliasing -fno-omit-frame-pointer  -isystem /usr/local/include "  -DCMAKE_EXE_LINKER_FLAGS:STRING=" -L/usr/local/lib -Wl,-rpath=/usr/local/lib/gcc9  -L/usr/local/lib/gcc9 -B/usr/local/bin -fstack-protector-strong -L/usr/local/lib "  -DCMAKE_MODULE_LINKER_FLAGS:STRING=" -L/usr/local/lib -Wl,-rpath=/usr/local/lib/gcc9  -L/usr/local/lib/gcc9 -B/usr/local/bin -fstack-protector-strong -L/usr/local/lib "  -DCMAKE_SHARED_LINKER_FLAGS:STRING=" -L/usr/local/lib -Wl,-rpath=/usr/local/lib/gcc9  -L/usr/local/lib/gcc9 -B/usr/local/bin -fstack-protector-strong -L/usr/local/lib "  -DCMAKE_INSTALL_PREFIX:PATH="/usr/local"  -DCMAKE_BUILD_TYPE:STRING="Release"  -DTHREADS_HAVE_PTHREAD_ARG:BOOL=YES  -DCMAKE_INSTALL_RPATH_USE_LINK_PATH=YES  -DCMAKE_VERBOSE_MAKEFILE:BOOL=ON -DBUILD_SHARED_LIBS:BOOL=ON -DPKG_ASPHERE:BOOL=ON -DPKG_BODY:BOOL=ON -DPKG_CLASS2:BOOL=ON -DPKG_COLLOID:BOOL=ON -DPKG_COMPRESS:BOOL=ON -DPKG_DIPOLE:BOOL=ON -DPKG_GRANULAR:BOOL=ON -DPKG_KSPACE:BOOL=ON -DPKG_MANYBODY:BOOL=ON -DPKG_MC:BOOL=ON -DPKG_MESSAGE:BOOL=ON -DPKG_MISC:BOOL=ON -DPKG_MOLECULE:BOOL=ON -DPKG_PERI:BOOL=ON -DPKG_POEMS:BOOL=ON -DPKG_QEQ:BOOL=ON -DPKG_REPLICA:BOOL=ON -DPKG_RIGID:BOOL=ON -DPKG_SHOCK:BOOL=ON -DPKG_SPIN:BOOL=ON -DPKG_SNAP:BOOL=ON -DPKG_SRD:BOOL=ON -DPKG_USER-ATC:BOOL=ON -DPKG_USER-AWPMD:BOOL=ON -DPKG_USER-BOCS:BOOL=ON -DPKG_USER-CGDNA:BOOL=ON -DPKG_USER-MESODPD:BOOL=ON -DPKG_USER-CGSDK:BOOL=ON -DPKG_USER-COLVARS:BOOL=ON -DPKG_USER-DIFFRACTION:BOOL=ON -DPKG_USER-DPD:BOOL=ON -DPKG_USER-DRUDE:BOOL=ON -DPKG_USER-EFF:BOOL=ON -DPKG_USER-FEP:BOOL=ON -DPKG_USER-MANIFOLD:BOOL=ON -DPKG_USER-MEAMC:BOOL=ON -DPKG_USER-MGPT:BOOL=ON -DPKG_USER-MISC:BOOL=ON -DPKG_USER-MOFFF:BOOL=ON -DPKG_USER-MOLFILE:BOOL=ON -DPKG_USER-PHONON:BOOL=ON -DPKG_USER-PTM:BOOL=ON -DPKG_USER-QTB:BOOL=ON -DPKG_USER-REACTION:BOOL=ON -DPKG_USER-REAXC:BOOL=ON -DPKG_USER-SDPD:BOOL=ON -DPKG_USER-SMD:BOOL=ON -DPKG_USER-SMTBQ:BOOL=ON -DPKG_USER-SPH:BOOL=ON -DPKG_USER-TALLY:BOOL=ON -DPKG_USER-UEF:BOOL=ON -DPKG_USER-QMMM:BOOL=ON -DPKG_USER-YAFF:BOOL=ON
```

**Comment by akohlmey** [comment] 2020-05-04 00:19
This is too convoluted and complex to even try and reproduce it. Please find the minimum set of configuration options that reproduces the linker failure. And please test with full branch from PR #2051  `git clone --depth=1 -b collected-small-changes https://github.com/akohlmey/lammps.git`.  There have been numerous improvements since April 15th.

**Comment by yurivict** [comment] 2020-05-04 02:28
If you would just use the same set of options in the cmake arguments line, wouldn't this easily reproduce the problem?

**Comment by junghans** [comment] 2020-05-04 02:53
Could be any of the packages that depend on MPI itself.

**Comment by akohlmey** [comment] 2020-05-04 03:16
> If you would just use the same set of options in the cmake arguments line, wouldn't this easily reproduce the problem?

It is not just about recreating the situation, but about narrowing down, which specific combination of settings causes it.  I don't use any *BSD machines normally and only have a tiny FreeBSD virtual machine to try out and debug.  Debugging is massively slowed down.  Also, I need confirmation that this is not an issue that was already corrected (there is a good chance for that).  I am happy to fix things for as long as it is obvious and easy to isolate the cause.  However, for anything more complex I need a helping hand, regardless of the operating system used.

**Comment by yurivict** [comment] 2020-05-04 04:18
Ok, maybe I would wait until after the next patch release when all patched will be merged.

**Comment by akohlmey** [comment] 2020-05-04 12:09
Ok, then I will close this one for now. Please re-open in case the issue persists after the next patch release (possibly tomorrow) after narrowing down which specific combination of options are causing this unwanted behavior. Thanks.

**Closed by akohlmey** 2020-05-04 12:09 UTC
Labels: bug, wontfix
