### ISSUE TITLE
[BUG] INTEL package doesn't work when using sw and lj/cut hybrid pair styles

### ISSUE THREAD

**Issue by cihe13375** [lammps/lammps#3094] opened 2022-01-20 19:48 UTC
**Summary**

When using hybrid pair style of `sw` and `lj/cut` (`pair_style hybrid sw lj/cut`), the simulation cannot be run with INTEL package (`-sf intel`). Either avoid using INTEL package or change one of the pair styles (e.g. `sw` -> `tersoff`, or `lj/cut` -> `morse`) seems to let it run normally.

**LAMMPS Version and Platform**

`7Jan2022`, pre-built binary on Win10, downloaded from https://rpm.lammps.org/windows/64bit/

**Expected Behavior**

The simulation should run normally, with output written to stdout and log.lammps.

**Actual Behavior**

LAMMPS is stuck on `Setting up Verlet run ...` for a while and quit directly, with no output written.

**Steps to Reproduce**

Download the demo below and run: `lmp -i sw.in -pk intel 0 omp 1 -sf intel`

**Further Information, Files, and Links**

[demo.zip](https://github.com/lammps/lammps/files/7908047/demo.zip)

**Comment by akohlmey** [comment] 2022-01-20 21:08
@cihe13375 thanks for the bug report and the well done reproducer. I have found a simple workaround:
```
  diff --git a/src/INTEL/npair_intel.cpp b/src/INTEL/npair_intel.cpp
  index 395e50006c..76a56ef90f 100644
  --- a/src/INTEL/npair_intel.cpp
  +++ b/src/INTEL/npair_intel.cpp
  @@ -367,7 +367,7 @@ void NPairIntel::bin_newton(const int offload, NeighList *list,
               ty[u] = x[j].y;
               tz[u] = x[j].z;
               tjtype[u] = x[j].w;
  -            if (THREE) ttag[u] = tag[j];
  +            if (THREE && ttag) ttag[u] = tag[j];
             }
   
             if (FULL == 0 && TRI != 1) {
  @@ -515,7 +515,7 @@ void NPairIntel::bin_newton(const int offload, NeighList *list,
             }
   
             if (THREE) {
  -            const tagint jtag = ttag[u];
  +            const tagint jtag = ttag ? ttag[u] : tag[j];
               int flist = 0;
               if (itag > jtag) {
                 if (((itag+jtag) & 1) == 0) flist = 1;
```

But I will defer to the (main) INTEL package developer to confirm whether this is a suitable solution or to suggest a better alternative.

**Comment by cihe13375** [comment] 2022-01-21 15:36
Thanks for the reply! This fix works for me with `-pk intel 0 omp 1`. However, with more than one OpenMP thread used (e.g. `-pk intel 0 omp 2`) LAMMPS still seems to stuck on `Setting up Verlet run ...` and crash. It's probably not a big issue though since `mpirun` still works. (I tested it on a linux machine since I have no experience of compiling LAMMPS on Windows)

**Comment by akohlmey** [comment] 2022-01-21 16:29
@cihe13375 here is a more extensive change that eliminates the (unreliable) tag caching altogether:
```
  diff --git a/src/INTEL/npair_intel.cpp b/src/INTEL/npair_intel.cpp
  index 395e50006c..67cd2517e4 100644
  --- a/src/INTEL/npair_intel.cpp
  +++ b/src/INTEL/npair_intel.cpp
  @@ -310,7 +309,6 @@ void NPairIntel::bin_newton(const int offload, NeighList *list,
         flt_t * _noalias const tz = ncachez + toffs;
         int * _noalias const tj = ncachej + toffs;
         int * _noalias const tjtype = ncachejtype + toffs;
  -      tagint * _noalias const ttag = ncachetag + toffs;
   
         flt_t * _noalias itx;
         flt_t * _noalias ity;
  @@ -367,7 +365,6 @@ void NPairIntel::bin_newton(const int offload, NeighList *list,
               ty[u] = x[j].y;
               tz[u] = x[j].z;
               tjtype[u] = x[j].w;
  -            if (THREE) ttag[u] = tag[j];
             }
   
             if (FULL == 0 && TRI != 1) {
  @@ -515,7 +512,7 @@ void NPairIntel::bin_newton(const int offload, NeighList *list,
             }
   
             if (THREE) {
  -            const tagint jtag = ttag[u];
  +            const tagint jtag = tag[j];
               int flist = 0;
               if (itag > jtag) {
                 if (((itag+jtag) & 1) == 0) flist = 1;

```

**Comment by cihe13375** [comment] 2022-01-21 19:51
Thanks, it fixed the aforementioned issue. I found another issue though (sorry for raising them successively, feel free to close this if you think it's time to stop), where it crashes if there're more than one `run` in the script. For example, substitute `run 100` in the demo with
```
run 50
run 50
```
and it will crash at the second `run 50`. It also crash with a setup like this:
```
run xxxx
unfix something
fix something_other
run yyyy
```

**Comment by akohlmey** [comment] 2022-01-21 21:10
@cihe13375 unlike the previous issues listed here, I don't see a straightforward way to address this. My best suggestion is to avoid triggering the issue by restarting:

```
[...]
run 50
write_restart after_first_run.restart
clear
read_restart after_first_run.restart
pair_style hybrid sw lj/cut 10.0
pair_coeff * * sw Si.sw Si NULL
pair_coeff 1 2 lj/cut 5.0 3.5
pair_coeff 2 2 lj/cut 5.0 3.5
fix fixname all nve
run 50
```

If you are not making any changes to the system (e.g. adding/changing/removing fixes or atoms or pair styles) you can also append `pre no` to the second run command and also avoid the crash without having to restart.

**Comment by wmbrownIntel** [comment] 2022-01-25 05:51
I think we should do below to fix the tag cache allocation and revert the other changes. With this fix, I didn't reproduce the multiple run issue, but if it persists, let me know and I will pursue it further:

```
diff --git a/src/INTEL/fix_intel.cpp b/src/INTEL/fix_intel.cpp
index 6a848a366e..a201386724 100644
--- a/src/INTEL/fix_intel.cpp
+++ b/src/INTEL/fix_intel.cpp
@@ -447,7 +447,7 @@ void FixIntel::pair_init_check(const bool cdmessage)
   #endif
 
   int need_tag = 0;
-  if (atom->molecular != Atom::ATOMIC) need_tag = 1;
+  if (atom->molecular != Atom::ATOMIC || three_body_neighbor()) need_tag = 1;
 
   // Clear buffers used for pair style
   char kmode[80];
diff --git a/src/INTEL/intel_buffers.cpp b/src/INTEL/intel_buffers.cpp
index 3470c18db8..cbbc609fc0 100644
--- a/src/INTEL/intel_buffers.cpp
+++ b/src/INTEL/intel_buffers.cpp
@@ -207,8 +207,6 @@ void IntelBuffers<flt_t, acc_t>::free_nmax()
 template <class flt_t, class acc_t>
 void IntelBuffers<flt_t, acc_t>::_grow_nmax(const int offload_end)
 {
-  if (lmp->atom->molecular) _need_tag = 1;
-  else _need_tag = 0;
   #ifdef _LMP_INTEL_OFFLOAD
   free_nmax();
   int size = lmp->atom->nmax;
diff --git a/src/INTEL/npair_intel.cpp b/src/INTEL/npair_intel.cpp
index 67cd2517e4..2fffb2353a 100644
--- a/src/INTEL/npair_intel.cpp
+++ b/src/INTEL/npair_intel.cpp
@@ -309,6 +309,7 @@ void NPairIntel::bin_newton(const int offload, NeighList *list,
       flt_t * _noalias const tz = ncachez + toffs;
       int * _noalias const tj = ncachej + toffs;
       int * _noalias const tjtype = ncachejtype + toffs;
+      tagint * _noalias const ttag = ncachetag + toffs;
 
       flt_t * _noalias itx;
       flt_t * _noalias ity;
@@ -365,6 +366,7 @@ void NPairIntel::bin_newton(const int offload, NeighList *list,
             ty[u] = x[j].y;
             tz[u] = x[j].z;
             tjtype[u] = x[j].w;
+            if (THREE) ttag[u] = tag[j];
           }
 
           if (FULL == 0 && TRI != 1) {
@@ -512,7 +514,7 @@ void NPairIntel::bin_newton(const int offload, NeighList *list,
           }
 
           if (THREE) {
-            const tagint jtag = tag[j];
+            const tagint jtag = ttag[u];
             int flist = 0;
             if (itag > jtag) {
               if (((itag+jtag) & 1) == 0) flist = 1;

```

**Comment by akohlmey** [comment] 2022-01-25 12:16
> I think we should do below to fix the tag cache allocation and revert the other changes. With this fix, I didn't reproduce the multiple run issue, but if it persists, let me know and I will pursue it further:
> 

The tag caching issue seems resolved with this change, but the multi-run issue not and the symptoms are the same as before.
There is a segfault on the second run command unless that command includes "pre no". As before the "numneighhalf pointer is initialized to a bogus value.

```
Core was generated by `./lmp -in sw.in -pk intel 0 omp 1 -sf intel -log log.omp'.
Program terminated with signal SIGSEGV, Segmentation fault.
#0  0x00007fa57750a3be in LAMMPS_NS::PairSWIntel::_ZN9LAMMPS_NS11PairSWIntel4evalILi1ELi1ELi1EfdEEviiPNS_12IntelBuffersIT2_T3_EERKNS0_10ForceConstIS3_EEii._omp_fn.0(void) ()
    at /home/akohlmey/compile/lammps/src/INTEL/pair_sw_intel.cpp:323
323	        const int jnumhalf = numneighhalf[ii];
(gdb) print numneighhalf
$1 = (const int * const __restrict__) 0x1

```

Some info about the executable:
```
OS: Linux "Fedora Linux 35 (Thirty Five)" 5.15.16-200.fc35.x86_64 x86_64

Compiler: GNU C++ 11.2.1 20211203 (Red Hat 11.2.1-7) with OpenMP 4.5
C++ standard: C++14
MPI v3.1: MPICH Version:	3.4.1
MPICH Release date:	Fri Jan 22 14:17:48 CST 2021
MPICH ABI:	13:10:1

Accelerator configuration:

KOKKOS package API: OpenMP Serial
KOKKOS package precision: double
OPENMP package API: OpenMP
OPENMP package precision: double
INTEL package API: OpenMP
INTEL package precision: single mixed double

Active compile time flags:

-DLAMMPS_GZIP
-DLAMMPS_PNG
-DLAMMPS_JPEG
-DLAMMPS_FFMPEG
-DLAMMPS_EXCEPTIONS
-DLAMMPS_SMALLBIG
sizeof(smallint): 32-bit
sizeof(imageint): 32-bit
sizeof(tagint):   32-bit
```

**Comment by akohlmey** [comment] 2022-01-26 17:05
reopen because of still pending multi-run issue

**Comment by akohlmey** [comment] 2022-02-12 01:31
@wmbrownIntel do you have any suggestion to solve this?
Or should I just add a note to the documentation that when trying multiple runs, "pre no" or restarting may be required?

**Comment by wmbrownIntel** [comment] 2022-02-14 07:50
The problem seems to be due to neighbor->nrequest changing from the copy_neighbor_info() in the first and second run (causing a skip list index to exceed local array storage in intel skip list variant). I need to spend a little time to review the logic for all of this. Will try to get a fix in the next couple of days...

**Closed** 2022-02-19 10:55 UTC
Labels: bug, user_intel_package
