### ISSUE TITLE
[Feature Request] Allow delete_atoms to work on specific species or group

### ISSUE THREAD

**Issue by mjclarke94** [lammps/lammps#1425] opened 2019-04-11 09:22 UTC
**Summary**
The delete atoms command currently is indiscriminate towards the group or species of an atom, and simply works on a given geometric region. It would be useful to have the option to discriminate between types of atoms.

**Use case**
As an example use case, when calculating Li diffusion coefficients through a cathode, it is necessary to remove a small fraction of Li atoms from the pristine system. The porosity command seems perfect for this, but currently deletes atoms indiscriminately. It would be useful to be able to delete a given fraction of atoms of a given type, making what is normally a manual operation on the input file something that can be done in one line and seeded for provenance.

**Comment by mkanski** [comment] 2019-04-12 08:42
It's not entirely true. Delete_atoms command works on groups which can be defined by an atom-style variable. The code below should delete approx. half of atoms of type 1:

`variable delete atom (type==1)*(random(0,1,214365)<0.5)`
`group delete variable delete`
`delete_atoms group delete`

The created variable is equal to 1 if an atom is of type 1 and a random number is lower than 0.5 and such atoms will be deleted. If the number of type 1 atoms is sufficiently high, the commands should delete approx. half of them.

**Comment by mjclarke94** [comment] 2019-04-13 10:36
Hi @mkanski. Forgive my ignorance, but follow up question: 

Is it possible following this to update the charge of a group of atoms? I just tried your and it deletes approximately the right number of atoms, but I can't know ahead of time exactly how many will be deleted. I'd then need to charge compensate for the removal of these atoms by slightly increasing the charge of another group of atoms. Is there a way to:
a) Do a calculation to work out the correct new charge for the redox active species
b) Update the charge of the correct atoms accordingly

**Comment by jrgissing** [comment] 2019-04-16 04:54
although probably not relevant to the use case you mentioned, fix bond/react can also delete specific molecules, identified by their topology

**Comment by akohlmey** [comment] 2019-04-30 19:51
Been thinking about this for a bit. In principle the issue is resolved by using the strategy proposed by @mkanski , but it seems to me, this would be a more obvious solution, if we add support for using atom style variables directly. I don't want to add sub-options to the porosity keyword, as that would make things more complex and possibly confusing. Opinions anybody?

**Comment by mkanski** [comment] 2019-05-06 07:36
I think that the best solution for a new user would be to make `porosity` work on groups. This would include the existing behavior + atom style variables + other options of groups like subtractions or dynamic groups (if one would like to delete atoms after some MD). 
Of course there is a problem with the backward compatibility, but it can be maintained by introducing an optional keyword for `porosity`, i.e.
`delete_atoms porosity name 0.5 12412 group` would mean that `name` is a group. Without the new keyword, `name` would relate to region as it is currently.

**Comment by xuwenwu** [comment] 2019-10-23 22:50
Yeah, I agree with mkanski.

**Closed** 2022-05-04 17:50 UTC
Labels: enhancement
