### ISSUE TITLE
Broken with VORONOI option

### ISSUE THREAD

**Issue by yurivict** [lammps/lammps#1187] opened 2018-10-31 05:55 UTC
```
/usr/ports/science/lammps/work/lammps-stable_22Aug2018/src/VORONOI/compute_voronoi_atom.cpp:83:14: error: member access into incomplete type 'LAMMPS_NS::Error'
        error->all(FLERR,"Illegal compute voronoi/atom command");
             ^
/usr/ports/science/lammps/work/lammps-stable_22Aug2018/src/lammps.h:25:9: note: forward declaration of 'LAMMPS_NS::Error'
  class Error *error;            // error handling
        ^
/usr/ports/science/lammps/work/lammps-stable_22Aug2018/src/VORONOI/compute_voronoi_atom.cpp:90:33: error: member access into incomplete type 'LAMMPS_NS::Error'
      if (iarg + 2 > narg) error->all(FLERR,"Illegal compute voronoi/atom command");
                                ^
/usr/ports/science/lammps/work/lammps-stable_22Aug2018/src/lammps.h:25:9: note: forward declaration of 'LAMMPS_NS::Error'
  class Error *error;            // error handling
        ^
```

Version 22Aug2018 on FreeBSD 11.2 amd64
voro++-0.4.6

**Comment by yurivict** [comment] 2018-10-31 06:00
Other files also have this problem:
```
/usr/ports/science/lammps/work/lammps-stable_22Aug2018/src/LATTE/fix_latte.cpp:60:10: error: member access into incomplete type 'LAMMPS_NS::Error'
    error->all(FLERR,"Must use units metal with fix latte command");
         ^
```

Enabling some options trigger this problem, so it isn't just ```VORONOI```.

**Comment by akohlmey** [comment] 2018-10-31 06:03
This issue has to be caused by using -I flags that make the compiler import the wrong error.h file. It cannot be a LAMMPS issue. LAMMPS has been using the same setup to compile packages for many, many years. compute_voronoi_atom.cpp has the necessary `#include "error.h"` statement and this code has been the same for over 5 years.

You need to describe in more detail how exactly you are configuring/building LAMMPS.

**Comment by yurivict** [comment] 2018-10-31 06:10
In the FreeBSD port, I am trying to add some build options and hit this problem. Without options it builds fine.

It is configured with this command:
```cmake -DWITH_FFMPEG:BOOL=true -DWITH_GZIP:BOOL=true -DWITH_JPEG:BOOL=true -DPKG_LATTE:BOOL=true -DBUILD_OMP:BOOL=true -DWITH_PNG:BOOL=true -DPKG_VORONOI:BOOL=false -DCMAKE_C_COMPILER:STRING="clang60"  -DCMAKE_CXX_COMPILER:STRING="clang++60"  -DCMAKE_C_FLAGS:STRING="-O2 -pipe -fno-omit-frame-pointer  -fstack-protector -fno-strict-aliasing "  -DCMAKE_C_FLAGS_DEBUG:STRING="-O2 -pipe -fno-omit-frame-pointer  -fstack-protector -fno-strict-aliasing "  -DCMAKE_C_FLAGS_RELEASE:STRING="-O2 -pipe -fno-omit-frame-pointer  -fstack-protector -fno-strict-aliasing "  -DCMAKE_CXX_FLAGS:STRING="-O2 -pipe -fno-omit-frame-pointer -fstack-protector -fno-strict-aliasing -fno-omit-frame-pointer  "  -DCMAKE_CXX_FLAGS_DEBUG:STRING="-O2 -pipe -fno-omit-frame-pointer -fstack-protector -fno-strict-aliasing -fno-omit-frame-pointer  "  -DCMAKE_CXX_FLAGS_RELEASE:STRING="-O2 -pipe -fno-omit-frame-pointer -fstack-protector -fno-strict-aliasing -fno-omit-frame-pointer  "  -DCMAKE_EXE_LINKER_FLAGS:STRING=" -Wl,-rpath=/usr/local/lib/gcc7  -L/usr/local/lib/gcc7 -B/usr/local/bin -fstack-protector "  -DCMAKE_MODULE_LINKER_FLAGS:STRING=" -Wl,-rpath=/usr/local/lib/gcc7  -L/usr/local/lib/gcc7 -B/usr/local/bin -fstack-protector "  -DCMAKE_SHARED_LINKER_FLAGS:STRING=" -Wl,-rpath=/usr/local/lib/gcc7  -L/usr/local/lib/gcc7 -B/usr/local/bin -fstack-protector "  -DCMAKE_INSTALL_PREFIX:PATH="/usr/local"  -DCMAKE_BUILD_TYPE:STRING="Release"  -DTHREADS_HAVE_PTHREAD_ARG:BOOL=YES  -DCMAKE_INSTALL_RPATH_USE_LINK_PATH=YES  -DCMAKE_VERBOSE_MAKEFILE:BOOL=ON```

**Comment by akohlmey** [comment] 2018-10-31 06:14
CMake support in version 22 August 2018 is experimental and has known issues. Please try with the latest patch release.

**Comment by akohlmey** [comment] 2018-10-31 06:31
As mentioned before, this must be due to how you are doing the configuration. Possibly you are overwriting some required setting that switches the order in which include directories are looked for. I currently don't see how this is a LAMMPS problem and what would need to be done to address this.

**Comment by yurivict** [comment] 2018-10-31 07:12
I found the combination of arguments that trigger this problem:
```-DWITH_JPEG:BOOL=true -DWITH_PNG:BOOL=true -DBUILD_OMP:BOOL=true -DPKG_VORONOI:BOOL=false```.

It doesn't look like the port is doing anything unusual, just these options when enabled together trigger this failure.

**Comment by akohlmey** [comment] 2018-10-31 07:30
@yurivict sorry, but i cannot reproduce this.
`mkdir build-test ; cd build-test ; cmake ../cmake -DWITH_JPEG:BOOL=true -DWITH_PNG:BOOL=true -DBUILD_OMP:BOOL=true -DPKG_VORONOI:BOOL=false ; make -j4` works just fine on my machine.

**Comment by yurivict** [comment] 2018-10-31 07:33
Sorry, it was a typo. I meant ```-DWITH_JPEG:BOOL=true -DWITH_PNG:BOOL=true -DBUILD_OMP:BOOL=true -DPKG_VORONOI:BOOL=true```. Not sure if you will be able to reproduce, but this is what triggers the error for me.

**Comment by akohlmey** [comment] 2018-10-31 07:44
same difference. if i cannot reproduce it, i cannot debug it. please trigger a selective recompile of the voronoi compile style and capture the actual compilation flags with: `touch ../src/VORONOI/compute_voronoi_atom.cpp ; make VERBOSE=1`

on my machine here i get:
```
Scanning dependencies of target lmp
make[2]: Leaving directory '/home/akohlmey/compile/lammps/build-most'
make -f CMakeFiles/lmp.dir/build.make CMakeFiles/lmp.dir/build
make[2]: Entering directory '/home/akohlmey/compile/lammps/build-most'
[  0%] Building CXX object CMakeFiles/lmp.dir/home/akohlmey/compile/lammps/src/VORONOI/compute_voronoi_atom.cpp.o
/usr/lib64/ccache/c++  -DLAMMPS_FFMPEG -DLAMMPS_GZIP -DLAMMPS_JPEG -DLAMMPS_MEMALIGN=64 -DLAMMPS_PNG -DLAMMPS_SMALLBIG -I/usr/include/mpich-x86_64 -I/home/akohlmey/compile/lammps/src/VORONOI -I/home/akohlmey/compile/lammps/src -I/home/akohlmey/compile/lammps/build-most/styles  -fopenmp -O2 -DNDEBUG   -o CMakeFiles/lmp.dir/home/akohlmey/compile/lammps/src/VORONOI/compute_voronoi_atom.cpp.o -c /home/akohlmey/compile/lammps/src/VORONOI/compute_voronoi_atom.cpp
```

**Comment by yurivict** [comment] 2018-10-31 07:55
```
/usr/local/bin/clang++60  -DLAMMPS_JPEG -DLAMMPS_MEMALIGN=64 -DLAMMPS_PNG -DLAMMPS_SMALLBIG -I/usr/local/mpi/openmpi/include -I/usr/local/include -I/usr/local/include/voro++ -I/usr/ports/science/lammps/work/lammps-stable_22Aug2018/src/VORONOI -I/usr/ports/science/lammps/work/lammps-stable_22Aug2018/src -I/usr/ports/science/lammps/work/.build/styles -O2 -pipe -fno-omit-frame-pointer -fstack-protector -fno-strict-aliasing -fno-omit-frame-pointer -fopenmp=libomp -O2 -pipe -fno-omit-frame-pointer -fstack-protector -fno-strict-aliasing -fno-omit-frame-pointer -o CMakeFiles/lmp.dir/usr/ports/science/lammps/work/lammps-stable_22Aug2018/src/VORONOI/compute_voronoi_atom.cpp.o -c /usr/ports/science/lammps/work/lammps-stable_22Aug2018/src/VORONOI/compute_voronoi_atom.cpp
/usr/ports/science/lammps/work/lammps-stable_22Aug2018/src/VORONOI/compute_voronoi_atom.cpp:83:14: error: member access into incomplete type 'LAMMPS_NS::Error'
        error->all(FLERR,"Illegal compute voronoi/atom command");
             ^
```

**Comment by akohlmey** [comment] 2018-10-31 07:55
BTW: there should be no need to explicitly set `-DWITH_JPEG:BOOL=true -DWITH_PNG:BOOL=true -DBUILD_OMP:BOOL=true` those will be autodetected and enabled if available and working. Does compilation work, if you drop those?

**Comment by yurivict** [comment] 2018-10-31 07:55
> Does compilation work, if you drop those?

It works if they are ```false```.

**Comment by akohlmey** [comment] 2018-10-31 07:56
Just don't set them.

**Comment by akohlmey** [comment] 2018-10-31 07:58
Please check your `/usr/local/include` folder. does it contain a file `error.h`?

**Comment by yurivict** [comment] 2018-10-31 08:03
> Just don't set them.

It fails when they aren't set.

> Please check your /usr/local/include folder. does it contain a file error.h?

Yes, such file exists.
```
$ pkg which /usr/local/include/error.h 
/usr/local/include/error.h was installed by package ga-5.7_3
```
I'll delete it and will label the port as conflicting with ```ga```.

**Comment by yurivict** [comment] 2018-10-31 08:04
But this is also a bug in ```lammps``` because you have a wrong include directories order. Your local directories should go first.

**Comment by akohlmey** [comment] 2018-10-31 08:16
can you please check, if the following change resolves the issue?
```
diff --git a/cmake/CMakeLists.txt b/cmake/CMakeLists.txt
index b3c0a70e4..418bdd0db 100644
--- a/cmake/CMakeLists.txt
+++ b/cmake/CMakeLists.txt
@@ -193,6 +193,8 @@ if(PKG_MEAM OR PKG_USER-H5MD OR PKG_USER-QMMM OR PKG_USER-SCAFACOS)
   enable_language(C)
 endif()
 
+include_directories(${LAMMPS_SOURCE_DIR})
+
 # do MPI detection after language activation, if MPI for these language is required
 find_package(MPI QUIET)
 option(BUILD_MPI "Build MPI version" ${MPI_FOUND})
@@ -1166,7 +1168,6 @@ set(LAMMPS_STYLE_HEADERS_DIR ${CMAKE_CURRENT_BINARY_DIR}/styles)
 
 GenerateStyleHeaders(${LAMMPS_STYLE_HEADERS_DIR})
 
-include_directories(${LAMMPS_SOURCE_DIR})
 include_directories(${LAMMPS_STYLE_HEADERS_DIR})
 
 ######################################
```

**Comment by akohlmey** [comment] 2018-10-31 08:34
Thanks for your perseverance and quick feedback. The change will be included in the next LAMMPS patch.
You should probably also drop a line to the global arrays folks (i assume that is what is in the ga package, right?) so that they install their headers in a subfolder (e.g. `/usr/local/include/ga/error.h`)
so that rather than including `error.h` one would incllude `ga/error.h` and conflicts like this would become less probable.

**Closed** 2018-10-31 16:13 UTC
Labels: bug, cmake

**Comment by yurivict** [comment] 2018-10-31 16:30
Thanks for your fast fix!

I already wrote to GlobalArrays folks last night.

Cheers.
