### ISSUE TITLE
[BUG] Wrong Python module install path on Fedora36

### ISSUE THREAD

**Issue by strizhkindenis** [lammps/lammps#3429] opened 2022-09-04 19:36 UTC
**Summary**

When building lammps on Fedora36 with `-D BUILD_SHARED_LIBS=on -D LAMMPS_EXCEPTIONS=on -D PKG_PYTHON=on` lammps Python module installs into `.local/local/lib` instead of `.local/lib`

**LAMMPS Version and Platform**

Fedora linux version 36
lammps release branch commit: 883a25bbd847f66d663dbb61381bdbdb9922c574

**Expected Behavior**

Python moudule installs into `.local/lib/pythonX.X/site-packages/lammps` and it works on `import lammps`

**Actual Behavior**

For some reason it installs into `.local/local/lib/pythonX.X/site-packages/lammps` and Python can't find the module.

```shell
running install
/usr/lib/python3.10/site-packages/setuptools/command/install.py:34: SetuptoolsDeprecationWarning: setup.py install is deprecated. Use build and pip and other standards-based tools.
  warnings.warn(
running install_lib
creating /home/denis/.local/local
creating /home/denis/.local/local/lib
creating /home/denis/.local/local/lib/python3.10
creating /home/denis/.local/local/lib/python3.10/site-packages
creating /home/denis/.local/local/lib/python3.10/site-packages/lammps
...
```

Though, if I use `make install-python` command it installs properly with `pip` into `.local/lib/pythonX.X/site-packages/lammps`

**Comment by junghans** [comment] 2022-09-04 23:25
Hmm, the issue must be somewhere in our `setup.py` as we are using that to install the python module in CMake:
https://github.com/lammps/lammps/blob/8315f9996b2f32aebe859bffd2cd09e9ded9b877/cmake/CMakeLists.txt#L852

**Comment by junghans** [comment] 2022-09-05 13:05
@denisstrizhkin if you install the lammps package using `dnf` is the python module in the right place?

**Comment by akohlmey** [comment] 2022-09-05 15:43
> Hmm, the issue must be somewhere in our `setup.py` as we are using that to install the python module in CMake:
> 
> https://github.com/lammps/lammps/blob/8315f9996b2f32aebe859bffd2cd09e9ded9b877/cmake/CMakeLists.txt#L852

FWIW, the code used in "make install-python" calls install.py which has been 'modernized' to a) create a virtual environment for building, b) install/update pip, build, wheel, setuptools (i.e. the contents of python/wheel_requirements.txt), c) use `python -m build` to create a wheel with some trickery to include the LAMMPS shared library) and finally d) use `python -m pip` to install the created wheel`. Not elegant, but seems to be working for all platforms now.

**Comment by strizhkindenis** [comment] 2022-09-05 16:05
By using `sudo dnf install python3-lammps` it installs into `/usr/lib/python3.10/site-packages/lammps`.

`import lammps` works but I get this error:
```shell
OSError: liblammps.so: cannot open shared object file: No such file or directory
```
on `lmp = lammps.lammps()`.
`export LD_LIBRARY_PATH=/usr/lib64` does not help.
Though `/usr/lib64/liblammps.so.0` is present.

This is on clean fedora36 vm

**Comment by strizhkindenis** [comment] 2022-09-05 16:07
But I don't think user home install is possible with `dnf`.

**Comment by junghans** [comment] 2022-09-06 03:26
> By using `sudo dnf install python3-lammps` it installs into `/usr/lib/python3.10/site-packages/lammps`.
> 
> `import lammps` works but I get this error:
> 
> ```shell
> OSError: liblammps.so: cannot open shared object file: No such file or directory
> ```
> 
> on `lmp = lammps.lammps()`. `export LD_LIBRARY_PATH=/usr/lib64` does not help. Though `/usr/lib64/liblammps.so.0` is present.
> 
> This is on clean fedora36 vm

I think the unnumbered `liblammps.so` symlink is part of the devel package - we should fix that dependency....

> But I don't think user home install is possible with `dnf`.

Correct.

**Comment by junghans** [comment] 2022-09-06 03:30
> > Hmm, the issue must be somewhere in our `setup.py` as we are using that to install the python module in CMake:
> > https://github.com/lammps/lammps/blob/8315f9996b2f32aebe859bffd2cd09e9ded9b877/cmake/CMakeLists.txt#L852
> 
> FWIW, the code used in "make install-python" calls install.py which has been 'modernized' to a) create a virtual environment for building, b) install/update pip, build, wheel, setuptools (i.e. the contents of python/wheel_requirements.txt), c) use `python -m build` to create a wheel with some trickery to include the LAMMPS shared library) and finally d) use `python -m pip` to install the created wheel`. Not elegant, but seems to be working for all platforms now.

Seems pretty convoluted to me, original cmake just copied files around during installation, not sure why that was changed. But this more a question for @rbberger.

**Comment by rbberger** [comment] 2022-09-06 05:20
Probably related to this: https://discuss.python.org/t/linux-distro-patches-to-sysconfig-are-changing-pip-install-prefix-outside-virtual-environments/18240

Historically speaking: `make install-python` was designed for the use case that motivated this issue. So a regular user doing a local CMake build and installation into their home. `make install` is targeted for packaging or virtual environments.

Nevertheless, it's a pain point that there are two python installation methods and neither of them bothers about the other one. We should try to consolidate.

The CMake `install` one installs using the old way with the outdated `setup.py` way (we're already getting a warning that we should stop doing that) and apparently doesn't take the special case of  `$HOME/.local` prefix into account. Replacing it with equivalent `pip install --prefix=${CMAKE_INSTALL_PREFIX} --root=\$ENV{DESTDIR}/ .` silences that warning, but produces the same issue on F36. It could be dealt with by figuring out the right folder during CMake time, and then using `pip install --target` to install a generated wheel in the right place.

The "modern" approach used in `install-python` does seem more reliable, but it needs quite a few extras (venv, wheel, build) to accomplish its task. Its main deficiency is that it doesn't take `CMAKE_INSTALL_PREFIX` into account. As convoluted as it seems, it does look like the way forward with some tweaks, transforming it into the right CMake phases (configure, build, install).

The first step along consolidation I see would be to split up installation from the build. So what would need to happen is that the wheel always gets created during `make`, possibly controlled via a CMake option, while `make install` then just installs the wheel at the right prefix.

**Comment by akohlmey** [comment] 2022-10-07 21:38
> Historically speaking: `make install-python` was designed for the use case that motivated this issue. So a regular user doing a local CMake build and installation into their home. `make install` is targeted for packaging or virtual environments.

Not quite. "make install-python" is for the case of somebody compiling LAMMPS locally (regardless of the build method) *without* the desire to install the LAMMPS executable or library into a path somewhere, but with the wish to use the LAMMPS Python module. So it produces a self-contained wheel, but lacks anything that is beyond the needs of running the Python module.

"make install" should work if a user does a "local" installation into `${HOME}/.local` (which is the default setting in the CMake build and the modern equivalent of the /usr/local prefix that is default for autoconf scripts and the GNU software etc.) or a system wide installation either into /usr or some other area.

With the latest changes in PR #3456 this is now working for me while retaining the option to redirect the installation with ${DESTDIR}.

@denisstrizhkin the pull request will be merged soon and then you can try out with the develop branch and report, whether your issue is resolved (it seems for me on Fedora 36 with all updates).

**Closed as completed** 2022-10-08 21:21 UTC
Labels: bug

**Comment by strizhkindenis** [comment] 2022-10-10 11:04
Thanks everyone. I can confirm that develop branch works as expected for me. Tested on clean Fedora36 WM.
