### ISSUE TITLE
[BUG] LAMMPS on GPU core dumps reading data file

### ISSUE THREAD

**Issue by cmahrens** [lammps/lammps#4170] opened 2024-05-23 01:09 UTC
**Summary**

LAMMPS built for GPU core dumps while reading in my data file while freeing an invalid pointer.  Data file is read fine on CPU.

**LAMMPS Version and Platform**

LAMMPS (2 Aug 2023 - Update 2)
commit 27e8d0f19cfd60ff513828af74d07d2c8f3c4451 (HEAD -> stable, tag: stable_2Aug2023_update2, tag: patch_2Aug2023_update2, origin/stable)
Merge: ce756540e8 9befd421ca
Author: Axel Kohlmeyer <akohlmey@gmail.com>
Date:   Thu Dec 14 21:09:30 2023 -0500

    Merge pull request #3933 from lammps/maintenance
    
    Second Set of Collected Bug Fixes and Maintenance Updates for 2 August 2023 Stable release

Platform:

CPU standard: AMD Rome EPYC 7H12
GPU : AMD Rome EPYC 7713 + 4 NVIDIA A100 Tensor Core
HPE Cray Shasta

**Expected Behavior**

Should read data file and run simulation to completion.

**Actual Behavior**

Reads data file and runs to completion on CPU.  On GPU it core dumps when reading the data file.

LAMMPS_COMMAND: srun -n 1 lmp -k on g 1 -sf kk -pk kokkos -in in.lammps 
LAMMPS (2 Aug 2023 - Update 2)
KOKKOS mode with Kokkos version 3.7.2 is enabled (src/KOKKOS/kokkos.cpp:108)
  will use up to 1 GPU(s) per node
  using 1 OpenMP thread(s) per MPI task
Reading data file ...
  orthogonal box = (-200 -200 -200) to (200 200 200)
  1 by 1 by 1 MPI processor grid
  reading atoms ...
  100 atoms
  scanning bonds ...
free(): invalid pointer
srun: error: nid001245: task 0: Aborted (core dumped)
srun: Terminating StepId=10959771.1
LAMMPS Run Completed TotalElapsed 4 = 1716423600 - 1716423604

**Steps to Reproduce**

lmp -k on g 1 -sf kk -pk kokkos -in in.lammps 

in.lammps and random_coil_100_1.dat attached 

**Further Information, Files, and Links**

I had someone from the institutional computing team here at LANL also test it and they got the same results.

[attachments.zip](https://github.com/lammps/lammps/files/15410154/attachments.zip)

**Comment by akohlmey** [comment] 2024-05-23 01:16
@cmahrens please try using the "develop" branch. GPU/Kokkos support is a fast moving target, so using the latest versions of the sources can have addressed issues not fixed in the stable/maintenance version.

Since your failing job dumps a core file, can you retrieve and load the core dump with the executable into gdb and produce a stack trace? That could help identify the location of the failure and simplify determining whether this can be addressed for the stable version and whether it still needs to be looked into for the development branch.

**Comment by cmahrens** [comment] 2024-05-23 01:21
@akohlmey 

Here is the gdb output.

[gdb.out.zip](https://github.com/lammps/lammps/files/15410275/gdb.out.zip)

I will try to reproduce it on develop branch and get back to you.

**Comment by stanmoore1** [comment] 2024-05-23 17:47
@cmahrens  I can reproduce the segfault, will debug.

**Comment by stanmoore1** [comment] 2024-05-23 17:54
It is failing here: https://github.com/lammps/lammps/blob/develop/src/atom.cpp#L1008-L1039. Should be an easy fix, just need to handle the memory correctly for Kokkos.

**Comment by cmahrens** [comment] 2024-05-23 18:30
Thank you.  That jives with our experience here at LANL.  Someone from institutional computing also tried it on the develop branch and it failed for the GPU case.

**Comment by stanmoore1** [comment] 2024-05-23 19:20
@cmahrens #4172 fixes the memory issue. However, you also need #4167 for hybrid bond styles.

@megmcca I'm thinking it would be good to merge #4167 now, and then you can submit a new PR with hybrid angle/dihedral/improper when they are ready.

**Comment by megmcca** [comment] 2024-05-23 20:09
@stanmoore1 merging #4167 sounds good to get things rolling with hybrid bond

**Closed as completed** 2024-05-23 21:56 UTC
Labels: bug

**Comment by cmahrens** [comment] 2024-05-23 22:48
@stanmoore1 Thank you!

**Comment by stanmoore1** [comment] 2024-06-06 19:02
@cmahrens this should all work now with the the latest `develop` branch (KOKKOS support for hybrid bonds 
 in https://github.com/lammps/lammps/pull/4167 has been merged). Let us know if you see any more issues.

**Comment by cmahrens** [comment] 2024-06-15 03:01
@stanmoore1: I hadn't merged in 4167 yet and then hit the issue with hybrid bond styles just today on a 100k atom, 100k constraint run, so downloaded and tried the latest develop branch and it seems to fix it for me.  Thank you again!
