### ISSUE TITLE
[BUG] hybrid/overlay with KOKKOS overwrites atom forces, rather than sums them

### ISSUE THREAD

**Issue by bnebgen-LANL** [lammps/lammps#3936] opened 2023-10-10 19:35 UTC
**Summary**

When calling hybrid/overlay with KOKKOS package, the second potential replaces atom forces rather then adds to them.

**LAMMPS Version and Platform**

LAMMPS (2 Aug 2023 - Development - patch_2Aug2023-540-gc0ace4aa4b)'

Note: This bug is NOT present in LAMMPS (28 Mar 2023 - Development)

**Expected Behavior**

When running the attached input we expect to see forces being applied by the LJ potential which has a 20 angstrom cutoff.

**Actual Behavior**

When running the attached input with KOKKOS we see all forces are zero, because they have been overwritten by the extremely small cutoff zbl potential.

**Steps to Reproduce**

lmp -in test-hybrid.txt -k on g 1 -sf kk (or whatever KOKKOS accelerator you are using)
examine forces in dump.0.lammpstraj, they should be zero

lmp -in test-hybrid.txt 
examine forces in dump.0.lammpstraj, they should be non-zero

**Further Information, Files, and Links**

[test-hybrid.txt](https://github.com/lammps/lammps/files/12861195/test-hybrid.txt)

**Comment by stanmoore1** [comment] 2023-10-10 20:19
@bnebgen-LANL thanks I know the cause of this. It is due to fusing the force clear kernel with force compute. For pair hybrid it should only zero for the first pair style. Need to think how to fix it best.

**Comment by bnebgen-LANL** [comment] 2023-10-10 20:21
So you are saying if I add a dummy potential to hybrid/overlay in the first slot, it will work correctly?

**Comment by stanmoore1** [comment] 2023-10-10 20:22
No, but if you use a half list it goes away. It can only fuse for full list.

**Comment by bnebgen-LANL** [comment] 2023-10-10 20:23
I don't know what you mean by 'half list'.

**Comment by stanmoore1** [comment] 2023-10-10 20:23
Currently it zeros out the force for every pair style that uses `pair_kokkos.h`, but it should only zero out the first pair style, otherwise the forces are lost.

**Comment by stanmoore1** [comment] 2023-10-10 20:24
`lmp -in test-hybrid.txt -k on g 1 -sf kk -pk kokkos neigh half`
See https://docs.lammps.org/package.html

**Comment by bnebgen-LANL** [comment] 2023-10-10 20:27
Ahhhh. OK. I'm like 90% sure that fix will break mliap unified (which is actually why I care). HIPNN requires a full neighbor list.

**Comment by stanmoore1** [comment] 2023-10-10 20:29
Yes, I need to add a new template param into `pair_kokkos.h` and turn off the zero, working on it now.

**Comment by bnebgen-LANL** [comment] 2023-10-10 20:39
Thanks a bunch for your help, on this issue and the previous one.

**Comment by stanmoore1** [comment] 2023-10-11 22:37
@bnebgen-LANL this should be fixed by [9b108a6](https://github.com/lammps/lammps/pull/3930/commits/9b108a631bb4b7361855b755ce6accfd657bbbf8)

**Closed as completed** 2023-10-16 18:00 UTC
Labels: bug
