### ISSUE TITLE
[BUG] fix rigid/nve langevin not working as expected

### ISSUE THREAD

**Issue by valesori** [lammps/lammps#2288] opened 2020-08-13 14:39 UTC
**Summary**

The Langevin thermostat is not working as expected in conjunction with fix rigid/nve and rigid/nve/small.

**LAMMPS Version and Platform**

LAMMPS version: 3 Mar 2020
Running on Ubuntu 16.04.7.

**Expected Behavior**

I am running an NVT simulation of rigid molecules. Each molecule is composed by three particles, one of type 1 and two of type 2. The type 2 particles are arranged in a certain configuration at fixed distance 0.5 from the center of the type 1 particle. I am using fix rigid/nve/small langevin. Intramolecular interactions are disabled (neigh_modify exclude molecule/intra all). See input file reported below for details. 

The temperature is expected to fluctuate around the target value (T=0.05).

**Actual Behavior**

An explosion of the kinetic energy is observed when using as input the file 1.lammpsdata.
Using a _very similar_ configuration (see attached file 2.lammpsdata), in which the three particles in a molecule are arranged on the same line, gives reasonable behavior. Note that in 1.lammpsdata the three particles in a molecule are "almost" arranged on the same line, but one out of three is slightly misaligned.

- Reducing the time step does not seem to solve the problem.

- Changing the interaction potentials (1-1, 1-2 and 2-2) does not seem to solve the problem. I have tried different combinations, for example:

```
pair_style hybrid lj/cut 1.122462048 zero 1.0
pair_coeff 1 1 lj/cut 1.0 1.0 1.122462048
pair_modify pair lj/cut shift yes
pair_coeff 1 2 zero 1.122462048
pair_coeff 2 2 zero 1.122462048

pair_style lj/cut 1.122462048
pair_modify shift yes
pair_coeff 1 1 1.0 1.0
pair_coeff 1 2 0.0 1.0 1.0
pair_coeff 2 2 0.0 1.0 1.0

pair_style lj/cut 1.122462048
pair_modify shift yes
pair_coeff * * 1.0 1.0 1.122462048
```

, getting always the same result.

- Visual inspection of the trajectory (using VMD) reveals that when using the file 1.lammpsdata some particles start to rotate very rapidly, resulting in the observed explosion of the kinetic energy (it may be necessary to generate many dump files, however a very short run is sufficient).

- Using fix rigid/nve instead of rigid/nve/small gives the same behavior.

- Using fix rigid/nvt and rigid/nvt/small gives **reasonable** behavior.

**Steps to Reproduce**

I attach two input files:

- 1.lammpsdata --> anomalous behavior

- 2.lammpsdata --> "reasonable" behavior

[data_files.zip](https://github.com/lammps/lammps/files/5069572/data_files.zip)

The input script which I am using is the following (commented lines are different pair styles that may be tried):

```
variable nsteps equal 1e6
variable mytemp         equal 0.05    
variable thermodump     equal   $(v_nsteps/1e5)
variable trajdump       equal   $(floor(v_nsteps/20))    
variable trestart       equal   $(floor(v_nsteps/5.))    
variable tstep         equal   0.001  
variable damp   equal   0.1    
variable neigh_cutoff equal 0.3
variable lseed equal 921389
variable vseed equal 191814
variable fname string data
variable thermofile     string  thermo.dat
variable simname string run_T${mytemp}

units           lj          
boundary        p p p      
atom_style     bond

read_data       ${fname}

neighbor ${neigh_cutoff} bin
neigh_modify every 10 delay 0 check yes
neigh_modify exclude molecule/intra all

#pair_style hybrid lj/cut 1.122462048 zero 1.0
#pair_coeff 1 1 lj/cut 1.0 1.0 1.122462048
#pair_modify pair lj/cut shift yes
#pair_coeff 1 2 zero 1.122462048
#pair_coeff 2 2 zero 1.122462048

#pair_style lj/cut 1.122462048
#pair_modify shift yes
#pair_coeff 1 1 1.0 1.0
#pair_coeff 1 2 0.0 1.0 1.0
#pair_coeff 2 2 0.0 1.0 1.0

pair_style lj/cut 1.122462048
pair_modify shift yes
pair_coeff * * 1.0 1.0 1.122462048

timestep ${tstep}

variable step equal step
variable temp equal temp
variable etot equal etotal
variable ke equal ke
variable pe equal pe
variable press equal press

thermo_style custom step etotal ke pe temp press
thermo ${thermodump}
thermo_modify norm no

fix fix_rigid all rigid/nve/small molecule langevin ${mytemp} ${mytemp} ${damp} ${lseed}

velocity all create ${mytemp} ${vseed} dist gaussian mom yes rot yes
run 0
velocity all scale ${mytemp}

fix fix_print all print ${thermodump} "${step} ${etot} ${ke} ${pe} ${temp} ${press}" file ${thermofile} screen no title "#1:step 2:etot 3:ke 4:pe 5:temp 6:press"

dump 1 all custom ${trajdump} dump/dump.${simname}.*.lammpstrj type mol xu yu zu
dump_modify 1 sort id
dump_modify 1 pad 10
dump_modify 1 format line "%d %d %.8f %.8f %.8f"

run ${nsteps}

unfix fix_print
unfix fix_rigid

write_data      data.${simname}
write_restart restart/restart.${simname}
```

**Comment by valesori** [comment] 2020-09-01 14:16
**Update**

It seems that the simulation becomes stable (when using the 1.lammpsdata input file) if one increases the value of the damp parameter enough (e.g. damp=100).
It could be therefore a numerical instability caused by the small value of the damp parameter.
It is still puzzling to me that two initial configurations which are so similar can give such different results.

**Comment by valesori** [comment] 2020-09-03 10:40
**Update**

There is another strange behavior that I have observed. I am posting about this as a comment instead of opening another issue since it seems related to the original one, but it may well have a different origin.

To observe this behavior it's better to consider a configuration with more molecules than those considered in the original post, as for example the one here attached (512 molecules):

[data_file_512.zip](https://github.com/lammps/lammps/files/5167684/data_file_512.zip)

It is also advisable to run a longer simulation (10^7 steps).

When running the same code as the one posted in the original post with this input file, one can see that the mean temperature is ~3% lower than the target temperature, i.e. ~0.0485 instead of 0.05. Note that in this file the molecules have the same configuration as those in file 2.lammpsdata in the original post, which I wrote had "reasonable" behavior; i.e., the three particles composing the molecule are arranged on a line segment.

This anomalos behavior seems to only be observable when the 1-2 and 2-2 interactions are both turned off, for example by choosing one of the following sets of interactions:

(1)
```
pair_style hybrid lj/cut 1.122462048 zero 1.0
pair_coeff 1 1 lj/cut 1.0 1.0 1.122462048
pair_modify pair lj/cut shift yes
pair_coeff 1 2 zero 1.0
pair_coeff 2 2 zero 1.0
```

(2)
```
pair_style lj/cut 1.122462048
pair_modify shift yes
pair_coeff 1 1 1.0 1.0
pair_coeff 1 2 0.0 1.0 1.0
pair_coeff 2 2 0.0 1.0 1.0
```

The temperature is initialized correctly to 0.05, but almost immediately drops to ~0.0485 and fluctuates around this value for the rest of the simulation.

Some observations:

- Changing the value of the damp parameter seems to have no effect in this case.

- Changing (decreasing) the value of the timestep seems to have no effect.

- The same problem is also present if one chooses a higher temperature.

- Using fix rigid/nve instead of fix rigid/nve/small does not solve the problem.

- The problem seems to disappear if some non-zero interaction is chosen either for the 1-2 or for the 2-2 pair.

Again, I am posting this as a comment but it may well be a different issue. I am not sure. However I am finding in several cases unexpected behavior when using the langevin thermostat with rigid bodies.

**Comment by ndtrung81** [comment] 2020-09-03 13:12
@valesori if you switch to fix rigid, will the issues persist?

**Comment by valesori** [comment] 2020-09-03 15:30
@ndtrung81 

Thanks for your reply.

Regarding problem n.1, i.e. the explosion of the kinetic energy when using molecules which are not perfectly linear (as in file 1.lammpsdata), the outcome is the same if I switch to fix rigid, however the output is different. 

For example, when using fix rigid/nve/small I get:

```
Step TotEng KinEng PotEng Temp Press 
       0        1.125        1.125            0         0.05 0.0093750025 
     100    1.1000319    1.1000319            0  0.048890306 -0.084708585 
     200    1.2306661    1.2306661            0  0.054696271  -0.54990806 
     300    1.3107243    1.3107243            0  0.058254415  -0.60869955 
     400 1.395687e+150 1.395687e+150            0 6.2030533e+148 1.1630728e+148 
     500          inf          inf            0          inf          inf 
     600          inf          inf            0          inf          inf 
ERROR on proc 0: Non-numeric atom coords - simulation unstable (../domain.cpp:521)
```

whereas when using fix rigid/small I get:

```
Step TotEng KinEng PotEng Temp Press 
       0        1.125        1.125            0         0.05 0.0093750025 
     100    1.1002767    1.1002767            0  0.048901188 -0.084713701 
     200    1.2308354    1.2308354            0  0.054703793  -0.54994162 
     300    1.3195609    1.3195609            0  0.058647149  -0.61461195 
     400 1.5553234e+40 1.5553234e+40            0 6.9125484e+38 1.2961032e+38 
     500 1.6294807e+111 1.6294807e+111            0 7.2421366e+109 1.357901e+109 
     600 4.6570736e+203 4.6570736e+203            0 2.0698105e+202 3.8808957e+201 
     700         -nan         -nan            0         -nan         -nan 
ERROR on proc 0: Non-numeric atom coords - simulation unstable (../domain.cpp:521)
```

Also regarding problem n.2, i.e. the mean temperature being lower than the desired value, not much seems to change when switching to fix rigid (or fix rigid/small). I include [a plot](https://github.com/lammps/lammps/files/5169571/temp.pdf) in which I compare fix rigid (+langevin), rigid/nve (+langevin) and rigid/nvt. Only the latter seems to give the correct mean temperature, whereas the former two consistently give a lower temperature. It is also possible that there is very small drift in the temperature, but it is not clear from these data. Note that I have performed running averages to smooth out the data.

The codes used to obtain these plots are the following (only the fix fix_rigid ... line is changed):

```
variable nsteps 		equal 1e7
variable mytemp         equal 0.05    
variable thermodump     equal $(v_nsteps/1e4)
variable tstep        	equal 0.001  
variable damp   		equal 1.0    
variable neigh_cutoff 	equal 0.3
variable lseed 			equal 921389
variable vseed 			equal 191814
variable fname 			string data
variable thermofile     string thermo.dat
variable simname 		string run_T${mytemp}

units          lj          
boundary       p p p      
atom_style     molecular

read_data       ${fname}

neighbor ${neigh_cutoff} bin
neigh_modify every 10 delay 0 check yes
neigh_modify exclude molecule/intra all

pair_style hybrid lj/cut 1.122462048 zero 1.0
pair_coeff 1 1 lj/cut 1.0 1.0 1.122462048
pair_modify pair lj/cut shift yes
pair_coeff 1 2 zero 1.122462048
pair_coeff 2 2 zero 1.122462048

timestep ${tstep}

variable step equal step
variable temp equal temp
variable etot equal etotal
variable ke equal ke
variable pe equal pe
variable press equal press

thermo_style custom step etotal ke pe temp press
thermo ${thermodump}
thermo_modify norm no

fix fix_rigid all rigid molecule langevin ${mytemp} ${mytemp} ${damp} ${lseed}
#fix fix_rigid all rigid/nve molecule langevin ${mytemp} ${mytemp} ${damp} ${lseed}
#fix fix_rigid all rigid/nvt/small molecule temp ${mytemp} ${mytemp} ${damp}

velocity all create ${mytemp} ${vseed} dist gaussian mom yes rot yes
run 0
velocity all scale ${mytemp}

fix fix_print all print ${thermodump} "${step} ${etot} ${ke} ${pe} ${temp} ${press}" file ${thermofile} screen no title "#1:step 2:etot 3:ke 4:pe 5:temp 6:press"

run ${nsteps}

unfix fix_print
unfix fix_rigid

write_data      data.${simname}



```

**Comment by valesori** [comment] 2020-09-09 12:30
**Update**

I think I have identified a key issue of problem #2 (temperature being lower than the desired value), although I cannot tell where the problem is located specifically. This may or may not be related to problem #1 (explosion of the kinetic energy).

**I'm convinced that the problem must be related to how the degrees of freedom of the molecules are accounted for by the Langevin thermostat.**

In order to show this, I have run two simulations of 21^3=9261 molecules. The simulation code (reported below) is exactly the same for the two simulations, and only the input data files are different. The input files are attached below:

[input_files.zip](https://github.com/lammps/lammps/files/5194857/input_files.zip)

As in the examples from previous posts, each molecule is made of three particles: one "type 1" particle and 2 "type 2" particles (**_This is actually not relevant; I have also tried to consider all particles of the same type, and the result is the same_**). Each particle interacts with particles belonging to different molecules via a WCA potential (intramolecular interactions are turned off).

1. In the first simulation (input file n9261_180.lammpsdata), the three particles in a molecule are arranged on a line segment (180 degrees), with a distance of 0.5 between each particle and its neighbors.

2. In the second simulation  (input file n9261_90.lammpsdata), the three particles are arranged in a rectangular triangle configuration (90 degrees), with a distance of 0.5 between the central particle and the other two.

The starting configuration is a perfect cubic crystal, with the particles all oriented in the same way. **_I have also tried to start with particles oriented in random directions, finding the same results_**. The molecule number density is 0.001, so that the system is rather dilute.

The temperature, as in the examples reported above, is initialized using the workaround reported in the section "Restrictions" of the [velocity command manual page](https://lammps.sandia.gov/doc/velocity.html).

One can see that for the "linear" (180 degrees) particles, the temperature is initialized at t=0 to the correct value, T=0.05, but then immediately drops to ~0.047. The mean temperature successively increase until it seems to stabilize at the correct value.

For the "triangular" (90 degrees) particles, on the other hand, the mean temperature stays around the correct mean value and no drop is observed.

Here is a plot of the temperature for the two simulations:

[temp_wca_trimer_180_90.pdf](https://github.com/lammps/lammps/files/5195004/temp_wca_trimer_180_90.pdf)

also in log scale:

[temp_wca_trimer_180_90_log.pdf](https://github.com/lammps/lammps/files/5195009/temp_wca_trimer_180_90_log.pdf)

This example makes it clear to me that there must be a problem with how the thermostat accounts for the degrees of freedom of the particles. Indeed, the most relevant difference between the two input files is that the linear particles only have 5 d.o.f., whereas the triangular particles have 6. 

I'm not sure where the problem is exactly, but as I discussed in the previous posts the same problem is found when using fix rigid, rigid/small, rigid/nve and rigid/nve/small with the langevin thermostat.

Here is the simulation code used to obtain the data shown in the plot (it's basically the same as the previously reported codes, with a few irrelevant changes):

```
variable nsteps 		equal 1e7
variable mytemp         equal 0.05    
variable thermodump     equal $(v_nsteps/1e4)
variable tstep        	equal 0.001  
variable damp   		equal 1.0    
variable neigh_cutoff 	equal 0.3
variable lseed 			equal 921389
variable vseed 			equal 191814
variable fname 			string data
variable thermofile     string thermo.dat
variable simname 		string run_T${mytemp}

units          lj          
boundary       p p p      
atom_style     molecular

read_data       ${fname}

neighbor ${neigh_cutoff} bin
neigh_modify every 10 delay 0 check yes
neigh_modify exclude molecule/intra all

pair_style lj/cut 1.122462048
pair_modify shift yes
pair_coeff * * 1.0 1.0 1.122462048

timestep ${tstep}

variable step equal step
variable temp equal temp
variable etot equal etotal
variable ke equal ke
variable pe equal pe
variable press equal press

thermo_style custom step etotal ke pe temp press
thermo ${thermodump}
thermo_modify norm no

fix fix_rigid all rigid molecule langevin ${mytemp} ${mytemp} ${damp} ${lseed}

velocity all create ${mytemp} ${vseed} dist gaussian mom yes
run 0
velocity all scale ${mytemp}

fix fix_print all print ${thermodump} "${step} ${etot} ${ke} ${pe} ${temp} ${press}" file ${thermofile} screen no title "#1:step 2:etot 3:ke 4:pe 5:temp 6:press"

run ${nsteps}

unfix fix_print
unfix fix_rigid

write_data      data.${simname}
```

**Comment by valesori** [comment] 2020-09-11 16:10
**Addendum to previous comment**

If one looks at the translational (center-of-mass) and rotational components of the kinetic energy (KE), one sees that the translational KE behaves correctly (KE_cm = 3NkT/2, with N=number of molecules and k=1), whereas the rotational KE behaves anomalously (should be KE_rot=NkT). This is shown for example in [this plot](https://github.com/lammps/lammps/files/5210252/wca_trimer_180_1type_n1000_kecm_kerot.pdf) (simulation of 10^3 "linear trimers").

**Comment by ndtrung81** [comment] 2020-09-11 21:30
@valesori thanks for your careful tests and analysis.

Can you try apply the diff in the attached file to fix_rigid.cpp, and then rebuild LAMMPS, and rerun with fix rigid?

[fix_rigid.cpp.diff.txt](https://github.com/lammps/lammps/files/5210635/fix_rigid.cpp.diff.txt)

**Comment by valesori** [comment] 2020-09-14 08:33
@ndtrung81 

Thank you for your reply. I applied the diff, but now the rotational kinetic energy seems to diverge exponentially.
Cfr. the following output from the last reported script (c_kecm is the center of mass KE, c_kerot is the rotational KE):

```
Step KinEng Temp c_kecm c_kerot 
       0      124.925         0.05    75.663953    49.261047 
     200    135.86216  0.054377492    76.006808    59.855357 
     400    148.19101   0.05931199     77.10283    71.088177 
     600    160.29431  0.064156218    74.739102    85.555209 
     800    171.53975  0.068657095    77.244896    94.294857 
    1000    185.75707  0.074347435    76.389171     109.3679 
    1200    200.62041  0.080296344    76.975862    123.64455 
    1400    216.22654  0.086542542    76.396424    139.83012 
    1600    237.44872   0.09503651     76.78004    160.66868 
    1800     258.1554   0.10332416    74.851218    183.30419 
    2000    286.85743   0.11481186     73.51773     213.3397 
    2200    324.54013   0.12989399     71.40043     253.1397 
    2400    381.69328   0.15276897    74.160005    307.53327 
    2600     457.3238   0.18303934      73.2111     384.1127 
    2800     559.5835   0.22396778    72.928768    486.65474 
    3000    708.07977   0.28340195    71.418117    636.66165 
    3200    920.09803   0.36826017    72.039306    848.05873 
    3400    1216.9418   0.48706896    75.237801     1141.704 
    3600    1630.6377   0.65264665    74.914396    1555.7233 
    3800     2225.413   0.89069962    73.685712    2151.7273 
    4000    3086.8115    1.2354659    73.740769    3013.0707 
    4200    4315.6391     1.727292    73.532864    4242.1062 
    4400    6115.4496    2.4476484    74.456019    6040.9936 
    4600    8774.0579    3.5117302    72.996448    8701.0615 
    4800    12561.984    5.0278104    73.227641    12488.757 
    5000    18126.169    7.2548205    72.296015    18053.873 
    5200      26212.8    10.491415    74.350501     26138.45 
    5400    38036.042    15.223551    73.467222    37962.575 
    5600    55441.305    22.189836    72.175171     55369.13 
    5800    80904.591    32.381265    75.129374    80829.462 
    6000    118232.76    47.321495    73.153345     118159.6 
    6200    172951.98    69.222326    75.770757    172876.21 
    6400    253212.08    101.34564    74.114911    253137.97 
    6600    371190.46    148.56532    74.167622     371116.3 
    6800    544604.16    217.97245    72.945206    544531.21 
    7000    799688.39     320.0674    73.149051    799615.24 
    7200    1175162.9    470.34735     73.21747    1175089.6 
    7400    1727519.1    691.42249     72.17068    1727446.9 
    7600    2541817.1    1017.3372    73.303761    2541743.8 
    7800    3740683.8    1497.1718    73.688459    3740610.1 
    8000    5508304.7    2204.6447    73.926294    5508230.8 
    8200    8114578.7    3247.7801     72.55958    8114506.1 
    8400     11958556    4786.2943    73.369092     11958483 
    8600     17628612    7055.6782    74.600937     17628537 
    8800     25995881    10404.595    76.005667     25995805 
    9000     38345905    15347.571    76.204853     38345829 
    9200     56581163    22646.053    75.599554     56581087 
    9400     83512814    33425.181    74.462863     83512739 
    9600 1.2329059e+08    49345.842    75.208381 1.2329051e+08 
    9800 1.8205861e+08    72867.164    76.185306 1.8205853e+08 
   10000 2.6890026e+08    107624.68    75.929113 2.6890018e+08 
```

**Comment by ndtrung81** [comment] 2020-09-14 17:34
@valesori thanks for the update. Would you mind applying the diff attached to the original fix_rigid.cpp? There remain places that are missed by the last patch.

[fix_rigid.diff-2.txt](https://github.com/lammps/lammps/files/5220044/fix_rigid.diff-2.txt)

**Comment by valesori** [comment] 2020-09-15 10:14
@ndtrung81 Thank you very much for the update.

The new fix seems to solve the problem! 

Both problem #1 (explosion of the kinetic energy) and problem #2 (lower temperature value) seem now to be solved, cfr. for example [this plot](https://github.com/lammps/lammps/files/5224165/wca_trimer_180_1type_n1000_kecm_kerot_1.pdf).

May I ask what the problem was, and if/when the patch will be implemented into the LAMMPS code?

**Comment by ndtrung81** [comment] 2020-09-15 20:07
@valesori you're welcome, and thanks for the update. The problem is that the langevin torques (langextra[3], langextra[4] and langextra[5]) to be added to the bodies should be in the space frame. Originally these torques were computed from the principal moments of inertia (defined in the body frame) and the body angular velocities in the space frame (omega), which are inconsistent with each other. What the patch does are: 1) converting the body angular velocities from the space frame into the body frame, then 2) computing the langevin torques in the body frame, and 3) converting the torques from the body frame back to the space frame. You can find these steps commented in the patch.

Similar changes will be done for rigid/small and submitted as a PR.

**Comment by valesori** [comment] 2020-09-16 15:45
@ndtrung81 Thank you for the explanation. Will similar changes be applied to rigid/nve and rigid/nve/small?

Also, please excuse me if the following question is silly, but I'm very new to Github and some things are still not clear to me:
I am currently using the stable release of lammps (I forked the branch "stable" and I am working on that).
Once the changes are available, will it be possible to easily apply them to this version? 
Or will they only be available on the "master" or "unstable" branch?

**Comment by akohlmey** [comment] 2020-09-16 16:00
> Also, please excuse me if the following question is silly, but I'm very new to Github and some things are still not clear to me:
> I am currently using the stable release of lammps (I forked the branch "stable" and I am working on that).

you can only "fork" the entire repository, which is an operation on the github website.
then you "clone" the repository, either your fork (if you did that) or the original repository.

> Once the changes are available, will it be possible to easily apply them to this version?
> Or will they only be available on the "master" or "unstable" branch?

all changes to LAMMPS are submitted as pull requests and then merged into the branch "master". this branch is only recommended to use for people doing active development that has changes to common code. at every patch release (every few weeks) the state of the master branch at that point is merged into the "unstable" branch. at every stable/full release, the state of the master branch is merged into the "stable" branch. 

the next patch release is planned for this week (depends on completing a few urgent projects)
a stable release is planned for the end of the month (unless it is deferred by bugs surfacing that need fixing).

**Comment by valesori** [comment] 2020-09-16 16:18
@akohlmey Thank you for the reply and for the explanation. 
Indeed, I meant that I forked the entire repository and then cloned my fork, and that I am working on the "stable" branch; sorry for the bad use of the terminology.

**Comment by akohlmey** [comment] 2020-09-16 16:32
> @akohlmey Thank you for the reply and for the explanation.
> Indeed, I meant that I forked the entire repository and then cloned my fork, and that I am working on the "stable" branch; sorry for the bad use of the terminology.

no problem. if you created a fork, then you won't get any updates automatically. 
best practices when working on a fork are the following:
- never work on any of the branches with the same name as upstream (i.e. "master", "unstable", or "stable"). always create  feature branches. if you accidentally make a commit to any of those branches, undo it. you want to be able to get "fast-forward" updates on those branches. with a commit it will diverge and create a host of problems down the line
- add a repository shortcut (aka "remote") for the upstream repository. e.g. by `git remote add upstream https://github.com/lammps/lammps.git`
- now you can "link" the branches "master", "unstable" and "stable" to the original upstream repository with: eg.
```bash
  git fetch upstream
  git checkout master
  git branch --set-upstream-to=upstream/master
```
- to update the linked branches you only need to do: `git checkout master; git pull` and if done correctly, it should just do a fast-forward without a commit
- to update a feature branch to the current state of an upstream branch to the update of your local branch and then `git checkout some-feature-branch; git merge unstable`

You can also set to "watch" the upstream repository and will then get notifications (usually best to limit it to release notifications).

HTH

**Comment by valesori** [comment] 2020-09-16 19:32
@akohlmey Thank you very much for these suggestions. I was just starting to get my feet wet at this, so I had done some of these things already "more or less correctly", but I still have to get the hang of it. Hope to maybe be able to contribute more efficiently in the future!

**Comment by sjplimp** [comment] 2020-09-16 20:48
@valesori Thanks for reporting this issue with all the careful details.  @ndtrung81 has just posted a PR to fix it.

**Closed** 2020-09-17 02:36 UTC
Labels: bug
