### ISSUE TITLE
[BUG] 2Aug2023_update3 ：Calculation error when using kokkos to accelerate the meam potential

### ISSUE THREAD

**Issue by LLfbforever** [lammps/lammps#4315] opened 2024-09-04 13:10 UTC
（1）There is no problem in using CPU to accelerate the calculation of meam potential
（2）When using KOKKOS to accelerate the meam potential, the calculation error occurs, and the total energy calculated in the first step is different from the result calculated by the CPU. Through debugging, it is found that the calculated force->pair->eng_vdwl values ​​are different.
By searching, it is found that in the MEAMKokkos<DeviceType>::meam_dens_final function in the file KOKKOS/pair_meam_kokkos.cpp, the ev.evdwl value reduced by Kokkos::parallel_reduce is different from the result calculated by the CPU.
![err](https://github.com/user-attachments/assets/1c65e272-0708-4118-9b9d-25c4805b6f50)

It was also found that during the calculation process, the temperature and total energy suddenly increased, and an error was reported later.

**Comment by Mounik-tech** [comment] 2024-09-04 13:10
try this
https://gofile.io/d/yMHabA
select the desired compiler in the installer

**Comment by akohlmey** [comment] 2024-09-04 13:23
Please try version stable_2Aug2023_update4 or the 29Aug2024 stable release. Both have bugfixes to meam in KOKKOS although I cannot say if they specifically address what you are observing.

**Comment by stanmoore1** [comment] 2024-09-04 18:10
@LLfbforever if using the latest version of LAMMPS doesn't resolve the issue, can you also please attach a minimal working example of the issue? Thank you

**Comment by stanmoore1** [comment] 2024-09-09 21:10
@LLfbforever any update on this? I'm happy to take a look if you post a reproducer

**Comment by akohlmey** [comment] 2024-09-25 21:00
@LLfbforever if you do not provide further information as requested and a (simple) way to reproduce it, we have to close this issue down as unconfirmed. We cannot fix a bug that we cannot reproduce.

**Comment by akohlmey** [comment] 2024-11-28 12:30
@LLfbforever since there have been no updates from you or an input deck to reproduce it, we will assume that the issue has been resolved by updating LAMMPS and close this issue now.

**Closed as not planned by akohlmey** 2024-11-28 12:30 UTC
Labels: bug, unconfirmed
