### ISSUE TITLE
[BUG] Dynamic load balancing leads to missing atoms

### ISSUE THREAD

**Issue by ohenrich** [lammps/lammps#2463] opened 2020-10-29 10:32 UTC
**Summary**

The dynamic load balancing causes missing atoms and jobs to crash.

**LAMMPS Version and Platform**

LAMMPS master branch from 29th Oct 2020, GNU GCC9 C++ compiler, OpenMPI library, 2.8 GHz Quad-Core Intel Core i7, Mac OS X 10.15.7

**Expected Behavior**

Atoms should not be lost during dynamic load balancing.

**Actual Behavior**

Atoms get lost and the runs crash, but not for very low core counts (e.g. 2 or 4 MPI-tasks).

**Steps to Reproduce**

Run the attached test problem on 8 MPI-tasks without and with dynamic load balancing through comm_style tiled and fix balance rcb.

**Further Information, Files, and Links**

Note that this problem is potentially related to issues #2337 and #1655, but hasn't been addressed yet. It is likely to cause problems in the next stable release.

The test problem and stdout for runs on 4 and 8 MPI-tasks with and without dynamic load balancing is contained in the attached zip archive.

[test.zip](https://github.com/lammps/lammps/files/5457700/test.zip)

**Comment by akohlmey** [comment] 2020-10-29 10:36
This is indeed a duplicate of issue #2337

**Closed by akohlmey** 2020-10-29 10:36 UTC
Labels: bug, duplicate
