### ISSUE TITLE
[BUG] Flawed logic in USER-INTEL when checking for kspace compatibility with pair hybrid

### ISSUE THREAD

**Issue by donatas-surblys** [lammps/lammps#1808] opened 2019-12-13 07:58 UTC
**Summary**

When using USER-INTEL, both pair and kspace style have to be supported, otherwise the following error is produced: "Intel styles for kspace require intel pair style.".
Due to a logic error, the check fill always fail with pair hybrid, even when all sub-styles are supported.

**LAMMPS Version and Platform**

Latest LAMMPS master version. Intel compiler version: 18.0.2.

**Steps to Reproduce**
The error can be demonstrated by the following script when executed with "-sf intel":
```
units real
atom_style charge
region box block -30 30 -30 30 -30 30
create_box 2 box
pair_style hybrid lj/cut/coul/long 15 lj/cut/coul/long 15
kspace_style pppm 1e-6
mass * 100
create_atoms 1 single 0 0 -1
create_atoms 2 single 0 0 1
set type 1 charge -1
set type 2 charge 1
pair_coeff 1 1 lj/cut/coul/long 1 1 1
pair_coeff 2 2 lj/cut/coul/long 2 1 1
pair_coeff 1 2 lj/cut/coul/long 1 1 1
run 0
```

**Expected Behavior**

I'm not fully sure if pair hybrid is supported by USER-INTEL, but it appears to be so from a quick glance over the source code. At the very least, a more appropriate error message should be provided.

**Actual Behavior**

The provided script produces the following error: 

> ERROR: Intel styles for kspace require intel pair style. (../fix_intel.cpp:544)

**Further Information, Files, and Links**
`fix_intel.cpp` contains the `FixIntel::kspace_init_check`, which check for compatibility. In case of a normal pair style, it simply check for the "/intel" suffix. In case of pair hybrid or hybrid/overlay, the `_pair_intel_count` is checked. The `_pair_intel_count` flag is incremented in the `FixIntel::pair_init_check` function, which is called by the `init_style` functions of intel pair styles. Unfortunately, as can be seen in the `Force::init` function,` kspace->init()` is called before `pair->init()`, therefore `_pair_intel_count` will always be zero when  `FixIntel::kspace_init_check` is called.

**Comment by akohlmey** [comment] 2020-01-03 07:03
Should be addressed in PR #1817. Please check it out.

**Comment by donatas-surblys** [comment] 2020-01-07 07:07
OK, the sample script is working with PR #1817, but I worry that calling pair_init_check() inside kspace_init_check() makes the intel pair style compatibility test pass unconditionally. For example, I was able to segfault LAMMPS by using "lj/charmmfsw/coul/long" pair style that is not implemented by USER-INTEL with -sf intel flag:
```
units real
atom_style charge

region box block -30 30 -30 30 -30 30

create_box 2 box

pair_style hybrid lj/charmmfsw/coul/long 13 15 lj/charmmfsw/coul/long 13 15
kspace_style pppm 1e-6

mass * 100
create_atoms 1 single 0 0 -1
create_atoms 2 single 0 0 1
set type 1 charge -1
set type 2 charge 1

pair_coeff 1 1 lj/charmmfsw/coul/long 1 1 1
pair_coeff 2 2 lj/charmmfsw/coul/long 2 1 1
pair_coeff 1 2 lj/charmmfsw/coul/long 1 1 1

run 0
```


I am also getting a similar error (ERROR: Intel styles for bond/angle/dihedral/improper require intel pair style. (../fix_intel.cpp:519)) when trying to use intel pair_hybrid with bonds:
```
units real
atom_style molecular

region box block -30 30 -30 30 -30 30
create_box 2 box bond/types 1 extra/bond/per/atom 1 extra/special/per/atom 1
mass * 100

pair_style hybrid lj/cut 10 lj/cut 10
pair_coeff * * lj/cut 1 3 1
pair_coeff 2 2 lj/cut 2 3 1

create_atoms 1 single -1 0 0
create_atoms 1 single  0 0 0

create_atoms 2 single -1 0 15

bond_style harmonic
bond_coeff 1 0 1

create_bonds single/bond 1 1 2

run 0     
```

I haven't looked closely into the code path, it it looks like bond_init_check() is being called before pair_init_check(). I guess a similar treatment as kspace_init_check() might solve it? I'm also a bit worried about _pair_intel_count getting double counted.

**Comment by akohlmey** [comment] 2020-01-07 16:23
@donatas-surblys thanks for the feedback and providing additional test inputs. i'll be looking into this more thoroughly using some more careful testing and also checking with valgrind and alike. the problem is, that USER-INTEL is doing some steps out of order and redundantly because it needs information otherwise only available later to do some further preprocessing and repackaging of internal data for optimized access patterns. That makes things difficult to follow and can cause problems due to unintended side effects. the unintended side effects is a major concern in LAMMPS, since a lot of it was programmed with an assumptions of X cannot before Y because this is how we program it, so we don't need to check or make it consistent. as time progresses and people come up with more complex operations, these assumptions are not always true anymore and that makes things tricky. already spotted some uninitialized memory access and a couple of small memory leaks before even looking at the initialization issue in detail.
that said, what you are asking for in your inputs is definitely pushing the limits, so i am not too surprised that this has not been tested before (or even considered).

**Comment by akohlmey** [comment] 2020-01-07 20:39
@donatas-surblys i've changed the process of detecting intel hybrid substyles since the corresponding suffixes are actually not stored inside the hybrid styles, so a different detection mechanism is needed. PR #1817 is updated correspondingly. Please check it out.

**Closed** 2020-01-08 22:16 UTC
Labels: bug
