### ISSUE TITLE
[BUG]  dump NetCDF  fails when process has no atoms. 

### ISSUE THREAD

**Issue by janmees** [lammps/lammps#1543] opened 2019-06-28 08:22 UTC
**Summary**
When dumping data while using multiple processors, error is raised if one processor does not contain any atoms. 

**LAMMPS Version and Platform**

Tested on versions 30 Apr 2019 and 9 Nov 2018. 

**Actual Behavior**
I created a test file with a large box and create a single atom on one end. If I run it on one core there is no problem. On two cores the error is raised when the dump command is reached. This error is not raised if I create a second atom on the other side of the box. 

ERROR on proc 0: NetCDF failed with error 'NetCDF: Index exceeds dimension bound' in line 917 of ../dump_netcdf.cpp. (../dump_netcdf.cpp:1029)

I will attach a minimal working example that reproduces the error. 

[test.in.zip](https://github.com/lammps/lammps/files/3338222/test.in.zip)

**Comment by pastewka** [comment] 2020-06-23 15:24
I cannot reproduce this bug. It appears to be a problem with the local installation of NetCDF on @janmees system. Closing this issue.

**Comment by pastewka** [comment] 2020-06-23 15:24
I see I cannot close it myself, @akohlmey can you close this issue?

**Closed** 2020-06-23 15:31 UTC
Labels: bug, unconfirmed
