### ISSUE TITLE
[BUG] Drift of z coordinate when using fix rigid + Langevin thermostat in 2d simulation

### ISSUE THREAD

**Issue by valesori** [lammps/lammps#2459] opened 2020-10-28 13:36 UTC
**Summary**

When using the fix rigid, rigid/small, rigid/nve and rigid/nve/small + Langevin thermostat, the z coordinate does not remain =0 in 2d simulations.

**LAMMPS Version and Platform**

LAMMPS development version (master branch) patch_22Oct2020-50-g5872b05

Ubuntu 16.04

**Expected Behavior**

Running simulations of (pentagon-shaped) rigid particles in 2d. The particles interact via a cut-and-shifted Lennard-Jones potential with cutoff radius = 2.5.

I've run some tests using fix rigid, rigid/small, rigid/nve and rigid/nve/small + Langevin thermostat in conjunction with fix enforce2d using the latest stable version of LAMMPS (3 March 2020) and found that, as expected, the z coordinate of the particles, which is initially =0, remains =0 during the simulation.

**Actual Behavior**

When using the latest patch version (branch master) to perform the same simulations, I observe that the z coordinate does not remain =0 during the simulation. Qualitatively, one can see that if the simulation is run for for long enough, the particles will begin to rotate, with rotation axis parallel to the z=0 plane, and eventually some atoms will "rotate out" of the plane, usually causing a segmentation fault or similar problems. 

To be more quantitative, I've plotted the root-mean-squared z coordinate of the particles (z_rms) as a function of time, which is shown in the following plot:

![z_rms](https://user-images.githubusercontent.com/50881862/97423623-c8dc0b80-190f-11eb-9680-86f0fb1e837d.png)

One can see that:

- For fix rigid and rigid/nve, z_rms initially increases and then seems to fluctuate around some mean value or to increase very slowly. This is probably not due only to rounding-off errors, since when performing the simulation with the stable LAMMPS version z remains exactly =0.

- For fix rigid/small, z_rms increases exponentially.

- For fix rigid/nve/small the simulation could not be terminated due to a segmentation fault (Signal code: Address not mapped).

**Steps to Reproduce**

I include below a folder containing the input script (run.in) and the starting configuration (data).

The starting configuration consists in 4 pentagon-shaped rigid particles arranged in regularly in the z=0 plane.

As suggested in the manual (https://lammps.sandia.gov/doc/Howto_2d.html), I chose a small but finite z dimension for the simulation box, zlo=0.0 zhi=0.1. I have also tried zlo=-0.05, zhi=0.05, with the same results. Decreasing zhi-zlo seems to mitigate the problem (discussion in the section below), but does not solve it.

Each particle is composed by 20 atoms, with 4 atoms per side of the pentagons. The distance between each atom and its neighbors is 0.5. A snapshot of the initial configuration is reported below:

![snapshot](https://user-images.githubusercontent.com/50881862/97424877-a3e89800-1911-11eb-9718-c810fff5f2da.png)

**Further Information, Files, and Links**

- I'll note again that this problem is _not_ present (the z coordinate of all the particles remains exactly =0 during the simulation) in the stable version of LAMMPS (3 Mar 2020), which however had other issues with the Langevin thermostat when used with rigid body particles (https://github.com/lammps/lammps/issues/2288).

- Reducing the thickness of the box in the z direction seems to somewhat mitigate the problem, but it does not solve it, as shown in the plot below:

![z_rms_rigid_small](https://user-images.githubusercontent.com/50881862/97441600-30eb1b80-1929-11eb-91ab-17e8dd50084a.png)

**_Folder with input script and starting configuration_**: [bug.zip](https://github.com/lammps/lammps/files/5451993/bug.zip)

**_Input script_**:

```
variable nsteps			equal 	1e7	
variable Tstart			equal   1.0		
variable Tend         	equal 	1.0	    	
variable thermodump     equal   $(v_nsteps/1e4)		
variable trajdump       equal   $(v_nsteps/100)    	
variable tstep        	equal   0.001   
variable damp   		equal   1.0    	
variable cutoff			equal	2.5		 
variable lseed			equal	2141	
variable vseed			equal	10188	
variable fname 			string 	data		
variable thermofile     string  thermo.dat	
variable simname 		string 	run_Tstart${Tstart}_Tend${Tend}	


units           lj          	
boundary        p p p       	
atom_style     	molecular
dimension		2 		

read_data       ${fname}

neighbor		0.8 bin 		
neigh_modify	every 10 delay 0 check yes
neigh_modify	exclude molecule/intra all 

pair_style	lj/cut ${cutoff}
pair_coeff	* * 1.0 1.0 ${cutoff}
pair_modify shift yes

timestep	${tstep}

variable step	equal step
variable temp	equal temp
variable etot	equal etotal
variable ke	equal ke
variable pe	equal pe
variable press	equal press

thermo_style	custom step etotal ke pe temp press
thermo		${thermodump}

fix 	fix_rigid	all rigid/small molecule langevin ${Tstart} ${Tend} ${damp} ${lseed}
fix		fix_2d 		all enforce2d 				

velocity 	all create ${Tstart} ${vseed} dist gaussian mom yes rot yes 
run 0
velocity	all scale ${Tstart}

fix		fix_print all print ${thermodump} "${step} ${etot} ${ke} ${pe} ${temp} ${press}" file ${thermofile} screen no title "#1:step 2:etot 3:ke 4:pe 5:temp 6:press"

dump		1 all custom ${trajdump} dump/dump.${simname}.*.lammpstrj mol xu yu zu
dump_modify	1 sort id
dump_modify	1 pad 10
dump_modify	1 format line "%d %.8e %.8e %.8e"

run		${nsteps}

unfix fix_print
unfix fix_rigid
unfix fix_2d

write_data      data.${simname}
```

**Comment by akohlmey** [comment] 2020-10-28 14:52
Thanks for the report and detailed instructions with files to reproduce it. This should be addressed in PR #2456 which enforces that langevin thermostat forces and torques are not applied when they are turned off (for fix rigid and all styles derived from it) and zeroed out where computed (for fix rigid/small and all styles derived from it since they don't have the flag to selectively turn forces or torques off). This is just in time for the stable release. ;-)

**Comment by valesori** [comment] 2020-10-28 15:06
@akohlmey Happy to be in time for the stable release! :)

A small correction to the data file attached above (some atom coordinates were repeated; doesn't change the overall qualitative behavior):

[bug-corr.zip](https://github.com/lammps/lammps/files/5452791/bug-corr.zip)

**Comment by valesori** [comment] 2020-10-30 16:33
@akohlmey , I may be doing something wrong, but I am having the same problem (or at least a very similar one) with the new stable version.
Below a plot of z_rms using fix rigid/small which compares the results obtained with the old unstable version (patch_22Oct2020-50-g5872b05) to those obtained with the new stable one (29 Oct 2020):

![z_rms_new](https://user-images.githubusercontent.com/50881862/97731160-181f6900-1ad5-11eb-8090-b640fa6934f9.png)

The behavior is slightly different, but the z coordinate is still drifting.
I tested again using the stable version of 3 Mar 2020, and the z coordinate remains exactly equal to 0.

**Comment by rbberger** [comment] 2020-10-30 22:17
@akohlmey  I looked at this a bit and leaving my findings so far. Even if the forces/torques are zeroed out for 2d, because of the transformations based on the vectors derived from the inertia tensor (which are produced by `MathEigen::jacobi3`), the z coordinate can become something non-zero.
```
Thread 1 "lmp" hit Hardware watchpoint 3: *(double *) 0x7fffed853110

Old value = 0
New value = 2.4637061326127517e-16
MathExtra::matvec (ex=0x7fffed071380, ey=0x7fffed071398, ez=0x7fffed0713b0, v=0x7fffed467130, ans=0x7fffed853100) at /home/richard/GitHub/lammps/lammps/src/math_extra.h:499
499     }
(gdb) print ex
$30 = (const double *) 0x7fffed071380
(gdb) up
#1  0x00007ffff72d358a in LAMMPS_NS::FixRigidSmall::set_xv (this=0x5555557e6b50) at /home/richard/GitHub/lammps/lammps/src/RIGID/fix_rigid_small.cpp:1330
1330        MathExtra::matvec(b->ex_space,b->ey_space,b->ez_space,displace[i],x[i]);
(gdb) print b->ex_space
$31 = {2.0036683209243809e-16, -4.2351647362715017e-21, 1.0000000000000002}
(gdb) print b->ey_space
$32 = {1.5203323900358638e-05, 0.99999999988442967, 2.541098841762901e-21}
(gdb) print b->ez_space
$33 = {-0.99999999988442967, 1.5203323900358638e-05, 1.882112265263667e-16}
```

**Comment by akohlmey** [comment] 2020-10-31 15:46
@rbberger it is acceptable to have some numerical noise on the conversion from body position and orientation to atom positions. that should not accumulate, but there must not be any contribution to the z-component of body center of mass, velocity of the center of mass, or center of mass force, and similarly on the x- and y-component of torque, angular momentum, and omega.
After some of the recent changes, it looks like enforce2d is not only required in post force, but I fail to understand why.
We can suppress the effect by explicitly zeroing components in `Fix::initial_integerate()`, but that would be a band-aid solution.

**Comment by akohlmey** [comment] 2020-10-31 15:54
Analysis with valgrind also shows that we must not allow access to "body" and "masstotal" in `Fix::extract()` before the bodies have been fully initialized. Just pushed a change to that effect here 66ed16760f93a928196d49e7d60697b93cb9e412

**Comment by valesori** [comment] 2020-11-05 11:38
@akohlmey Hi Axel, thanks for taking a look at this. Unfortunately I don't know the source code well enough to be of any significant help with the debugging... Could I ask you if there is any "quick and dirty" fix you can think of that could prevent this problem at the script level?

**Comment by akohlmey** [comment] 2020-11-10 02:37
On Thu, Nov 5, 2020 at 6:38 AM valesori <notifications@github.com> wrote:

> @akohlmey <https://github.com/akohlmey> Hi Axel, thanks for taking a look
> at this. Unfortunately I don't know the source code well enough to be of
> any significant help with the debugging... Could I ask you if there is any
> "quick and dirty" fix you can think of that could prevent this problem at
> the script level?
>
for as long as we are trying to identify the source of the numerical noise
that leads to the drift you are seeing and then find a way to reliably
quell it, there is not much you can do. as the amount of drift is very(!)
small, you can probably just break your run down to multiple segments and
manually reset z-coordinates and velocities in between segments. you may
also want to experiment with the fix_modify bodyforces and the fix rigid
reinit keyword to see if any of that reduces the amount of accumulated
drift when resetting the z-direction contributions regularly.

axel.



-- 
Dr. Axel Kohlmeyer  akohlmey@gmail.com  http://goo.gl/1wk0
College of Science & Technology, Temple University, Philadelphia PA, USA
International Centre for Theoretical Physics, Trieste. Italy.

**Comment by valesori** [comment] 2020-11-10 08:32
@akohlmey Thank you for your reply. Yes, breaking the simulation in multiple segments seems like a good idea, actually that's what I started doing in the end. However I would like to point out that it's feasible only with fix rigid and rigid/nve, since the drift is basically exponentially increasing when using rigid/small and eventually causes a segmentation fault (and I still get very quickly a segmentation fault when using rigid/nve/small). So it seems that the problem is "catastrophically worse" when using the "small" versions of the fixes?

I include below the result of some longer tests I have run for reference. Hope this helps!

![z_rms_new](https://user-images.githubusercontent.com/50881862/98649077-6e8f7180-2337-11eb-8544-f1404f2f3d77.png)

**Comment by mkanski** [comment] 2023-03-09 10:51
It appears that adding a line `fix_modify fix_rigid bodyforces early` to the input file attached above solves this issue as I no longer see a segmentation fault during 1e9 step run. See also the attached RMS plot.

LAMMPS version: develop / patch_22Dec2022-9-gf84b64bc86-modified

![image](https://user-images.githubusercontent.com/20713012/223846588-1f725c17-699e-4e40-9f38-8cc6a2865335.png)

**Comment by sjplimp** [comment] 2023-03-30 17:04
The comment by @mkanski is a critical point.  If bodyforces early is not set (and it isn't by default), then the fix enforce2d operation has no effect.  That fix calls enforce2d() in the rigid fixes to zero out all the torque/angmom/other components which are inconsistent with 2d rigid body motion.  However that operation will happen at post_force in the timestep.  And then the rigid integrator in final_integrate() will compute the forces and torques.  I.e. the enforce2d zeroings will be no-ops.

I think one solution would be to have the fix modify bodyforces option default be "early" for 2d and "late" for 3d.  A user can still achieve the effect of "late" in a 2d model by making sure fix rigid is the next-to-last fix and fix enforce2d is the last fix.
But as it is now, "late" effectively makes fix rigid the last fix so that the 2d enforcement zeroings are ignored.

I'm still unclear why there is any non-zero z value, as in the plot above by @mkanski

**Comment by sjplimp** [comment] 2023-04-03 23:33
I ended up doing something different than my proposed solution a few days ago.  See PR #3274

@valesori Please check if the new PR #3724 addresses this issue - thanks for the test script.

@mkanski Thanks for the insightful comment about the earlyflag.  That helped me figure out where to add logic
to the two fix rigid vaiants.

**Comment by mkanski** [comment] 2023-04-04 08:29
Happy to help, but I just followed an advice from @akohlmey earlier in this discussion. :)

**Closed** 2023-11-15 12:08 UTC
Labels: bug
