### ISSUE TITLE
bug with dihedral_style nharmonic

### ISSUE THREAD

**Issue by ramisetti** [lammps/lammps#1141] opened 2018-10-01 17:17 UTC
## Summary

Using the commands _dihedral_style nharmonic_ and _dihdedral_coeff 3 10.0 20.0 30.0_ is leading to lammps ERRORs.

## Type of Issue

Bug Report

## Detailed Description (Enhancement Suggestion)

On quick inspection I see the below line in function coeff within dihedral_nharmonic.cpp is raising the ERROR: "Expected integer parameter in input script or data file (../dihedral_nharmonic.cpp:279)
Last command: dihedral_coeff 3 10.0 20.0 30.0"

int n = force->inumeric(FLERR,arg[1]); 

The code expects argument 1 to be integer but the example (dihedral_coeff 3 10.0 20.0 30.0) provided in the documentation has float for arg[1]. I tried changing 10.0 to 2 just as a trial but i get another ERROR: All dihedral coeffs are not set.

## LAMMPS Version (Bug Report)

2 Aug 2018

**Comment by akohlmey** [comment] 2018-10-02 09:00
Thanks for your report. The issue is with the documentation. It is missing the entry for the dihedral type. It should be something like this: `dihedral_coeff 1 3 10.0 20.0 30.0`, where `1` represents the dihedral type, `3` the number of harmonic dihedral force constants and then the individual force constants themselves.

you not all dihedral coeffs set has nothing to do with this. please see the dihedral_coeff documentation.
and update for the docs will be included in the next patch.

**Closed** 2018-10-05 18:20 UTC
Labels: bug, documentation
