### ISSUE TITLE
[BUG] _Segmentation fault(signal 11)

### ISSUE THREAD

**Issue by XGLyasuo** [lammps/lammps#3252] opened 2022-05-06 08:48 UTC
**Summary**

LAMMPS crashes in the run section

**LAMMPS Version and Platform**

lammps-29Sep2021 ,  run with Ubuntu 18.04 on viscode 

**Expected Behavior**

I want to run this computition with lammps , my study area is to cracking the c12 mol to small olefins and create new bonds

**Actual Behavior**

crashed on the runing section

**Steps to Reproduce**

the in.scrpit and data file as below

**Further Information, Files, and Links**

as the attach files
[4.C12.zip](https://github.com/lammps/lammps/files/8638755/4.C12.zip)

**Comment by akohlmey** [comment] 2022-05-06 09:52
@XGLyasuo This is not really a bug in LAMMPS, but caused by a combination of some unfortunate choices in your system setup, a limitation of the REAXFF package implementation in LAMMPS, and how you parallelize your run.

Please note the following:

- It is an error to use two thermostats on the same atoms at the same time, yet you are using fix nvt and fix temp/berendsen together. You must either replace fix nvt with fix nve or comment out fix temp/berendsen.

- Your system is initially not well suited for domain decomposition based parallelization with all atoms in one part of the simulation box. That creates a load imbalance and thus results in inefficient use of your CPUs and a slow simulation. But that also causes problems with the ReaxFF implementation in LAMMPS: once you start heating the atoms/molecules are becoming distributed (and the simulation more efficient and faster), but also the heuristics for storage of neighbors on each processor is no longer suitable and thus ReaxFF will stop when it runs out of reserved memory buffers on the MPI processors that didn't have any atoms before.  This can be resolved in multiple ways:
  * Do not use MPI parallelization. That avoids the memory buffer issue. If you have included the OPENMP package in your LAMMPS executable, you can use OpenMP parallelization instead (by setting the OMP_NUM_THREADS environment variable to 6 and adding `-sf omp` to your command line. Because the OpenMP parallelization is over particles and not domains, it does not suffer from the load imbalance
  * Use the KOKKOS package version of ReaxFF (you can compile KOKKOS for serial (= MPI-only) execution or OpenMP multithreading. The KOKKOS package version has a more robust memory management, but you still have the load balancing issue, so OpenMP parallelization is a better choice in this case, too.
  * Address the load balancing issue and irregular particle distribution with MPI parallelization by using the `balance` and `fix balance` commands by adding `balance 1.1 shift xyz 10 1.001` before the minimization and then `fix load all balance 1000 1.1 shift xyz 10 1.001` before the first run command. This will try to shift the subdomain divisions in such a fashion that each should have a similar number of atoms and thus the memory buffer heuristics will be more accurate. With fix balance this setting is adapted regularly during the run as the particle distribution changes. While MPI parallelization is typically more efficient, it is difficult to predict whether this is faster than OpenMP parallelization in this specific case. Possibly not.
  * You can increase the settings for `safezone` and `mincap` to have larger buffer sizes. This is not likely to be sufficient and not addressing the load balancing and thus performance issue.
 
For the rather small number of processors (6) that you are using the option to switch to OpenMP parallelization (either via the KOKKOS or via the OPENMP package seem the most promising approach.

**Closed** 2022-05-07 13:36 UTC
Labels: wontfix

**Comment by XGLyasuo** [comment] 2022-05-08 07:00
- *First of all, thanks a lot for Mr.akohlmey giving me some advice. But , unfortunately , when I did all the method except KOKKOS , I didn't solved the problem. I am really sorry for that. I think maybe there some wrong section of my work of checking the problem. So here are my questions on the problem checking things: 1. you said that not use the mpi parallelization, I compiled lammps in src with serials, but output echo stall reflect MPI 1 used with 0 OPENMP，I don not know how to useOpenMP to run a simulation.
- Maybe my cpu is not doing well in lammps, I use i-9900k to do the simu but the cpu occpy is 98.3% used , I don not know if  it is the  problem. 
-  I ask my classmate , they  told me that maybe my model is too big , so there maybe some wrong with my box settings

**Comment by XGLyasuo** [comment] 2022-05-08 07:01
> @XGLyasuo This is not really a bug in LAMMPS, but caused by a combination of some unfortunate choices in your system setup, a limitation of the REAXFF package implementation in LAMMPS, and how you parallelize your run.
> 
> Please note the following:
> 
> * It is an error to use two thermostats on the same atoms at the same time, yet you are using fix nvt and fix temp/berendsen together. You must either replace fix nvt with fix nve or comment out fix temp/berendsen.
> * Your system is initially not well suited for domain decomposition based parallelization with all atoms in one part of the simulation box. That creates a load imbalance and thus results in inefficient use of your CPUs and a slow simulation. But that also causes problems with the ReaxFF implementation in LAMMPS: once you start heating the atoms/molecules are becoming distributed (and the simulation more efficient and faster), but also the heuristics for storage of neighbors on each processor is no longer suitable and thus ReaxFF will stop when it runs out of reserved memory buffers on the MPI processors that didn't have any atoms before.  This can be resolved in multiple ways:
>   
>   * Do not use MPI parallelization. That avoids the memory buffer issue. If you have included the OPENMP package in your LAMMPS executable, you can use OpenMP parallelization instead (by setting the OMP_NUM_THREADS environment variable to 6 and adding `-sf omp` to your command line. Because the OpenMP parallelization is over particles and not domains, it does not suffer from the load imbalance
>   * Use the KOKKOS package version of ReaxFF (you can compile KOKKOS for serial (= MPI-only) execution or OpenMP multithreading. The KOKKOS package version has a more robust memory management, but you still have the load balancing issue, so OpenMP parallelization is a better choice in this case, too.
>   * Address the load balancing issue and irregular particle distribution with MPI parallelization by using the `balance` and `fix balance` commands by adding `balance 1.1 shift xyz 10 1.001` before the minimization and then `fix load all balance 1000 1.1 shift xyz 10 1.001` before the first run command. This will try to shift the subdomain divisions in such a fashion that each should have a similar number of atoms and thus the memory buffer heuristics will be more accurate. With fix balance this setting is adapted regularly during the run as the particle distribution changes. While MPI parallelization is typically more efficient, it is difficult to predict whether this is faster than OpenMP parallelization in this specific case. Possibly not.
>   * You can increase the settings for `safezone` and `mincap` to have larger buffer sizes. This is not likely to be sufficient and not addressing the load balancing and thus performance issue.
> 
> For the rather small number of processors (6) that you are using the option to switch to OpenMP parallelization (either via the KOKKOS or via the OPENMP package seem the most promising approach.

1. *First of all, thanks a lot for Mr.akohlmey giving me some advice. But , unfortunately , when I did all the method except KOKKOS , I didn't solved the problem. I am really sorry for that. I think maybe there some wrong section of my work of checking the problem. So here are my questions on the problem checking things: 1. you said that not use the mpi parallelization, I compiled lammps in src with serials, but output echo stall reflect MPI 1 used with 0 OPENMP，I don not know how to useOpenMP to run a simulation.
Maybe my cpu is not doing well in lammps, I use i-9900k to do the simu but the cpu occpy is 98.3% used , I don not know if it is the problem.
I ask my classmate , they told me that maybe my model is too big , so there maybe some wrong with my box settings

**Comment by akohlmey** [comment] 2022-05-08 10:26
> * *First of all, thanks a lot for Mr.akohlmey giving me some advice. But , unfortunately , when I did all the method except KOKKOS , I didn't solved the problem. I am really sorry for that. I think maybe there some wrong section of my work of checking the problem. So here are my questions on the problem checking things: 1. you said that not use the mpi parallelization, I compiled lammps in src with serials, but output echo stall reflect MPI 1 used with 0 OPENMP，I don not know how to useOpenMP to run a simulation.

How to include the OPENMP package and how to compile it and then how to use it correctly is all explained in the LAMMPS manual in great detail.

> * Maybe my cpu is not doing well in lammps, I use i-9900k to do the simu but the cpu occpy is 98.3% used , I don not know if  it is the  problem.

No. *All* of the suggestions work as indicated when used according to the LAMMPS documentation.

> * I ask my classmate , they  told me that maybe my model is too big , so there maybe some wrong with my box settings

No. Your model is rather small. 

Your problems are obviously a lack of training combined with a lack of studying the documentation and lack of experience in doing computational research and solving technical problems. Neither this website nor your classmates are right source of information. You need to discuss with your adviser how to get the proper training from a person with sufficient experience. By default that should be your adviser. I don't have the time and this isn't the place.

**Comment by XGLyasuo** [comment] 2022-05-09 04:28
> > * *First of all, thanks a lot for Mr.akohlmey giving me some advice. But , unfortunately , when I did all the method except KOKKOS , I didn't solved the problem. I am really sorry for that. I think maybe there some wrong section of my work of checking the problem. So here are my questions on the problem checking things: 1. you said that not use the mpi parallelization, I compiled lammps in src with serials, but output echo stall reflect MPI 1 used with 0 OPENMP，I don not know how to useOpenMP to run a simulation.
> 
> How to include the OPENMP package and how to compile it and then how to use it correctly is all explained in the LAMMPS manual in great detail.
> 
> > * Maybe my cpu is not doing well in lammps, I use i-9900k to do the simu but the cpu occpy is 98.3% used , I don not know if  it is the  problem.
> 
> No. _All_ of the suggestions work as indicated when used according to the LAMMPS documentation.
> 
> > * I ask my classmate , they  told me that maybe my model is too big , so there maybe some wrong with my box settings
> 
> No. Your model is rather small.
> 
> Your problems are obviously a lack of training combined with a lack of studying the documentation and lack of experience in doing computational research and solving technical problems. Neither this website nor your classmates are right source of information. You need to discuss with your adviser how to get the proper training from a person with sufficient experience. By default that should be your adviser. I don't have the time and this isn't the place.

thanks for your advice, I talk with my adviser yesterday with my problem, and modified my model, it worked when I turned my box size to 70 50 25, I would be better to study harder to learn lammps.
