### ISSUE TITLE
[BUG] GPU package (OpenCL) hangs during neighbor list building on Apple Silicon

### ISSUE THREAD

**Issue by andeplane** [lammps/lammps#3531] opened 2022-11-18 17:48 UTC
**Summary**

I'm trying to run LAMMPS using the GPU package (a simple lj/cut potential) on my Apple M1 Pro CPU/GPU which should be able to run OpenCL. When I run with
`/repos/lammps/src/lmp_mpi -pk gpu 1 neigh yes -suffix gpu -in run.in`
LAMMPS hangs during Verlet::setup (stack goes further into `FixGPU::setup` and [lmp_gpu_forces]https://github.com/lammps/lammps/blob/develop/src/GPU/fix_gpu.cpp#L323)) and eventually stops at [get_answers](https://github.com/lammps/lammps/blob/develop/lib/gpu/lal_answer.h#L133) I think.

However, if I run without computing neighbor lists on GPU
`/repos/lammps/src/lmp_mpi -pk gpu 1 neigh no -suffix gpu -in run.in`

it runs normally.

**LAMMPS Version and Platform**
LAMMPS (23 Jun 2022 - Update 2)
MacOS Ventura 13.0
Macbook Pro, Apple M1 Max

**Expected Behavior**

Simulation should run normally.

**Actual Behavior**

Code hangs at [get_answers](https://github.com/lammps/lammps/blob/develop/lib/gpu/lal_answer.h#L133).

**Steps to Reproduce**
Have a Macbook with M1 CPU.
Compile LAMMPS with GPU package using OpenCL (either CMake or Makefile).
Run any simple LJ script using GPU package.

**Further Information, Files, and Links**

I know that the GPU package isn't actively worked on, and Apple Silicon isn't a prioritized hardware, but for the curious eye, it would be cool to have it working as the GPU apparently is blazingly fast.

**Comment by akohlmey** [comment] 2022-11-18 18:07
@andeplane not sure if there is a chance to get this looked into. There are multiple points working against it:
- Apple seems to have completely abandoned OpenCL and wants people to use the Metal API instead. So if this is an issue in the OpenCL runtime, it may not get fixed.
- There needs to be a LAMMPS developer interested in making this work in contrast to other open issues in the GPU package
- There needs to be somebody with access to suitable hardware (most devs I know use Linux boxes). MacOS is not very accommodating (it used to be much better) and it seems to be getting worse over time.

**Comment by andeplane** [comment] 2022-11-18 18:10
Yeah, I didn't really expect anything. Feel free to close it as wont-fix, but now it's here for transparency anyway! I like your response time :P

**Comment by philipturner** [comment] 2023-01-23 03:11
> Apple seems to have completely abandoned OpenCL and wants people to use the Metal API instead. So if this is an issue in the OpenCL runtime, it may not get fixed.

I don't think broken OpenCL is the problem (except Apple's broken profiling timers). From my experience, MD libraries simply forget to add a switch-case for the Apple GPU vendor. e.g. not using the correct SIMD size. Once it works, you'll probably see seriously degraded performance compared to an equivalent Nvidia GPU. This requires investigation to find the issue.

Another issue is - the M1 architecture doesn't support double precision. Maybe that tripped a flag. Kahan Summation (FP64 emulation) strictly for energy accumulation can stop energy drift without needing mixed precision.

> There needs to be a LAMMPS developer interested in making this work in contrast to other open issues in the GPU package

> There needs to be somebody with access to suitable hardware (most devs I know use Linux boxes). MacOS is not very accommodating (it used to be much better) and it seems to be getting worse over time.

I do have suitable hardware, what do I need to do to test? I don't think this issue should be ignored because a decent portion of users are Mac users.

**Comment by akohlmey** [comment] 2023-01-23 05:37
@philipturner Thanks a lot for your interest in helping to improve LAMMPS.

> I don't think this issue should be ignored because a decent portion of users are Mac users.

In my experience very few of them use GPU acceleration. Most of the time macOS machines are used for programming or testing inputs before they are moved to proper parallel machines or supercomputers (which tend to run Linux these days).  So this is not that big a loss. More an issue for people with a desire for completeness.

If the GPU has only single precision it is going to be not very useful, anyway. What matters is not energy summation but forces and using Kahan summation has two issues: 1) it requires more operations, and 2) it requires turning off compiler optimization or else the compiler will eliminate it. That said, the OpenCL code path of the GPU library should be able to handle it, since it works for Intel Xe GPUs that also only have single precision hardware. There were a few issues that needed to be resolved, but that was addressed about a year ago, IIRC.

Regular compilation of LAMMPS on ARM based macs is very well supported. We have such a machine in our CI pool that runs integration and unit testing (next to an Intel based on), and if needed I also have virtual machines for interactive debugging (x86 only, tho).

> what do I need to do to test?

This is not a question of testing. That was already done by the OP. You would have to dig into the code in lib/gpu to identify and correct the issue. But you probably want to wait with that until we have merged PR #3599 which has some fixes for shared memory GPU issues that were discovered during testing.

**Comment by philipturner** [comment] 2023-01-23 12:25
> In my experience very few of them use GPU acceleration.

I'm concerned about a molecular CAD application using LAMMPS for real-time simulations. I want users to have GPU acceleration and not be disadvantaged compared to those with Nvidia GPUs.

> What matters is not energy summation but forces

Are you not using 64-bit fixed precision to accumulate forces?

> the compiler will eliminate it

That can be solved with the `volatile` keyword. Or at minimum, bit-cast each intermediate result to an integer, logical OR with a mask unknown as compile time, bit-cast back to float.

> That said, the OpenCL code path of the GPU library should be able to handle it, since it works for Intel Xe GPUs that also only have single precision hardware.

That means Kahan Summation has been implemented for OpenCL? Your website says the backend is no longer being maintained.

**Comment by akohlmey** [comment] 2023-01-23 13:10
> > In my experience very few of them use GPU acceleration.
> 
> I'm concerned about a molecular CAD application using LAMMPS for real-time simulations.

Which confirms my statement, since that makes your use case **very** unusual.
I would have to see how this works in practice, since I am having a hard time imagining how you would deal efficienctly with the overhead of initializing the GPU kernels for that use case. 

> I want users to have GPU acceleration and not be disadvantaged compared to those with Nvidia GPUs.

That is very honorable thinking. 

> 
> > What matters is not energy summation but forces
> 
> Are you not using 64-bit fixed precision to accumulate forces?

LAMMPS uses floating point math, not fixed precision. There are three compile time choices for the GPU package: all double precision, mixed single and double precision, all single precision. Please see the build instructions for the GPU package. GPU acceleration with the KOKKOS package currently uses double precision. The bulk of the LAMMPS code, however, runs on the CPU and from that, only the code in the INTEL package can use single precision (selectable at runtime) for SSE/AVX vectorization (which works best with the Intel compilers).

> > the compiler will eliminate it
> 
> That can be solved with the `volatile` keyword. Or at minimum, bit-cast each intermediate result to an integer, logical OR with a mask unknown as compile time, bit-cast back to float.

I don't think anybody has bothered. Only a subset of user use GPU acceleration, most of the time those are using machines in HPC clusters, which tend to be using predominantly data center grade Nvidia GPUs, a small subset uses AMD GPUs. I am not aware of any cluster built from mac machines. The last I knew of existed about 20 years ago.
Out of the people using LAMMPS on desktops and laptops a growing number uses precompiled pre-packages executables (or automated build systems like homebrew) and thus rarely even enable GPU acceleration.

> > That said, the OpenCL code path of the GPU library should be able to handle it, since it works for Intel Xe GPUs that also only have single precision hardware.
> 
> That means Kahan Summation has been implemented for OpenCL?

I am not aware of that. 

Anyway, in terms of performance, there is very little difference between the mixed and the single precision setting on GPUs worth using (where the ratio between single and double precision units is typically 2:1 or 3:1). Even for consumer grade GPUs (where the ratio is more like 10:1) the speed gain from all-single is less than what you would lose from using compensated summation. 

> Your website says the backend is no longer being maintained.

where exactly does it say that?

**Comment by philipturner** [comment] 2023-01-23 14:25
> I would have to see how this works in practice, since I am having a hard time imagining how you would deal efficienctly with the overhead of initializing the GPU kernels for that use case.

https://www.youtube.com/watch?v=HjgjtAk-lws&list=PLH78wfbGI1x3zNH-uA6RHNsf8AZnxTErI&index=29 - I'm trying to contact the project owners. I have no information except that they're using LAMMPS. For many citizen scientists, all they have is their personal workstation. I want it possible to simulate as large of simulations as possible. Especially since some of Drexler's designs range in the millions of atoms.

> LAMMPS uses floating point math, not fixed precision.

OpenMM converts forces to UInt64 with a fixed dynamic range. This permits atomically accumulating them across GPU threads. Then they're casted back to `float` before accumulating energy.

> Please see the build instructions for the GPU package. GPU acceleration with the KOKKOS package currently uses double precision

Any chance the KOKKOS package could use mixed precision? I'm working on a SYCL backend for M1 GPU that could have built-in IEEE-compliant FP64 emulation (~1:40 ratio) and integrate with Kokkos. Alternatively, we could use a double-single approach as outlined in [df64_qf128](https://andrewthall.org/papers/df64_qf128.pdf). I'll have to see how that turns out with OpenMM, but it requires investing less time than IEEE-compliant FP64. Are you okay with 48-bit mantissa but single-precision dynamic range?

> where exactly does it say that?

https://docs.lammps.org/stable/Packages_details.html#gpu-package - "The GPU code can be compiled with either CUDA or OpenCL, however the OpenCL variants are no longer actively maintained and only the CUDA versions are regularly tested." This gives me chills from GROMACS, which officially deprecated their OpenCL package in favor of SYCL. Are you deprecating OpenCL in favor of Kokkos?

**Comment by akohlmey** [comment] 2023-01-23 15:12
> Especially since some of Drexler's designs range in the millions of atoms.

Running such large systems on a single desktop machine with few CPU cores is not making sense.
That is what HPC clusters are for.

Also, using LAMMPS does not also automatically mean that such calculations can be GPU accelerated. GPU acceleration in LAMMPS means, that models that are available on the CPU need to be reimplemented on the GPU. PR #3599 is an example of that. I didn't have the time to listen to the entire talk, but what I noticed that could match LAMMPS was the use of the oxDNA/oxDNA1/oxRNA model. That is currently not at all GPU accelerated. I also found mention of AIREBO and Tersoff. Among those only Tersoff has GPU acceleration.

> OpenMM converts forces to UInt64 with a fixed dynamic range.

OpenMM and LAMMPS are on very different ends of the range of MD simulation implementations. OpenMM is optimized for small systems with a limited number of force fields and run on individual machines (E.g. via Folding@Home), while LAMMPS is primarily designed for large scale multi-node supercomputers. For the use case of OpenMM the fixed precision MD is a solution, for LAMMPS it is not so much.

> Any chance the KOKKOS package could use mixed precision?

Work on supporting single and mixed precision in KOKKOS is an ongoing project. It is a huge effort, but the LAMMPS team is small and most of us have to first serve the projects that provide funding, so priorities change all the time.


> https://docs.lammps.org/stable/Packages_details.html#gpu-package - "The GPU code can be compiled with either CUDA or OpenCL, however the OpenCL variants are no longer actively maintained and only the CUDA versions are regularly tested."

This is true, although not completely describing the current situation. None of the people that developed the GPU package are currently in a position to fully support it. However, we get regular contributions and bug fixes from the package developers, as well as contributions from other research groups, e.g. those developing the HIP backend.
There have been multiple contributions and improvements, specifically to the OpenCL backend since this statement was added to the manual. In part, because the person making the contribution works for Intel and it is within the scope of his work for Intel, to improve software for Intel hardware (including Intel GPUs).

> This gives me chills from GROMACS, which officially deprecated their OpenCL package in favor of SYCL. Are you deprecating OpenCL in favor of Kokkos?

No. The GPU package and KOKKOS are complementary. KOKKOS has a different strategy of utilizing GPU acceleration and thus it performs better in some cases, while the GPU package performs better in other cases. Also, the GPU package supports a wider variety of features.

**Comment by philipturner** [comment] 2023-01-23 15:46
> OpenMM and LAMMPS are on very different ends of the range of MD simulation implementations.

Hence, I was thinking OpenMM would be a more appropriate package for a single-user application. I've looked at benchmarks of OpenMM on the same simulation, and it's often 2x faster than GROMACS, NAMD, or competing packages for single-GPU. Hopefully I can ask people working on MSEP what system sizes they target, and whether simulation speed is even an issue.

> oxDNA/oxDNA1/oxRNA

That would be a better way to simulate large systems, because it simplifies certain dynamics. More complex, is the idea of fusing protein (or spiroligomer) engineering with DNA origami. Such interactions are harder to simplify to (e.g.) finite-element analysis. I wonder whether they chose LAMMPS because it's associated with material science (dense covalent structures) and OpenMM is associated with biomolecules (F@H). Either way if the project's still funded, they probably won't switch libraries this far in.

> Running such large systems on a single desktop machine with few CPU cores is not making sense.

I guess I was trying to stretch the limits of what's possible. Many moving parts could be thousands of atoms, a million caps. I'm considering assemblies of ~100 parts the ~100 nm range, which we also can't test in laboratories. Hopefully MD will explain the mechanics of how small groups of components interact, and we generalize that behavior to simulate larger systems quickly. Again, I'm just exploring what the computational bounds are.

> I also found mention of AIREBO and Tersoff.

I don't know much about these potentials, but OpenMM is designed to be portable to new algorithms. One functionality is writing custom force functions ([1](http://docs.openmm.org/latest/userguide/application/05_creating_ffs.html), [2](http://docs.openmm.org/latest/userguide/theory/03_custom_forces.html)). If they're using LAMMPS for potentials suited to dense covalent structures, would that be portable according to the doc pages I hyperlinked?

**Comment by akohlmey** [comment] 2023-01-23 16:17
> Again, I'm just exploring what the computational bounds are.

That may well be, but an Apple M1/M2 based mac is not the solution to that. If you want serious compute power in a single box without a cluster, you need a Linux workstation based on the latest generation of AMD or Intel server CPUs 
with multiple sockets. There you can have systems with 100s of CPU cores.

> I wonder whether they chose LAMMPS because it's associated with material science

The reason most people develop their models for LAMMPS is because LAMMPS is easier to modify than most MD codes and it allows to implement much more complex models than what you can do with most MD codes.  Specifically, the likes of GROMACS, AMBER, NAMD, CHARMM, OpenMM are mostly optimized for biomolecular force fields and excel at those, but it would be impossible to implement most of the more complex potentials that LAMMPS includes.

AIREBO and Tersoff are many-body potentials, ReaxFF (another very popular choice in LAMMPS) is manybody with charge equilibration on top of that and capable of modeling chemical reactions (in biomolecular force fields the bonds are an input).

So you need more support in the MD code than being able to enter the parameters and settings in order to implement  manybody potentials. They need different neighbor list construction methods. Tersoff and AIREBO need a "full" neighbor list and AIREBO also neighbors of ghost atoms in order to evaluate angle and dihedral terms. Also AIREBO constructs sub-lists from the neighbor list because the many-body terms affect only atoms within short distances or each other, so-called REBO lists. You can just look at the source code of, say, pair_morse.cpp and pair_airebo.cpp and should see the difference in complexity from the size of the files.

**Comment by philipturner** [comment] 2023-01-23 16:27
> That may well be, but an Apple M1/M2 based mac is not the solution to that. If you want serious compute power in a single box without a cluster, you need a Linux workstation based on the latest generation of AMD or Intel server CPUs
with multiple sockets. There you can have systems with 100s of CPU cores.

Extrapolating compute power, the M1 Max CPU has 8 P-cores with 777 FLOPS FP32. The GPU has 10616 GFLOPS FP32. Assuming 1.5x performance drop from mixed precision, that's a 9.1x advantage equivalent to 73 M1 CPU cores.

**Comment by akohlmey** [comment] 2023-01-23 16:43
> Extrapolating compute power, the M1 Max CPU has 8 P-cores with 777 FLOPS FP32. The GPU has 10616 GFLOPS FP32. Assuming 1.5x performance drop from mixed precision, that's a 9.1x advantage equivalent to 73 M1 CPU cores.

Force kernels on GPUs never reach the utilization of CPUs and you are ignoring that you cannot use Newton's third law to avoid data races. That cuts the speed advantage to less than half of your estimate. Also if you are comparing single precision floating point you have to factor in that the CPUs I mentioned support AVX 512 vector instructions. So, using the INTEL package (which BTW *does* support AIREBO) with Intel compilers will be quite competitive on such hardware.

That is not to diminish the performance that you may get out of your machine, but in my experience, the cost of human workforce is in general much higher than that of computer equipment. If I had a choice between getting a high-end workstation or spending the time on the kind of programming you are determined to do, it would be an easy choice to just spend the money on the expensive equipment, run calculations without worry, and focus on the science.

I think we have argued enough about this now. And it is also clear that neither of us will change the other's mind.

Finally, let me point out one important detail: according to the original post, the issue with OpenCL that Anders was experiencing was due to the neighbor list construction code on the GPU, and **not** the force kernel. He was able to run when he instructed LAMMPS to copy neighbor lists constructed by the CPU to the GPU.

**Comment by philipturner** [comment] 2023-01-23 17:18
> I think we have argued enough about this now. And it is also clear that neither of us will change the other's mind.

My apologies. I didn't mean to get into a sort of argument, I'm just trying to make the most out of my existing hardware. I'll consider your input, and evaluate whether it's possible to port.

**Comment by philipturner** [comment] 2023-01-24 05:41
Where in the talk did Drexler mention AIREBO and Tersoff? I did not find it anywhere.

**Comment by philipturner** [comment] 2023-01-25 00:51
> That is not to diminish the performance that you may get out of your machine, but in my experience, the cost of human workforce is in general much higher than that of computer equipment. If I had a choice between getting a high-end workstation or spending the time on the kind of programming you are determined to do, it would be an easy choice to just spend the money on the expensive equipment, run calculations without worry, and focus on the science.

You were right. LAMMPS would take significant effort to port this on the M1 GPU. That's why I was originally willing to devote significant time to help out. However, OpenMM is extensible enough that [it is possible to port AIREBO](https://github.com/openmm/openmm/issues/3929). It may be the first-ever GPU accelerated version in history. This is because implementing new force fields doesn't require modifying the actual code base. It just happens that the built-in forcefields are biomolecular ones. There's also an API for many-body forces, which I assume you researched before concluding that's "impossible to implement".

I'm going to see whether I can advise the MSEP team to switch from LAMMPS to OpenMM. There are certain massive simulations, where 10x more compute power makes the difference between possible and not possible. At least for my use case. I'll take your advice, and use Newton's third law to calculate atomic-forcefields, not as a substitute for atomic-fetch-modify-explicit.

**Comment by akohlmey** [comment] 2023-02-03 12:06
fixed in PR #3613

**Closed as completed by akohlmey** 2023-02-03 12:06 UTC
Labels: bug, gpu_package

**Comment by andeplane** [comment] 2023-02-26 20:13
Oh that was a simple fix haha. For those who are interested, I ran a simple LJ benchmark on my M1 Max to see how it performs, and get 110 million atomsteps/second for large systems. That's pretty good.

For the SW benchmark (512k atoms) that was done on KNL, it gets 63 million atomsteps/second. Single precision of course.

![lj_benchmark](https://user-images.githubusercontent.com/16174/221434273-ffa2aeaa-cd82-491e-8e3b-e04ccb4560fb.png)

**Comment by philipturner** [comment] 2023-02-26 20:48
I'm having difficulty understanding what that speed means. Real-world calculations don't spend 100% of the time calculating Lennard-Jones potentials. OpenMM's best performance is apoa1rf, 37 million atom-steps/second with 36 W. @andeplane would you mind re-running one of the better-performing LJ configurations while executing the command below? Are there any other benchmarks that provide million atom-steps/second?

```
sudo powermetrics --sample-rate 500 --samplers gpu_power
```

Also, perhaps compare the M1 CPU's performance to GPU performance?

**Comment by andeplane** [comment] 2023-03-09 23:00
Sorry, I missed this! So in short, I am running the attached script, with varying `x` variable that controls the size of the system. Running on a single thread using the GPU. I was just plotting what LAMMPS was reporting as a function on number of atoms

`Performance: 9950.223 tau/day, 23.033 timesteps/s, 103.187 Matom-step/s`

If I run using all 10 CPU cores only (no GPU), I get
`Performance: 1673.177 tau/day, 3.873 timesteps/s, 17.351 Matom-step/s`

While running `powermetrics` like you asked, it is averaging ~40% GPU (see one sample here)
```
**** GPU usage ****

GPU active frequency: 882 MHz
GPU active residency:  40.63% (389 MHz: 5.3% 486 MHz: 5.3% 648 MHz: 5.5% 778 MHz: 5.4% 972 MHz: 4.2% 1296 MHz:  15%)
GPU requested frequency: (389 MHz: 6.9% 486 MHz: 7.0% 648 MHz: 2.6% 778 MHz: 8.4% 972 MHz: 9.0% 1296 MHz: 6.8%)
GPU idle residency:  59.37%
GPU Power: 7204 mW
```

[run.in.zip](https://github.com/lammps/lammps/files/10936817/run.in.zip)

**Comment by philipturner** [comment] 2023-03-09 23:33
Something is off. That is not 40% GPU, that is 15% maximum power. FP32 is being severely underutilized. Note that this system may have few very neighbors per atom, meaning it gets much more ns/day than my benchmark for OpenMM.

Even with something not using SIMD-scoped operations, it's quite impressive. 6x faster than CPU, and I could easily see optimizations boosting that to 13x. To be fair, you'll likely get faster CPU when using 8 CPU threads. The remaining 2 E-cores slow the entire thing down, when OpenMP assumes it's homogeneous.

If you want to give it a shot, I [exposed the SIMD-scoped reductions from Metal to OpenCL](https://github.com/philipturner/opencl-metal-stdlib) and already see measurable speedups with OpenMM. Because of the LAMMPS repo owner's remarks, I no longer have motivation to invest my own time into optimizing LAMMPS. But you are free to incorporate the header into LAMMPS OpenCL if you wish.

**Comment by stanmoore1** [comment] 2023-03-09 23:38
Lennard Jones is memory bandwidth bound on GPUs, so this isn't surprising: `FP32 is being severely underutilized`. Not very much work there.

**Comment by andeplane** [comment] 2023-03-10 11:28
@philipturner Ave neighs/atom = 37.479664 in case you're wondering. Also 8 vs 10 cores didn't make a big difference, but a bit faster yep.

**Comment by philipturner** [comment] 2023-03-10 16:22
Would you be able to run [apoa1.pdb](https://github.com/openmm/openmm/tree/master/examples) through LAMMPS using the settings [described here for RF](https://openmm.org/benchmarks), then see what nearest neighbors, M-atoms-steps, and ns/day is? I'd like to replicate some OpenMM benchmarks as closely as possible with LAMMPS, or vice versa.

**Comment by akohlmey** [comment] 2023-03-10 19:22
This discussion is becoming seriously off-topic. The issue is closed and the problem resolved. If you want to continue discussing the performance of LAMMPS vs. OpenMM, please open a new issue with a suitable topic or (better yet) move the discussion to the [LAMMPS forum on MatSci.org](https://matsci.org/lammps/) which is a much more suitable place for such discussions.
